### ISSUE TITLE
How to configure Bitbucket Team Project Behaviour via Groovy?

### ISSUE THREAD

**Issue by atifrasheed79** [jenkinsci/bitbucket-branch-source-plugin#184]
Hi Team, 

We are already configuring "Discover branches" behavior for our Bitbucket team project. Now I want to add "Filter by name (with regular expression)" as well. 

I went through the respository but coudn't find any reference! Could you please advise how I can add/configure "Filter by name (with regular expression)" behavior for a Bitbucket team project via groovy (Jenkins init/bootstrap scripts). 

Appreciate your help.

**Comment by casz** [comment]
Add a behavior called filter by name ☺️

**Comment by casz** [comment]
I'll have to set out some ground rules for what issues are allowed on this repo.

Your much better off asking the question on the [Jenkins user mailing list](https://groups.google.com/group/jenkinsci-users/topics) or [Jenkins gitter](https://gitter.im/jenkinsci/jenkins)

Only concerned about actual issues or features, these features are best sent a pull request as I don't have time to develop them.

I'll create an issue template that will voice the same concern.
