### ISSUE TITLE
How to use "by default Jenkinsfile" mode

### ISSUE THREAD

**Issue by KnightYoshi** [jenkinsci/bitbucket-branch-source-plugin#186]
I was wondering how to use the "by default Jenkinsfile" mode.
There's a field for "Project Recognizers" which takes a Groovy script, but we rely on the globally accessible default Jekinsfile and only have a JSON config file in the project that tells the globally accessible default Jekinsfile how/what to run through configuration instead of a groovy script (to prevent anyone from doing something malicious with Groovy scripts).

**Comment by casz** [comment]
User question must be directed at the Jenkins user mailing list or Jenkins gitter
https://groups.google.com/group/jenkinsci-users/topics
https://gitter.im/jenkinsci/jenkins
