### ISSUE TITLE
Unable to scan team repositories from Bitbucket Cloud

### ISSUE THREAD

**Issue by andrei-dascalu** [jenkinsci/bitbucket-branch-source-plugin#188]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version : 

- [x] Bitbucket cloud

- [ ] Bitbucket server and version

### Description

Jenkins ver. 2.164.2
Plugin 2.4.4
Bitbucket cloud

I've recently setup a new Jenkins instance hoping to get it working with Bitbucket, but I've noticed a strange issue. My steps:

1. Create team with a few repos in BitBucket
2. Get key/secret credentials from team (setup with return URL filled, all rights checked)
3. Add key/secret credentials and select them in main configuration for the plugin. Other settings: cache enabled, manage hooks enabled
4. Create Bitbucket team/project and fill the following settings: credentials the same as above,  owner = team id from bitbucket.

On first scan, it's reported as a success BUT I am getting this message:

`
Connecting to https://bitbucket.org using <key>/****** (<team id>)
Could not resolve team details
`

Connecting is reported without error but scanned 0 repositories (out of 5)

However, using the same credentials to make a call to `site/oauth2/access_token` and get client_credentials, it works. Also, I can make a call to list repositories to `https://api.bitbucket.org/2.0/repositories/<team id>` using the token and it works (I can see the repos, etc).

If I setup a plain multibranch project selecting Bitbucket source with same credentials and using the same team name, I get an error saying that the team id wasn't found.

I am also getting a strange error:

`
java.lang.NullPointerException: Descriptor list is null for context 'class org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject' in thread 'Handling GET /job/bb-test2/configure from 188.24.8.190 : qtp1535128843-9 AbstractFolder/configure.jelly FolderLibraries/DescriptorImpl/config.jelly LibraryConfiguration/config.jelly SCMRetriever/DescriptorImpl/config.jelly MultiSCM/DescriptorImpl/config.jelly'
`
That seems related to required but deprecated plugin MultiSCM

Is there any advice you can give me? Thanks!

**Comment by gideao** [comment]
Jenkins ver. 2.164.2
Plugin 2.4.4
Bitbucket cloud

I'm also getting the same error as reported by @andrei-dascalu. 

It's just no possible to create a multibranch project setting Bitbucket as a "Branch Sources".

If I set the "Owner" value with a valid username a get the error: **Could not find: the_username_used**. But on Jenkins Log this error is seen.

`Caught exception evaluating: h.filterDescriptors(it,attrs.descriptors) in /job/trilogo-2-api/configure. Reason: java.lang.NullPointerException: Descriptor list is null for context 'class org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject' in thread 'Handling GET /job/trilogo-2-api/configure from 200.187.171.196 : qtp1327763628-3294 AbstractFolder/configure.jelly FolderLibraries/DescriptorImpl/config.jelly LibraryConfiguration/config.jelly SCMRetriever/DescriptorImpl/config.jelly MultiSCM/DescriptorImpl/config.jelly'
java.lang.NullPointerException: Descriptor list is null for context 'class org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject' in thread 'Handling GET /job/trilogo-2-api/configure from 200.187.171.196 : qtp1327763628-3294 AbstractFolder/configure.jelly FolderLibraries/DescriptorImpl/config.jelly LibraryConfiguration/config.jelly SCMRetriever/DescriptorImpl/config.jelly MultiSCM/DescriptorImpl/config.jelly'`

When I set "Owner" with a random name get the error: **Error while loading repositories from cache**. But I'm also get this error on Jenkins Log:

`java.io.FileNotFoundException: URL: https://api.bitbucket.org/2.0/repositories/erewrsdfsdfsdfsd?role=contributor&page=1&pagelen=50
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getRequestAsInputStream(BitbucketCloudApiClient.java:786)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getRequest(BitbucketCloudApiClient.java:806)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.lambda$getRepositories$1(BitbucketCloudApiClient.java:686)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getRepositories(BitbucketCloudApiClient.java:702)
Caused: java.io.IOException: Error while loading repositories from cache
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getRepositories(BitbucketCloudApiClient.java:705)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource$DescriptorImpl.doFillRepositoryItems(BitbucketSCMSource.java:1216)`

**Comment by lmbai** [comment]
@andrei-dascalu @gideao had this error too. My solution is to `downgrade to plugin 2.2.8`

**Comment by casz** [comment]
I welcome contribution, as I don't actively use bitbucket nor bitbucket cloud I have little time to dedicate to debugging. I have plenty of time to dedicate on pull request reviews 😅

**Comment by DanieleVistalli** [comment]
I guess I figured out the issue.

example:
https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java#L630

You can notice that the URL building code is using variable substitution but in the CloudAPIClient I've found a number of places where substitution is using the "{/owner}" pattern with a / inside the placeholder.

My guess (checking other code) is that it should be "/{owner}" so that the final API call is consistent.

I'm trying to build a fixed version myself. If this proves to be the real issue I'll submit a PR.

**Comment by DanieleVistalli** [comment]
I checked changes to the getTeam method over the past year and it appears a change happened to the way API calls are built (changed from string concatenation to templating) and that the template based solution is buggy. I cloned the repo but cant get to build it quickly (I get Compilation failure
[ERROR] java.nio.file.NoSuchFileException: C:\dev\gitroot\bitbucket-branch-source-plugin\target\classes\META-INF\annotations\hudson.Extension) I'll test the downgrade but will check if I can eventually get to build a fixed version.

**Comment by casz** [comment]
@DanieleVistalli you need to build with JDK 8 or bump parent pom

**Comment by DanieleVistalli** [comment]
@casz thanks. I'll give it a shot, I've a JDK 8 at hand. WIll let you know.

**Comment by DanieleVistalli** [comment]
I've experienced some weird behaviour. I checked out 2.4.4 and built it form source then re-deployed.. it magically works. The one installed by the plugin manager doesn't. This is weird.

**Comment by NandoTheessen** [comment]
The workaround we found was that a team member generated an app password and we used his credentials and that password to authenticate.
OAuth is still not functional though.

@DanieleVistalli are there maybe changes on there that didn't make it to the plugin repository?

**Comment by philomory** [comment]
Is Oauth _supposed_ to work with this plugin? There's no documentation about it at all, such as what the callback URL should be, how to store your client id and secret, etc.

**Comment by casz** [comment]
There is a unfinished PR which tried to add oauth support https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/69#issuecomment-434876443

**Comment by ieugen** [comment]
Yeah, so we have encountered this issue as well. Right now the integration is broken.
We don't have any projects discovered. It seems a lot of issues surrounding the bitbucket plugin and jenkins.

**Comment by lmbai** [comment]
@ieugen the version 2.2.8 should work for u.

**Comment by gideao** [comment]
@ieugen I resolved this issue using my credentials and not using "App passwords" or "OAuth". Apparently this plug-in don't support a OAuth authentication and I don't tested "App passwords". Give it a try and share with us what happened.

**Comment by casz** [comment]
I'll try and say it again. I am only a maintainer, I don't actively use bitbucket. If someone wants to actively maintain the Bitbucket integration I'd gladly accept a maintainer who actively uses Bitbucket. I'll also gladly review any contributions.

Please pick up the PR #69 to resolve using OAuth.

**Comment by ieugen** [comment]
Thanks @casz . Heard you loud and clear. 

I'm debugging this as we speak. So far I found out that the plugin is eating up exceptions like a fat kid eats cake. 

The url is buit ok (I presume). The response is not parsed ok. 
```
Jun 03, 2019 2:25:02 PM com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient getTeam
SEVERE: Exception getting team
java.util.concurrent.ExecutionException: Cannot load value for key: myteam
	at com.cloudbees.jenkins.plugins.bitbucket.client.Cache.get(Cache.java:67)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getTeam(BitbucketCloudApiClient.java:654)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMNavigator.retrieveActions(BitbucketSCMNavigator.java:517)
	at jenkins.scm.api.SCMNavigator.fetchActions(SCMNavigator.java:332)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:439)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:277)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:164)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:968)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: java.io.IOException: I/O error when parsing response from URL: https://api.bitbucket.org/2.0/teams/myteam
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.lambda$getTeam$0(BitbucketCloudApiClient.java:647)
	at com.cloudbees.jenkins.plugins.bitbucket.client.Cache.get(Cache.java:65)
```

**Comment by vivek** [comment]
@andrei-dascalu 

Best open an issue at Jenkins issue and report it against bitbucket-branch-source plugin with details on how to reproduce with enough details.

I tried both, creating bitbucket Team project and multi branch project, both works fine. I used my bitbucket username and app password. I used bitbucket-branch-source 2.4.4.

**Comment by ieugen** [comment]
@andrei-dascalu : what Jenkins version do you have?

**Comment by sheona-harry** [comment]
I see this issue too. 
Jenkins ver. 2.176.1
Plugin 2.4.4 (I had 2.4.5 but I downgraded to 2.4.4 based on some comment I saw that said would fix it but it didn't fix the issue.)
Bitbucket cloud

**Comment by ranjith-ka** [comment]
I have same issue, 2.2.8 worked for me

**Comment by djarnis73** [comment]
Hi

I found this issue while googling "Error while loading repositories from cache" which was the error I was getting trying to setup the plugin. What I found out was that I needed to use my team workspace id, not the team name (my team name was on the form team-name, the id was teamname) so when I removed the dash in the owner field things started to work for me.

I'm not sure if this is related to this issue, but perhaps it can help others.

Best regards Jens

**Comment by mtewordt1** [comment]
For my use the issue is not solved at all.  I have not been able to set up a pipeline using a BitBucket repository.  I'd be very grateful for any advise

**Comment by casz** [comment]
@mtewordt1 please see the user guide https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/docs/USER_GUIDE.adoc

**Comment by aivcec** [comment]
Any update on this?

I am facing this issue when I try to connect a Bitbucket Cloud repository to a multibranch project.
I am using Bitbucket Cloud.

Running Jenkins 2.230 and Bitbucket Branch Source plugin 2.7.0

**Comment by jetersen** [comment]
Same status as before: https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/188#issuecomment-498227004
https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/288

**Comment by jetersen** [comment]
However I would add #262 is close to landing.
