### ISSUE TITLE
No Bitbucket Notification when PR Build is triggered

### ISSUE THREAD

**Issue by quasarea** [jenkinsci/bitbucket-branch-source-plugin#189]
Similar to https://issues.jenkins-ci.org/browse/JENKINS-55617, 

I'm using Jenkins **2.150.3** and bitbucket-branch-source-plugin **2.4.2**

I'm using bitbucket stash v4.5.2, Jenkins/**Bitbucket Endpoints Hooks** has **Manage hooks** checked and **Webhook implementation to use** is set to **plugin** mode (as **native** is supported for stash >= 5.4)

My Multibranch Pipeline Configuration is as followed:
- Discover Branches - Exclude branches that are also filed as PRs
- Discover pull requests from origin - Merging the pull request with the current target branch version
- Periodically scan multibranch pipeline triggers - Interval 15 minutes

When a feature branch is pushed it will cause the BRANCH to be build.
When a Pull-Request on this branch is created, jenkins renders it in Pull requests section as not built.
Changes pushed to such PR do not trigger the build of it.
The branch is rendering as disabled (grayed, crossed out)

**Comment by casz** [comment]
You have to look under the PRs tab

**Comment by bjsee** [comment]
We have the same problem after updating from version 2.2.12 of bitbucket-branch-source-plugin to 2.4.4.
Everything works except auto triggering of PR branch builds after pushed changes.
