### ISSUE TITLE
refname missing from build statuses

### ISSUE THREAD

**Issue by warrickhill** [jenkinsci/bitbucket-branch-source-plugin#190]
Jenkins version: 2.164.2
Plugin version: 2.4.4
Bitbucket Cloud

Looking at the build statuses created by this plugin in Bitbucket i can see the the 'refname' field is left blank.

Can this be updated so that it is set to the name of the branch the same as Bitbucket Pipelines would.

**Comment by casz** [comment]
feel free to contribute
