### ISSUE TITLE
Question about Plugin and Jenkins version mismatch 

### ISSUE THREAD

**Issue by dimdiden** [jenkinsci/bitbucket-branch-source-plugin#191]
### Checklist for this issue

- [x] Jenkins version
2.39

- [x] Plugin version
2.4.4 - latest

- [x] Bitbucket cloud

### Description

Hello Team,

Sorry for this question, please point me to the right thread if that is not an appropriate place for asking such questions.

The plugin description says: Minimum Jenkins requirement: 2.60.3
Currently, we have Jenkins 2.39 which doesn't meet these requirements, unfortunately. It's quite risky for us to update Jenkins installation as we have quite an extensive number of jobs running without issues.
Is there any workaround we could use to get the plugin working without upgrading the Jenkins installation? For example, to install some previous plugin version... 

Thanks in advance!

**Comment by casz** [comment]
As long as you are running java 8 you should have no issues

**Comment by casz** [comment]
However I'd urge you to upgrade

**Comment by dimdiden** [comment]
Cool! Thank you very much for your answer!
Closing this question then.
