### ISSUE TITLE
CHANGE_AUTHOR variable not set

### ISSUE THREAD

**Issue by andrewandante** [jenkinsci/bitbucket-branch-source-plugin#195]
### Your checklist for this issue

- [x] Jenkins version **2.150.2**

- [x]  Plugin version **2.4.4**

- [x]  Bitbucket cloud

### Description

Having a problem where our builds are failing because we are trying to access the variable `${CHANGE_AUTHOR}` and it is not set - this appears to have changed since 2.4, but I can't confirm for sure.

As an example, in our Jenkinsfile:

```groovy
pipeline {
...
  stages {
  ...
    stage('Run detection scripts') {
      steps {
        script {
          AUTHOR_ID=sh([script: "./scripts/ci/author_id_script.sh ${CHANGE_AUTHOR} | tail -n1", returnStdout: true]).trim()
          currentBuild.displayName = "${CHANGE_TITLE}"
          currentBuild.description = "PR-${CHANGE_ID}"
        }
      }
    }
```

This first part of the script fails because `${CHANGE_AUTHOR}` is no longer defined.

**Comment by andrewandante** [comment]
Just adding that now that we have commented out that section, we are seeing the same error with `${CHANGE_TITLE}` - so something is really not right here.

**Comment by RayOei** [comment]
This is still an issue in v2.7.0
The CHANGE_* variables are not set

**Comment by Jetersen** [comment]
https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/204#issuecomment-594115291

**Comment by jglick** [comment]
Verified in 2.8.0 using a simple PR filed from an origin branch in BB Cloud. These variables are set:

```
CHANGE_BRANCH
CHANGE_ID
CHANGE_TARGET
CHANGE_TITLE
CHANGE_URL
```

but no `CHANGE_AUTHOR`. I believe https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/a18e9d41dca08652d2bb2ce71fbf113e9ae5fb5a/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java#L645 is not working—the action is added, but with all null values. https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/a18e9d41dca08652d2bb2ce71fbf113e9ae5fb5a/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/pullrequest/BitbucketServerPullRequest.java#L112 does not sound good (though I observed the problem with Cloud, not Server).
