### ISSUE TITLE
No repo discovery for Project Key

### ISSUE THREAD

**Issue by EyalZilberblum** [jenkinsci/bitbucket-branch-source-plugin#196]
### Your checklist for this issue

- [x] Jenkins version 2.150.1

- [x] Plugin version 2.4.2

- [x] Bitbucket cloud

- [ ] Bitbucket server and version

### Description

When configuring 'Bitbucket Team/Project' to use bitbucket cloud team for repository discovery, there is no option to filter by 'Project Key'.
When scanning Organization Folder, the plugin make a request to https://api.bitbucket.org/2.0/repositories/{username}

And there is a supported api that allow filtering the repos by Project:
https://api.bitbucket.org/2.0/repositories/{username}?q=project.key="{ProjectKey}"

This is really useful when there are many projects under the same team, allowing the handle each project repos, instead of all team repos at once.

**Comment by casz** [comment]
Use this traits plugin: https://plugins.jenkins.io/bitbucket-filter-project-trait
