### ISSUE TITLE
OAuth credentials support for Bitbucket Endpoints - manage hooks

### ISSUE THREAD

**Issue by szczepix** [jenkinsci/bitbucket-branch-source-plugin#197]
### Your checklist for this issue

- [x] Jenkins version: **2.164.3**

- [x] Plugin version: **2.4.4**

- [x] Bitbucket cloud ✔

- [ ] Bitbucket server and version ❌

### Description

As a user of this plugin, I want to opportunity to set OAuth authorization for Bitbucket Endpoints (_Manage hooks_) so that I don't must pay for another user for the only purpose of manage books.

This is required by our security policies. I can't add my user credentials because it's a full admin and I have 2FA. Another user is paid and I don't want to pay.

Bitbucket user = $$$
OAuth credentials = Free

**Comment by casz** [comment]
Feel free to contribute, you can pick up and rework #69

**Comment by szczepix** [comment]
@casz Where I can find actual Contribution information of this plugin (_CONTRIBUTION.md or sth_) and information about creating a Jenkins plugin? btw. I am a Junior DevOps Engineer and work mostly with C# 😉

**Comment by casz** [comment]
@szczepix https://wiki.jenkins.io/display/JENKINS/Plugin+tutorial is a good resource.
