### ISSUE TITLE
Pull request is not triggered when bitbucket webhook sends pullrequest:* event

### ISSUE THREAD

**Issue by ricxsar** [jenkinsci/bitbucket-branch-source-plugin#200]
### Your checklist for this issue

- [x] Jenkins version
Jenkins version: 2.171
- [x] Plugin version
Plugin version: 2.4.4
- [x] Bitbucket cloud
I'm using Bitbucket cloud
- [ ] Bitbucket server and version

### Description
I have setup the bitbucket cloud to notify our jenkins server to do a build and it is working but when a pull request is created or updated, it doesn't trigger a build.

The jenkins server is also setup using Bitbucket Team/Project and it is working fine, just the pull request part.

There's nothing wrong with my Jenkinsfile since if a manually trigger the build on pull request, it will execute the steps defined in there.

![image](https://user-images.githubusercontent.com/8968902/59237488-19749b00-8c2d-11e9-820f-1087e83f4e1f.png)

![image](https://user-images.githubusercontent.com/8968902/59237877-69a02d00-8c2e-11e9-8398-d147faf7670c.png)

![image](https://user-images.githubusercontent.com/8968902/59241324-c2c18e00-8c39-11e9-9d1e-cb915dde1014.png)

Here is by Jenkinsfile:
```
def ISSUES
pipeline {
    agent none
    stages {
        stage('Executing Tests') {
            parallel {
                stage('UI/UX Test') {
                    agent {
                        docker {
                            image 'rodolforicojr/katalon-jenkins'
                            args "-u root"
                        }
                    }
                    when {
                        changeRequest comparator: 'EQUALS', target: 'master'
                    }
                    steps {
                        dir('tests/katalon') {
                            script{
                                ISSUES = jiraSearch 'project = WCWT AND issuetype = Test AND "Cucumber Test Type" in (Scenario, "Scenario Outline")'
                            }

                            step([$class: 'XrayExportBuilder', filePath: 'Include/features', issues: ISSUES.join(';'), serverInstance: 'f9b8d4af-5dcb-4361-bad4-d0f2b1f7e49b'])

                            sh 'katalon-execute.sh -browserType="Firefox" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/RunFeatures" -executionProfile="staging"'
                        }
                    }
                    post {
                        always {
                            dir('tests/katalon') {
                                archiveArtifacts artifacts: 'report/**/*.*', fingerprint: true
                                // junit 'report/**/JUnit_Report.xml'

                                cucumber failedFeaturesNumber: -1, failedScenariosNumber: -1, failedStepsNumber: -1, fileIncludePattern: '**/*.json', jsonReportDirectory: 'report/cucumber_report', pendingStepsNumber: -1, skippedStepsNumber: -1, sortingMethod: 'ALPHABETICAL', undefinedStepsNumber: -1

                                sh label: '', script: 'cp report/cucumber_report/$(ls report/cucumber_report -t1 | head -n 1)/cucumber.json report/cucumber_report/cucumber.json'

                                step([$class: 'XrayImportBuilder', endpointName: '/cucumber', importFilePath: 'report/cucumber_report/cucumber.json', serverInstance: 'f9b8d4af-5dcb-4361-bad4-d0f2b1f7e49b'])

                                sh label: '', script: 'rm -R report'
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by hubez** [comment]
Same here. Bitbucket cloud webhook fires and Bitbucket Branch Source Plugin successfully receives it and creates the PR jobs, but then the jobs are not built.

Regular branches work, otherwise. Just not PRs.

**Comment by lelandsindttouchnet** [comment]
For What it's worth... I had a similar (?the same problem?) a few weeks ago. (note: I am using BitBucket server, and I keep Jenkins LTS and Plugins up to date regularly.) 

Creating a pull request in BitBucket would create the pull request in Jenkins, but the build would not start automatically. 

In the interest of troubleshooting I created a new "Bitbucket Team/Project" against a new project in Bitbucket and the PRs built automatically as expected. 

The instance of Jenkins in question is built programmatically, so I updated Project template (using the new/working Project), rebuilt Jenkins and all the PRs work as expected. (all of this to say it was no big deal for me to push the changes to all Jenkins projects.) 

Here is a diff of the significant changes in my Project Template. 

```
-    <jenkins.branch.NoTriggerOrganizationFolderProperty>
-      <branches>.*</branches>
-    </jenkins.branch.NoTriggerOrganizationFolderProperty>
+    <jenkins.branch.OrganizationChildHealthMetricsProperty>
+      <templates>
+        <com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric plugin="cloudbees-folder@6.8">
+          <nonRecursive>false</nonRecursive>
+        </com.cloudbees.hudson.plugins.folder.health.WorstChildHealthMetric>
+      </templates>
+    </jenkins.branch.OrganizationChildHealthMetricsProperty>
+    <jenkins.branch.OrganizationChildOrphanedItemsProperty>
+      <strategy class="jenkins.branch.OrganizationChildOrphanedItemsProperty$Inherit"/>
+    </jenkins.branch.OrganizationChildOrphanedItemsProperty>
+    <jenkins.branch.OrganizationChildTriggersProperty>
+      <templates/>
+    </jenkins.branch.OrganizationChildTriggersProperty>
```

I suspect it has something to do with `OrganizationChildTriggersProperty` 

significant changes: all of the other changes were plugin version related... 
for example... 
```
-<jenkins.branch.OrganizationFolder plugin="branch-api@2.1.1">
+<jenkins.branch.OrganizationFolder plugin="branch-api@2.5.2">
```

Hope this helps/let me know if you have any questions.

**Comment by ricxsar** [comment]
Hi @lelandsindttouchnet. Thanks for figuring out the problem.
Can you give me detailed instructions on how to resolve the problem. I don't want my old build lost along the way since it is already in sync to JIRA.

**Comment by lelandsindttouchnet** [comment]
Documenting the details of our Jenkins Deployment/Re-Deployment is more than I can cover in this thread. I would suggest that you try the first troubleshooting step of creating a new BitBucket Project, populating it with at minimum a Jenkinsfile, then building out the Jenkins side... create a branch, a commit, and then a pull request... If the test project builds the PR properly... we can work from there.

**Comment by ricxsar** [comment]
I'm using the jenkins docker image as our instance. What can I do from there?

**Comment by ricxsar** [comment]
Any updates on this issue?

**Comment by hubez** [comment]
I found the issue to my problem! My issue was I had a Build strategy to build Named branches, and I think this filter also filtered out Pull Requests. Once I removed this, Pull Requests started to build on creation.

I think my path of how I got stuck in it was this:
Reproduce:
1.  Install plugin version 2.4.1
1. Create Bitbucket Branch Source Plugin project
1. Configure a Build strategies -> Named Branches -> Names (regex) = ".*"
1. Do builds, branches trigger automatically
1. Create branch, then pull request, notice pull request won't build
1. Install plugin version 2.4.5
1. Create branch, then pull request, notice pull request still won't build

Fix:
1. Remove Build strategies -> Named Branches -> Names (regex) = ".*"
1. Create branch, then pull request, notice pull request **BUILDS!**

**Comment by MaroonedMind** [comment]
I'm currently facing this issue. I have a Mutlibranch Pipeline in Jenkins (v2.190.1) that discovers branches and pull requests. I'm using Bitbucket Server (v4.14.7) with Post Webhooks for Bitbucket (v1.6.3) plugin.
On Push events trigger branch jobs, but not pull request jobs. I've tried removing branch jobs and adding Change Requests to Build strategy to no avail. What could be the case? Do PR jobs react only to certain types of events?
