### ISSUE TITLE
Plugin affected by GDPR API changes?

### ISSUE THREAD

**Issue by lgg42** [jenkinsci/bitbucket-branch-source-plugin#201]
### Your checklist for this issue

- [x] Jenkins version
2.164.2
- [x] Plugin version
2.4.4
- [x] Bitbucket cloud

- [ ] Bitbucket server and version

### Description

Recently Bitbucket made important changes to their API, https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/
Just the day these changes took effect, our JenkinsX pipelines broke.
After a days, there was a fix for the BitBucket plugin (https://github.com/jenkinsci/bitbucket-plugin)
- https://github.com/jenkinsci/bitbucket-plugin/commit/5ad436628eeab744be56d5f2355c90f7603e9322
- https://github.com/jenkinsci/bitbucket-plugin/commit/bdc06ef471bd7847bdd8b2bbc5d0c44fd384281c

But JenkinsX don't use that plugin, it uses bitbucket-branch-source-plugin.

The issue we were experiencing "solved" by itself so we thought it was something additional at BitBucket API. And today, the pipeline broke again in the same way.

After reading and asking a lot, we're wondering if there could be some change needed in this plugin.

**Comment by casz** [comment]
cc @car-roll @vivek ?

**Comment by casz** [comment]
See #182

**Comment by lgg42** [comment]
Thanks a lot, I understand maybe that the latest release 2.4.4 doesn't have these latests commits that fix that api issue? I see the first commit for fixing it is from April 10 whereas the 2.4.4 release was April 7...

**Comment by casz** [comment]
@lgg42 there is nothing new to release? https://github.com/jenkinsci/bitbucket-branch-source-plugin/commits/master

As mentioned in another issue: https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/188#issuecomment-498227004

I am only a maintainer, I don't actively use bitbucket. If someone wants to actively maintain the Bitbucket integration I'd gladly accept a maintainer who actively uses Bitbucket. I'll also gladly review any contributions.

**Comment by vivek** [comment]
@lgg42 Can you provide details about how you are using bitbucket-branch-source plugin with jenkins-x? In our testing with Jenkins we find bitbucket Team project as well as multi branch pipelines to work fine with bitbucket cloud using bitbucket-branch-source plugin 2.4.4.

Best open an issue at Jenkins issue and report it against bitbucket-branch-source plugin with details on how to reproduce with enough details.

**Comment by lgg42** [comment]
Oh! I just saw that the PR (https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/182) was closed and not merged. Thanks a lot for your time!
I'm writting to Atlassian Support to confirm if the the reason of the PR closure stills holds to this date. I'll update this thread.

**Comment by lgg42** [comment]
Hello again, I got confirmation from BitBucket support that the username field compatibility is definitely not working as of today. I'll follow the thread in https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/182.
