### ISSUE TITLE
Webhook handling for Tags broken (JENKINS-57516)

### ISSUE THREAD

**Issue by rhnewtron** [jenkinsci/bitbucket-branch-source-plugin#202]
### Your checklist for this issue

- [x] Jenkins version - 2.150.2

- [x] Plugin version - 2.4.4

- [x] Bitbucket cloud - NO 

- [x] Bitbucket server and version - v5.11.3

### Description

Pushes to BitBucket for Tags are not handled by the plugin correctly. 
The following Error is printed when the webhook is configured:

```
Jun 12, 2019 7:36:50 PM com.cloudbees.jenkins.plugins.bitbucket.hooks.NativeServerPushHookProcessor$HeadEvent addBranches
INFO: Received event for unknown ref type TAG of ref v3.5.1
```
It seems the plugin is not expecting any tags, however tag discovery can be configured. 

When I manually scan the repo in the multibranch job with tag filtering enabled, I get proper discovery, however autodiscovery on webhook would be nice.

This seems to be related with https://issues.jenkins-ci.org/browse/JENKINS-57516

Example content for tags can be found here: https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html

```
{
  "eventKey": "repo:refs_changed",
  "date": "2019-03-07T11:38:15+0000",
  "actor": {
    "name": "richard.lees",
    "emailAddress": "removed@removed.co.uk",
    "id": 1260,
    "displayName": "Richard Lees",
    "active": true,
    "slug": "richard.lees",
    "type": "NORMAL"
  },
  "repository": {
    "slug": "dkr-jenkins-slave-hybris65",
    "id": 260,
    "name": "dkr-jenkins-slave-hybris65",
    "scmId": "git",
    "state": "AVAILABLE",
    "statusMessage": "Available",
    "forkable": true,
    "project": {
      "key": "PKR",
      "id": 231,
      "name": "Packer",
      "description": "Packer scripts for generating both AMI and Docker images.",
      "public": false,
      "type": "NORMAL"
    },
    "public": false
  },
  "changes": [
    {
      "ref": {
        "id": "refs/tags/test1",
        "displayId": "test1",
        "type": "TAG"
      },
      "refId": "refs/tags/test1",
      "fromHash": "0000000000000000000000000000000000000000",
      "toHash": "76e67f1b12f5232c76eb531099782f5058d2986e",
      "type": "ADD"
    }
  ]
}
```

It seems we hit the filter: https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/c81bc520c0f8057e82f6459c1132e97c6e2e6ca7/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/NativeServerPushHookProcessor.java#L146-L149

**Comment by szEvEz** [comment]
We are having the same issue.

**Comment by casz** [comment]
Feel free to send a PR 😅

**Comment by jakub-bochenski** [comment]
not stale

**Comment by jakub-bochenski** [comment]
not stale

**Comment by szEvEz** [comment]
not stale

**Comment by casz** [comment]
it's pretty stale if nobody wants to submit a PR.

**Comment by szEvEz** [comment]
Looks like this issue is solved by https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/230 - isn't it?

**Comment by casz** [comment]
Which has been out since 2.5.0: https://github.com/jenkinsci/bitbucket-branch-source-plugin/commit/237950221788d47785680ef5e2f2da4402299d25

**Comment by casz** [comment]
@szEvEz please report back whether it works or not 😓 
As I said multiple times I do not use it bitbucket any more 😅

**Comment by szEvEz** [comment]
@casz 
Tags are now successfully discovered. Looks like its working now properly and this issue can be closed as its solved by https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/230
Thanks!
