### ISSUE TITLE
Disable build status

### ISSUE THREAD

**Issue by zodiac1214** [jenkinsci/bitbucket-branch-source-plugin#203]
### Your checklist for this issue

- [ ] Jenkins version

- [ ] Plugin version

- [ ] Bitbucket cloud

- [ ] Bitbucket server and version

### Description

We should be able to disable build status notifier at runtime. For example, i want to turn off build status report for branch build and only enable for PR build.

**Comment by casz** [comment]
A trait plugin exist for this very reason https://plugins.jenkins.io/skip-notifications-trait
