### ISSUE TITLE
Proposal to add Source and Target environment vars on PRs

### ISSUE THREAD

**Issue by nWhitehill** [jenkinsci/bitbucket-branch-source-plugin#210]
One of the problems that I have run into while using this plugin is that when it builds a PR, it changes the environment variable GIT_BRANCH to the PR# . This is fine but it requires a fair amount of work to determine the source and target branch. In my use case in particular, I want a commit to PR branch to update the source branch's testing environment. I'm curious if the addition of 2 new environment variables on PR builds would be something the community would support. In other words, in addition to GIT_BRANCH being the PR number, also providing environment variables of SOURCE_BRANCH and TARGET_BRANCH on PR builds.

**Comment by cazzoo** [comment]
That would be a neat feature, I'm looking for the same feature
