### ISSUE TITLE
It is not possible to choose a job to trigger with Bitbucket Webhook

### ISSUE THREAD

**Issue by ppodbielski** [jenkinsci/bitbucket-branch-source-plugin#211]
I'm using  Jenkins 2.176 with Bitbucket cloud and bitbucket-branch-source-plugin 2.4.0.

Follow https://support.cloudbees.com/hc/en-us/articles/115000053051-How-to-Trigger-Multibranch-Jobs-from-Bitbucket-Server-  and everything works for me. 

But in my organization, I have often the situation that I have one Repository in bitbucket and e.g 2 Jenkins Multibranchpieline job. I don't want to trigger both project i.e when PR appear. Is there any way to specify which job should be triggered in such a case?

**Comment by quasarea** [comment]
you could have condition in Jenkins file that validates env.BRANCH etc and makes decision to build or not based on that

you could have different naming conversion and exclude some branches in first and other in second

**Comment by ppodbielski** [comment]
`you could have condition in Jenkins file that validates env.BRANCH etc and makes decision to build or not based on that` - it is a good solution in case when Jenkinsfiles are similar. What if they are completely different? e.g one is compiling and second is launching acceptance tests on separate env? 
`you could have different naming conversion and exclude some branches in first and other in second` - Whole code is on dev branch according to git flow.
