### ISSUE TITLE
BitbucketSCMFile.exists is never false for BitbucketSCMFile.child

### ISSUE THREAD

**Issue by cokieffebah** [jenkinsci/bitbucket-branch-source-plugin#212]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [ ] Bitbucket cloud

- [x] Bitbucket server and version

### Description
for:
Jenkins Version: 2.176.2
Plugin Version: Bitbucket Branch Source Plugin 2.4.5
Bitbucket Server Version: Atlassian Bitbucket v6.2.0

BitbucketSCMFile.exists is never false

looking through:
https://github.com/jenkinsci/scm-api-plugin/blob/master/src/main/java/jenkins/scm/api/SCMFile.java

and 

https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFile.java

and
https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/jenkins/plugins/git/GitSCMFile.java

...
BitbucketSCMFile does not appear to use Type.NONEXISTENT which is what SCMFile.exists() checks from the getType() property; when BitbucketSCMFile returns from newChild(...) (called by SCMFile.child) it only uses DIRECTORY or FILE as types unlike GitSCMFile.getType()

**Comment by casz** [comment]
@cokieffebah feel free to submit a PR :)

**Comment by cokieffebah** [comment]
@casz as time permits, I will take a deeper look.  I work on the templating-engine plugin and a user submitted an issue against us because of this issue. we have not worked with the bitbucket source plugin.  the user basically did most of the work/effort here, except the source code comparisons, I just passed along their info.

**Comment by cokieffebah** [comment]
my initial rough review, I think BitBucketScmFile.type() maybe should return NONEXISTENT by default or actually do a remote check ...

From https://github.com/jenkinsci/scm-api-plugin/blob/master/src/main/java/jenkins/scm/api/SCMFile.java#L279:

/**
     * The type of this object.
     *
     * @return the {@link Type} of this object, specifically {@link Type#NONEXISTENT} if this {@link SCMFile} instance
     * does not exist in the remote system (e.g. if you created a nonexistent instance via {@link #child(String)})
     * @throws IOException          if an error occurs while performing the operation.
     * @throws InterruptedException if interrupted while performing the operation.
     * @since 2.0
     */
    @NonNull
    protected abstract Type type() throws IOException, InterruptedException;

**Comment by cokieffebah** [comment]
Maybe your API needs to be extends to have a method like checkPathExists:
https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketApi.java#L127

... Like ...
/**
     * returns ScmFile.Type for the given path
     *
     * @param branchOrHash the branch name or commit hash
     * @param path the path to check for
     * @return ScmFile.Type
     * @throws IOException if there was a network communications error.
     * @throws InterruptedException if interrupted while waiting on remote communications.
     */
    ScmFile.Type typeForPath(@NonNull String branchOrHash, @NonNull String path)
            throws IOException, InterruptedException;
