### ISSUE TITLE
Handle repo rename correctly

### ISSUE THREAD

**Issue by petermcj** [jenkinsci/bitbucket-branch-source-plugin#216]
### Your checklist for this issue

- [x] Jenkins version: 2.176.2
- [x] Plugin version: 2.4.5
- [x] Bitbucket server and version: 6.3.2

### Description
Rename of a Bitbucket repo will create a new repo folder but leave the old as a folder in Jenkins. As consequence the jobs in the old repo can be built be mistake.
Either supply a way to delete the old or do the rename correct in Jenkins as well.

Same problem seems fixed in GitHub plugin: https://issues.jenkins-ci.org/browse/JENKINS-46068.

To reproduce:
1.	create a Bitbucket repo "A" with a jenkinsfile
2.	update/create organization folder in Jenkins
3.	rename Bitbucket repo to "B"
4.	=> 2 repos folders in Jenkins, A (with a Bitbucket icon) and B (with a folder icon)

**Comment by ksapede** [comment]
If anyone else runs into this issue, I was able to work around it by removing all builds in the folder with the previous name.  Once it was empty the folder was cleaned up by waiting one day (the time I have specified in the orphaned item strategy deletion policies) and running 'Scan Organization Folder Now'.
