### ISSUE TITLE
Consecutive builds should change key in API request

### ISSUE THREAD

**Issue by kyounger** [jenkinsci/bitbucket-branch-source-plugin#222]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [ ] Bitbucket cloud

- [x] Bitbucket server and version

Jenkins version: `2.176.2.3`
Plugin version: `2.4.4`
Bitbucket flavor: `Server` @ `v6.5.1`

### Description

When multiple builds for a single commit run, they should show up in BitBucket as consecutive builds; they instead replace the previous one, so you only ever see a single build.

When builds occur, each build pushes a new status for that specific commit. (https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java#L450)

You can see the status values are populated in this class: https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java#L185

According to BitBucket's docs on this API, to achieve the multiple build status effect, the `key` needs to change each time. We seem to be using the `hash` as the key; which wouldn't change after a rebuild.

https://developer.atlassian.com/server/bitbucket/how-tos/updating-build-status-for-commits/

I'm up for putting together a PR for this, but I want to gather information about what we should ultimately use for the `name` and `key` values. It seems to me that the `key` should be what we're currently populating into the `name`? Not sure what to use for a name at that point.

Here is a current GET of that endpoint to illustrate what is currently passed from a Jenkins instance with this plugin:

```{
  "size": 1,
  "limit": 100,
  "isLastPage": true,
  "values": [
    {
      "state": "SUCCESSFUL",
      "key": "712a01f5ad1e15642b85b1d8a4b4fd85",
      "name": "bb-server-team-name » repo-1 » master #22",
      "url": "http://example.com/master-1/job/example/job/repo-1/job/master/22/display/redirect",
      "description": "This commit looks good.",
      "dateAdded": 1567087389770
    }
  ],
  "start": 0
}```

**Comment by kyounger** [comment]
OH, also, the has that is in there _IS NOT_ the hash of the commit we're building. I can't quite figure out where it comes from.

**Comment by casz** [comment]
Feel free to open a pull request 😅

**Comment by kyounger** [comment]
I plan to, but was hoping to get some thinking from maintainers on the name/key pattern if you have any. If not, then I'll run with it.

**Comment by casz** [comment]
None I don't use bitbucket 😁 so I am not sure I can remember from memory how it all worked. I know I found bitbucket server lacking when I came to the build status.
