### ISSUE TITLE
PR notification always shows "build still in progress"

### ISSUE THREAD

**Issue by urol** [jenkinsci/bitbucket-branch-source-plugin#224]
This does not happen when writing your own notifyBitbucket in Jenkinsfile, but then you have a green button and a "still running" button  from the same build.

Bitbucket Branch Source: 2.4.5
Jenkins ver. 2.164.3
Bitbucket Server v6.4.0
Trigger: Webhook to Jenkins for Bitbucket Server 5.2.9 
![20190906_120854](https://user-images.githubusercontent.com/9250087/64420737-3986ef80-d0a0-11e9-9006-683f907bf2cd.jpg)

**Comment by tempora-mutantur** [comment]
@urol 
Hello.
This plugins should handle notifications itself.
What your pipeline looks like?
Do you see messages like `[Bitbucket] Notifying pull request build result` in your build output?

**Comment by urol** [comment]
@tempora-mutantur 
Yes notification takes place, but the state of the build is wrong. And its not depending on the what your pipeline lokks like. The problem is that this behaviour only takes places in our jenkins production instances. I can't reproduce it with another instance. So i close this ticket as not-reproducable.
