### ISSUE TITLE
Unable to scan repositories from a project using Bitbucket Team/Project plugin in Jenkins

### ISSUE THREAD

**Issue by wanderleyteixeira** [jenkinsci/bitbucket-branch-source-plugin#225]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [x] Bitbucket cloud

- [ ] Bitbucket server and version

### Description

Jenkins ver. 2.176.3
Plugin 2.4.6
Bitbucket Cloud

We have integrated Bitbucket Cloud repositories with Jenkins. The Bitbucket Cloud repo organization is as follows:

```
<team name>
  |--Project01
        |--RepoA
             |-Jenkinsfile
        |--RepoB
             |-Jenkinsfile
  |--Project02
        |--RepoC
             |-Jenkinsfile
```

We set up a new Jenkins job `New Item` -> `Bitbucket Team/Project` and specified <team name> as owner all projects. Set the `Behaviour` to `Filter by name (with regular expression)` and fill in the `Regular expression` with a project name or key. When I click on `Scan Organization Folder Now` in Jenkins it *ignores* all repos. 

Result:
`0 repositories were processed`

According to the `Filter by name`:
_A Java regular expression to restrict the project names. Project names that do not match the supplied regular expression will be ignored._

This is ignored. We should be able to get a list of repos based on a project so that projects in a Team can be separated in different jobs.

Note: This works fine with BitBucket Server version.

**Comment by casz** [comment]
filter name is for repo names if you want project names filtering you need an extension plugin: https://plugins.jenkins.io/bitbucket-filter-project-trait

**Comment by wanderleyteixeira** [comment]
@casz Thank you very much. Resolved.

**Comment by abdennour** [comment]
@wanderleyteixeira  could you share config-as-code code for jenkins + bitbucket cloud integration
