### ISSUE TITLE
How to reach a bitbucket post webhook payload json from a jenkins pipeline file?

### ISSUE THREAD

**Issue by AlerantAppNGIN** [jenkinsci/bitbucket-branch-source-plugin#229]
### Your checklist for this issue

- [x] Jenkins version: 2.176.2

- [x] Plugin version: 2.4.4

- [ ] Bitbucket cloud

- [x] Bitbucket server and version: Atlassian Bitbucket 5.14.1

### Description
I'd like to find a way to use the payload json received from a native BitBucket server's Post webhook in a Jenkins pipeline file.

As far as I can see, the payload json is received by the BitbucketSCMSourcePushHookReceiver.doNotify() method. Perhaps a possible solution would be to pass the entire payload to an environment variable and then use this variable from the pipeline file.

Please help me how to achieve this goal.

BR.

**Comment by tomasbjerre** [comment]
This is what https://github.com/jenkinsci/generic-webhook-trigger-plugin/ does.

**Comment by OmriHarary** [comment]
I would also like to know this. This is functionality that I require.

**Comment by duncwa** [comment]
Anyone get an answer to this question?

**Comment by jetersen** [comment]
The info is simply not exposed.

The closest you can get is `CHANGE_TITLE`, `CHANGE_URL`, `CHANGE_AUTHOR`, `CHANGE_AUTHOR_DISPLAY_NAME`, `CHANGE_AUTHOR_EMAIL`, `CHANGE_FORK`, `CHANGE_BRANCH`,  `CHANGE_TARGET`, `CHANGE_ID`

**Comment by kchrusciel** [comment]
Any update on this? I want to trigger build after the pull request merge. But I want to pass also event data to Jenkins

**Comment by samsonmaconi** [comment]
This works for me https://github.com/jenkinsci/generic-webhook-trigger-plugin/

**Comment by souris4science** [comment]
@samsonmaconi can you elaborate more on this? How did you manage to use generic webhook trigger in a multibranch pipeline using the Bitbucket Source Branch plugin? e.g. when a PR job is triggered how did you retrieve the data sent in the webhook request?

**Comment by duncwa** [comment]
I have used the danger gem to access the Bitbucket and GitHub pr json key value pairs and then post those in slack.  In a multi branch pipeline pr you get automatic updates to your pr status using the octokit gem for github.

**Comment by Arunrajg** [comment]
Any update on this? Bitbucket payload provides us useful information. Can this payload be exposed?

https://github.com/jenkinsci/generic-webhook-trigger-plugin/ does not work for Multibranch Pipeline Jobs
