### ISSUE TITLE
Concurrent build setting being retained after being disabled

### ISSUE THREAD

**Issue by angelo-loria** [jenkinsci/bitbucket-branch-source-plugin#233]
### Your checklist for this issue

- [2.176.2 ] Jenkins version

- [2.4.5] Plugin version

- [ X] Bitbucket cloud

- [ ] Bitbucket server and version

### Description

I have declarative pipelines that use disableConcurrentBuilds() under options. You can see the 'Do not allow concurrent builds' checkbox checked when viewing the branch job configuration. When I remove that option from the pipeline, that box remains enabled and concurrent builds remain disabled. I had to completely delete the Bitbucket organization folder and recreate it for it to enable concurrent builds. After removing that option, I tried rescanning the branches and restarting Jenkins but the setting remained enabled.  

I had to remove the affected branches from the filter, setting orphan item strategy to delete them immediately, rescan everything to delete them, and then add the branches back to the filter and scan again. After doing this, it recognized that the pipeline no longer included that option and started building concurrently.

**Comment by ostlerc** [comment]
I just ran into this as well. Seems nobody has fixed it yet.

**Comment by KalleOlaviNiemitalo** [comment]
Can you test whether the same problem applies to other branch-source plugins?

It seems pipeline-model-definition-plugin adds a [DisableConcurrentBuildsJobProperty](https://github.com/jenkinsci/workflow-job-plugin/blob/workflow-job-2.42/src/main/java/org/jenkinsci/plugins/workflow/job/properties/DisableConcurrentBuildsJobProperty.java) to the job, where it would naturally persist forever, but also adds a [DeclarativeJobPropertyTrackerAction](https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/v1.9.3/pipeline-model-definition/src/main/java/org/jenkinsci/plugins/pipeline/modeldefinition/actions/DeclarativeJobPropertyTrackerAction.java) indicating that the job property came from the pipeline script and should be deleted by [Utils.updateJobProperties](https://github.com/jenkinsci/pipeline-model-definition-plugin/blob/v1.9.3/pipeline-model-definition/src/main/groovy/org/jenkinsci/plugins/pipeline/modeldefinition/Utils.groovy#L532-L684) if it is ever removed from the pipeline script. Maybe the DeclarativeJobPropertyTrackerAction is somehow missing or contains incorrect information.

**Comment by mdealer** [comment]
The problem exists. We should stop wasting our time with stale bots and instead just investigate them.

Running Jenkins 2.375.3
