### ISSUE TITLE
Support for Bitbucket Cloud Projects

### ISSUE THREAD

**Issue by mlasevich** [jenkinsci/bitbucket-branch-source-plugin#242]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [x] Bitbucket cloud

- [x] Bitbucket server and version

### Description

Jenkins Version: 2.190.1 LTS
Plugin Version: 2.4.2/2.5.1-SNAPSHOT

Unless I am mistaken, this plugin currently does not  directly support BitBucket Cloud Projects. There is a single field "Owner" that for BB Server means Project and for BB Cloud means Team (or in both cases may also mean user). There is a trait that can help filter repos, but it is not same thing.

In the event of BB Cloud Team with a lot of projects/repos, this means that we will scan a lot more repos than we need to, and that we cannot easily separate different projects.  It also means we get title and avatar (once that is working) for the entire team instead of for the specific project - leading to confusion

My suggestion would be to separate  Owner into User, Team and Project fields, requiring a selection of either User (valid for either case) or Project in case of BB Server, or Team in case of BB Cloud with optional Project. May be less confusing to both configure and maintain...

i.e. UI of something like:

(If BB Server)
-----
 - [ ] User: ______________
 - [ ] Project: ___________
-----

(if BB Cloud)
-----
 - [ ] User: ______________
 - [ ] Team: _____________  Project: ___________
-----

In BB Server implementation just ignore "team" and in BB Cloud implementation use Team title/avatar if Project is not unique, else use Project info

Does this make sense?

**Comment by casz** [comment]
Use "Multibranch project" select bitbucket as source?

**Comment by mlasevich** [comment]
Wouldn't that be limited to a single repo? I want "project" functionality, like with BB server With Cloud we get "team" functionality, which is logical equivalent of scanning entire BB Server. :-/

**Comment by casz** [comment]
Use "Bitbucket team/project" job type and set owner to said team?

**Comment by mlasevich** [comment]
Yep. I will shut up and go away now :-) Although this makes it a bit more difficult to implement the avatar bit as I have to figure out how to distinguish team from project - different API endpoints (I think) - but I am guessing the code already figures it out somehow, so I should be able to find it..... Thanks.

**Comment by mlasevich** [comment]
Actually, I misunderstood what you said. It works as you say, but that is not necessarily a desired behavior. The plugin equates "Team" in Cloud to "Project" in Server, but they do not mean same thing. Both Cloud and Server have "Projects", but Cloud has "Teams" where Server equivalent is to have multiple instances of a server defined in Jenkins Config. I need to be able to specify a Project on Cloud just like we specify Project on Server :-/

**Comment by casz** [comment]
Not sure what your saying but to my knowledge this is already you can have multiple bitbucket endpoint configured.
If you want a single project either use filters or use the multi branch job type for that single project/repo

**Comment by mlasevich** [comment]
Ok, here is the scenario - Lets say we have 100 projects, each with 10 repos.

In case of Server - I point to the project, and it scans the 10 repos. In case of cloud I can either create a MultiBranch job for 1 repo (I want all 10), or a team-wide job limited to one project that will scan 10000 repos every time to find the 10 it needs. I want Cloud version to work just like Server version - i.e. be able to point to a Project and just scan those 10 projects. Added benefit is that I can get description and avatar for the specific project instead of the entire team.

I think we have some confusion in terms:
- "repo" - single git repository
- "Project" - a collection of repos
- "server" - a BB Server instance defined by a single URL. Effectively, this is a collection of Projects for BB Server
- "team" - Logical equivalent to "server" for BB Cloud. i.e. a collection of Projects in BB Cloud. 

Now, inside this plugin, "owner" means "team" for BB Cloud, but "project" for BB Server - causing disparity in functionality and confusion

**Comment by casz** [comment]
Use https://plugins.jenkins.io/bitbucket-filter-project-trait to filter your team?

**Comment by mlasevich** [comment]
Yes, I get that you can scan every repo in every single project and use traits to filter out just the repos in one project, but that does not scale well. We are still scanning 1000 repos to find 10. And if you do this for every project, you are now scanning 100,000 repos even though you have 1000 total. :-/ And again, you get the avatar/name for the team rather than for the project.
