### ISSUE TITLE
Needs to take preemptive auth for https://api.bitbucket.org/2.0/repositories/

### ISSUE THREAD

**Issue by ca-stefan-cordes** [jenkinsci/bitbucket-branch-source-plugin#246]
# Your checklist for this issue

- [2.190.1] Jenkins version

- [2.5.0] Plugin version

- [ X] Bitbucket cloud

- [ ] Bitbucket server and version

### Description

The doPreemptiveAuth in org.apache.http.client.protocol.RequestAuthCache is not called and
effect is that Multibranch Config Repositories for "Owner" are requested without authentication.
(and so just public repos are found)

As never before the authentication was needed from the context (authScheme=null),
the http-request is waiting for a http.response=401 to send the authentication.

But due 
https://api.bitbucket.org/2.0/repositories/candaservices?page=1&pagelen=50
is reachable without authentication, too (HTTP/1.1 200 OK) 
the credentials out of BitbucketUsernamePasswordAuthenticator.configureContext are never grapped and so response is always:
{"pagelen": 50, "values": [], "page": 1, "size": 0}

![image](https://user-images.githubusercontent.com/50696194/67854768-355fd700-fb11-11e9-9b68-b8d53bdb616e.png)

**Comment by casz** [comment]
Feel free to contribute :bow:

**Comment by ca-stefan-cordes** [comment]
Ok. I got a little closer.
BitbucketUsernamePasswordAuthenticator already performs a "pre-emptive auth" via setAuthCache 
according to 
https://hc.apache.org/httpcomponents-client-4.5.x/tutorial/html/authentication.html

but the element put into the cache is 
https://api.bitbucket.org
(with port==-1) whereas 
org.apache.http.client.protocol.RequestAuthCache.process(HttpRequest, HttpContext)
replaces the target with 
https://api.bitbucket.org:443
and so cache entry is not found.

```
       if (target.getPort() < 0) {
            target = new HttpHost(
                    target.getHostName(),
                    route.getTargetHost().getPort(),
                    target.getSchemeName());
        }
```

**Comment by ca-stefan-cordes** [comment]
No, it is not solved with adding concrete ports in
BitbucketUsernamePasswordAuthenticator
as 
{https://api.bitbucket.org:443=[B@4c64ecfc}
is already contained in authCache.

I need to find another root cause...

**Comment by ca-stefan-cordes** [comment]
Ok. Looks like it happens on authenticated proxy only:

com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.setClientProxyParams(String, HttpClientBuilder)

is re-settings the 
com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.context
and so the authCache added api.bitbucket.org:443 is gone.

**Comment by ca-stefan-cordes** [comment]
This is fixed with https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/248
