### ISSUE TITLE
User guide link on plugin site doesn't work

### ISSUE THREAD

**Issue by andham** [jenkinsci/bitbucket-branch-source-plugin#251]
The link for "Uer guide" under "Documentation" on the plugin site (https://plugins.jenkins.io/cloudbees-bitbucket-branch-source) doesn't work. I believe the correct URL should now be https://docs.cloudbees.com/docs/admin-resources/latest/plugins/bitbucket

**Comment by casz** [comment]
This is fixed in master as doc is moved to github though I have yet to create a release

**Comment by andham** [comment]
Great, thanks for quick response!

**Comment by casz** [comment]
Now updated 😊
https://plugins.jenkins.io/cloudbees-bitbucket-branch-source
