### ISSUE TITLE
Invalid statement in user guide

### ISSUE THREAD

**Issue by andham** [jenkinsci/bitbucket-branch-source-plugin#252]
In the user guide on https://docs.cloudbees.com/docs/admin-resources/latest/plugins/bitbucket it states that "This feature is only available for Bitbucket Cloud at the moment." for webhooks registrering. That is not true but it is supported for Bitbukcet Server as well in newer versions of hte plugin.
When trying to update the page via the edit link in top right corner I get a 404 page. Not sure how to report this invalid info other than here.

**Comment by casz** [comment]
I am not sure who over at CloudBees maintain the userguide or if we can even contribute

cc @oleg-nenashev @amuniz

**Comment by oleg-nenashev** [comment]
Sorry, missed it. I am not sure who maintains this area, CC @jphartley

**Comment by jphartley** [comment]
Somebody in Tammy Fox's team. Ashton is out.

**Comment by amuniz** [comment]
I think those docs should be moved to this repository, let me see if I can do it.

**Comment by amuniz** [comment]
https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/272
