### ISSUE TITLE
Indicate in project when automatic webhooks registrering is enabled

### ISSUE THREAD

**Issue by andham** [jenkinsci/bitbucket-branch-source-plugin#253]
If the plugin is configured to manage hooks, this is configured in the admin part of Jenkins. But normal users don't have access to that so the ydon't know if it is enabled or not.
I think it would be good if it could be indicated somewhere when the pluign has been configured to automatically manage webhooks in Bitbucket. Maybe in the configuration panel of the multibranch project, in the "Scan Multibranch Pipeline Triggers" section?

**Comment by casz** [comment]
it is indicated by the build log.

**Comment by andham** [comment]
I think that the build log is a bit late if I, as a end user, is to set up at multibranch build project. When setting up/configuring it would be nice to see this. Without having to wait for an actual build to look at the log for. But just my 2 cents on where I'd like to find this info as an end user.

**Comment by casz** [comment]
if manage hook is enabled it is for the entire instance, as end user you can assume that your Jenkins admins did their job 😅

**Comment by andham** [comment]
Sure. I'm just thinking that instead of require the Jenkins admin to create some wiki page where this is stated (and could possibly change as the plugin config is updated) the current configured behavior could be displayed to the end user within Jenkins.
But it's just a improvement suggestion as I didn't find the info in the UI crystal clear.

**Comment by casz** [comment]
I don't use the Jenkins UI, I rely on integrations on the Bitbucket/gitlab/github or whatever have you.

**Comment by andham** [comment]
Fair enough.
