### ISSUE TITLE
traits stopped working in 2.6.0 for job-dsl

### ISSUE THREAD

**Issue by lifeofguenter** [jenkinsci/bitbucket-branch-source-plugin#258]
- Jenkins version: 2.190.2
- Plugin version: 2.6.0
- Bitbucket server: 5.16.0

I used to be able to configure this via the job-dsl plugin:

```
    organizationFolder('foo') {
        displayName('Foobar')

        organizations {
          bitbucket {
            serverUrl('https://stash.foobar.com')
            repoOwner('foo')
            credentialsId('stash-token')

            traits {
              sourceWildcardFilter {
                includes('sample-project')
                excludes('')
              }
            }
          }
        }
```

this is not working anymore since version 2.6.0: 
<img width="318" alt="Screenshot 2019-11-11 at 10 20 47" src="https://user-images.githubusercontent.com/241073/68575790-23652900-046d-11ea-9216-1d3c6de0c380.png">

**Downgrading to 2.5.0 fixes the issue and brings back traits:**

<img width="299" alt="Screenshot 2019-11-11 at 11 13 59" src="https://user-images.githubusercontent.com/241073/68579458-71c9f600-0474-11ea-8350-4c4e337ec5c4.png">

Jira ticket: https://issues.jenkins-ci.org/browse/JENKINS-60155

**Comment by reitzmichnicht** [comment]
We have the same problem after updating to version 2.6.0 of this plugin.

**Comment by casz** [comment]
https://github.com/jenkinsci/structs-plugin/pull/52 this is the blocker, I can convert some of the changes but struct plugins is the culprit

**Comment by darxriggs** [comment]
@casz I don't understand your comment completely. Can you explain the required steps to solve this issue?

**Comment by casz** [comment]
revert the changes I did on generics traits or wait for to be released https://github.com/jenkinsci/structs-plugin/pull/52 which will fix the parameterized parameter types

**Comment by darxriggs** [comment]
@casz It looks like jenkinsci/structs-plugin#52 is stuck. Could you therefore, as already suggested, revert some changes so Job DSL works fine again?

**Comment by casz** [comment]
I would welcome a PR 😅
