### ISSUE TITLE
"The selected credentials do not have permissions to determine whether project does or does not exist" error

### ISSUE THREAD

**Issue by alexqfredrickson** [jenkinsci/bitbucket-branch-source-plugin#259]
- [X] Jenkins v.2.190.2
- [X] Bitbucket Branch Source plugin v2.6.0
- [X] Bitbucket Server v5.16.3

### Description

I am trying to configure Bitbucket's native webhooks to trigger a Jenkins Multibranch Pipeline job scan.  Under the job's configuration (`Branch Sources` -> `Bitbucket` -> `Owner`), I entered the project key associated with the repository I would like to trigger a Multibranch Pipeline scan on.

On save, I get the error "The selected credentials do not have permissions to determine whether [project key I specified] does or does not exist".

When I try to `Scan Multibranch Pipeline Now` anyway, a tooltip instantly pops up saying "Done.".  The scan does not occur.  Under logs, I see `Could not update folder level actions from source` and `Failed to recompute children of [project key I specified]` errors.

The errors persist after I delete and recreate the job.  The credentials I specified in the job's configuration have write access to the associated repository.  

Is this plugin intended to work only with Bitbucket Cloud?

**Comment by renzors** [comment]
I had a similar issue. In my case, The account that I used was unlocked in AD, but Bitbucket server locked my account also for some reason and it asked my for a catpcha when I tried to login directly there, I didn't notice it until I went to Bitbucket to test the login with my account. After login with captcha, Jenkins was able to retrieve the repositories.

**Comment by acxmatos** [comment]
Just for anyone wondering around this problem just like I was. In my case, we use a corporate internet proxy to manage Jenkins plugins. For some reason, this proxy was being used by the Bitbucket plugin during the credential validation call, resulting in an invalid authentication (401).

I could find the following on Jenkins fine logs, which led me to solve the problem:

Jan 23, 2020 5:09:06 PM FINE com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient
Using proxy authentication (user=xxx)

Jan 23, 2020 5:17:11 PM FINE com.cloudbees.jenkins.plugins.bitbucket.api.credentials.BitbucketUsernamePasswordAuthenticator
Add host=http://x.x.x.x:7990 to authCache.

As you can see, the BitbucketServerAPIClient class was using the proxy to make an internal call. In the Manage Plugin advanced settings, I just added the Bitbucket Server IP address to the "No Proxy Host" list, and the issue went away.

**Comment by nashpaz123** [comment]
I also had the pleasure. In the Manage Plugin advanced settings, added the Bitbucket Server address (in my case the full SQDN) to the "No Proxy Host" list

**Comment by nhattran2311** [comment]
> Just for anyone wondering around this problem just like I was. In my case, we use a corporate internet proxy to manage Jenkins plugins. For some reason, this proxy was being used by the Bitbucket plugin during the credential validation call, resulting in an invalid authentication (401).
> 
> I could find the following on Jenkins fine logs, which led me to solve the problem:
> 
> Jan 23, 2020 5:09:06 PM FINE com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient
> Using proxy authentication (user=xxx)
> 
> Jan 23, 2020 5:17:11 PM FINE com.cloudbees.jenkins.plugins.bitbucket.api.credentials.BitbucketUsernamePasswordAuthenticator
> Add host=http://x.x.x.x:7990 to authCache.
> 
> As you can see, the BitbucketServerAPIClient class was using the proxy to make an internal call. In the Manage Plugin advanced settings, I just added the Bitbucket Server IP address to the "No Proxy Host" list, and the issue went away.

thank you very much, I spent a lot of time on this problem.

**Comment by yszzu1** [comment]
FIY: try to use another account,  the repository will be displayed.   The current account must be limited by admin.
