### ISSUE TITLE
Can't set Credentials for manage hooks

### ISSUE THREAD

**Issue by mohammadasim** [jenkinsci/bitbucket-branch-source-plugin#260]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [x] Bitbucket cloud

- [ ] Bitbucket server and version

### Description

Jenkins version: 2.206
Plugin version: 2.6.0
Bitbucket cloud

I am following this guide [https://support.cloudbees.com/hc/en-us/articles/115000051132-How-to-Trigger-Multibranch-Jobs-from-Bitbucket-Cloud-?page=28](URL) to enable webhooks with a multibranch pipeline from Bitbucket Cloud.
In the first step of set up, Configure a Bitbucket Endpoint under Manage Jenkins > Configure System > Bitbucket Endpoints:
I can't access any of the credentials in my Jenkins server. When I click add to create credentials it takes me to create credentials form, I choose ssh key credentials, enter username and paste my private key, then I click add. After that I expect the credentials to be available to be selected but that doesn't happen.
I have tried different types of credentials, i-e username-password etc but nothing seems to work. I don't have any problems on the Jenkins server. All the plugins are up to date and the credentials already on Jenkins server seems to work fine when I choose SCM to be git in other pipeline or freestyle projects.

**Comment by marcelaraujo** [comment]
It works with username and password credentials
