### ISSUE TITLE
Bitbucket notifications are ignored in Jenkins, and the builds don't start

### ISSUE THREAD

**Issue by qalinn** [jenkinsci/bitbucket-branch-source-plugin#264]
### Your checklist for this issue

- [X] Jenkins version 2.190.2

- [X] Plugin version 2.5.0

- [ ] Bitbucket cloud

- [X] Bitbucket server and version 5.2.2

### Description

On Jenkins,  I have created a Bitbucket Team/Project job, I have configured according to this article: https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/121274372/Configuring+Webhook+To+Jenkins+for+Bitbucket
On Bitbucket, I have configured the hooks according to this  post: https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/381419546/Configuring+Webhook+To+Jenkins+for+Bitbucket+Bitbucket+Branch+Source+Plugin

When I have created a  new branch in a repo the bitbucket is notifying Jenkins but Jenkins didn't start the build. Please see the logs: Dec 10, 2019 9:49:27 AM FINE hudson.plugins.git.GitStatus
Received notification from "ipAddressFromMyfirewall" ⇒ https://jenkinsUrl.com/git/notifyCommit for uri = https://bitbucketUrl/scm/ARC/testbitbucket.git ; sha1 = 400f7c12f4889d5699dbb49eecd030788a7d8475 ; branches = [branch12]

Please let me know if I am doing something wrong or is it an issue?

The same issue is if I am pushing something on a branch/PR.
The same issue if I am creating a PR, the PR is not created on Jenkins as a job even if the bitbucket send the  notification

**Comment by casz** [comment]
I have no knowledge of this Bitbucket Server webhook to jenkins

You could consider upgrading bitbucket server to 5.4 or use this plugin: https://github.com/Eernie/bitbucket-webhooks-plugin

**Comment by qalinn** [comment]
I cannot update the bitbucket server.

**Comment by casz** [comment]
I have no intetion of supporting this other webhook plugin.
Please contact their support or use the two options I mentioned.
