### ISSUE TITLE
BitbucketCloudApiClient.executeMethod hangs the build

### ISSUE THREAD

**Issue by kedio** [jenkinsci/bitbucket-branch-source-plugin#276]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [x] Bitbucket cloud

- [ ] Bitbucket server and version

### Description

Jenkins: 2.217
Plugin: 2.6.0
Bitbucket: cloud

Since a couple of days ago almost all our builds hang before even printing anything. 

![Screen Shot 2020-01-27 at 5 15 39 PM](https://user-images.githubusercontent.com/3375074/73214866-614b2280-4129-11ea-8320-fc5bc0ba936b.png)

The only thing I could find initially was when I cancel the hanged build it shows this message:
```
Branch event
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.executeMethod(BitbucketCloudApiClient.java:858)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getRequestAsInputStream(BitbucketCloudApiClient.java:885)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getRequest(BitbucketCloudApiClient.java:909)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getAllBranches(BitbucketCloudApiClient.java:1029)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getBranchesByRef(BitbucketCloudApiClient.java:484)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getBranches(BitbucketCloudApiClient.java:474)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieve(BitbucketSCMSource.java:791)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:582)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:98)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:299)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Finished: FAILURE
```

![Screen Shot 2020-01-27 at 5 16 03 PM](https://user-images.githubusercontent.com/3375074/73215186-ec2c1d00-4129-11ea-8cb9-3e8bb6dc491d.png)

Then I added a Logger for `com.cloudbees.jenkins.plugins.bitbucket` and it keeps printing this line over and over 
```
Jan 27, 2020 11:10:42 PM FINE com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient
Bitbucket Cloud API rate limit reached, sleeping for 5 sec then retry...
```

To me, it seems like the build is hanging on trying to get the Jenkinsfile from bitbucket. Not sure why we suddenly reached the limit, because we are not building more PR than usual. Could Bitbucket now consider retry as a request toward the limit?

**Comment by dblanchette** [comment]
We have started seeing the same behaviour yesterday. Seems related to https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/275.
It looks like the https://api.bitbucket.org/2.0/repositories/{team}/{repo}/refs/branches call is now listing all branches, not only open ones. For example, we have a Mercurial repository with 3800 branches, so that's 380 calls every time it scans out of a limit of 1000 every hour...

**Comment by Twb3** [comment]
Would it makes sense to add a pageLen to the /refs/branches call?

**Comment by dblanchette** [comment]
> 
> 
> Would it makes sense to add the max pageLen to the /refs/branches call?

Yes, I will try to add it.

**Comment by pispico** [comment]
Same issue here, and my repo is not that big I have around 500 branches.
There is any way to workaround it?

**Comment by casz** [comment]
@Twb3 thanks for the PR.

If you feel like we should have a retry limit feel free to create an PR that implements the desired change.

**Comment by hemp** [comment]
Thanks for the PR.  Has anyone opened a support case around the API change effecting this?  I don’t mind doing that but wondered if anyone already had a response already.

**Comment by Twb3** [comment]
> Thanks for the PR. Has anyone opened a support case around the API change effecting this? I don’t mind doing that but wondered if anyone already had a response already.

I have a support case open with them.  I've asked if they've made changes to the branches endpoint.  I'll post an update here if I get any news.

**Comment by dblanchette** [comment]
I also have a support case open and got a reply:

> We have recently made changes to our API rate limit for repository Refs, to be in line with our API limits are documented here: 
https://confluence.atlassian.com/bitbucket/rate-limits-668173227.html
so all authenticated calls per user per hour to the repository endpoint are limited to 1k an hour. 
Our Dev team is working to revert those changes and increase the limit for branches endpoint calls. 
Once those changes are rolled out later today you shouldn't be facing this again with Bitbucket, apologies for this inconvenience.

**Comment by casz** [comment]
I still fix the PR #277 adds value even though they plan to roll it back 😆

**Comment by hemp** [comment]
Thanks for the quick release @casz and @Twb3 - installed now.

**Comment by hemp** [comment]
Following up, working well.  

Side things but related:

Folks on the team here are using <https://github.com/nvie/git-toolbelt#git-cleanup> to remove branches that have merged.  

I wish there were a way to make *Close Branch* an organization wide default.

We also reduced how often our few hundred repos 'scan' using this groovy: <https://gist.github.com/hemp/8bfe46a7b8b42b8ffbc1c20dc887dad4>

**Comment by casz** [comment]
@hemp good work, these are exactly what I would recommend you do.

Reduce the periodic trigger to rely on events.

**Comment by kedio** [comment]
I installed the new version this morning and we didn't reach the API limit for any of our builds since then.
You guys are amazing I wasn't expecting such a quick response!
@hemp I will also look into cleaning up the branches that have merged to help even further.

**Comment by casz** [comment]
@hemp thanks for linking to https://github.com/nvie/git-toolbelt

I liked the scripts and created a scoop manifest for those on windows https://github.com/ScoopInstaller/Main/pull/761 to easily install them into your path 😅
