### ISSUE TITLE
5-second retry exacerbates rate-limiting

### ISSUE THREAD

**Issue by abentley** [jenkinsci/bitbucket-branch-source-plugin#280]
### Your checklist for this issue

- [ X ] Jenkins version

- [ X ] Plugin version

- [ X ] Bitbucket cloud

- [ ] Bitbucket server and version

### Description
Jenkins: 2.161
Plugin: 2.4.1
Bitbucket: cloud

BitBucket allows 1000 requests per hour (though they are apparently fixing this https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/276#issuecomment-579409899).  If 1000 requests are made in the first second of an hour, all subsequent requests for the next hour will fail.  Since `BitbucketCloudApiClient.executeMethod` retries every 5 seconds, a single call to it while rate-limited could generate 720 http requests.  Two simultaneous calls will easily exceed 1000 requests, causing further rate-limiting.

The plugin could honour the Retry-After header, if present.  Alternatively, it could use exponential back-off.  

Another option (which could be combined with one of the the above) would be to put a lock around the 429-handling code-path, so that a maximum of 720 requests could be generated per hour.  It seemed pretty clear from our logs that the "Bitbucket Cloud API rate limit reached" was appearing in our logs more frequently than every 5 seconds.  Unfortunately, those logs seem to be lost now, so I can't attach them.

**Comment by casz** [comment]
Have a look at #269 and again I'd welcome any PRs

I recall in the bitbucket cloud api they do not provide any retry-after header to apache http library just assumes to retry.
