### ISSUE TITLE
Orphaned Item Strategy doesn't inherit its values to pipelines

### ISSUE THREAD

**Issue by arielman** [jenkinsci/bitbucket-branch-source-plugin#284]
Hi
We have Jenkins, where all the CI pipelines are automatically created by bitbucket branch source plugin. The issue is log rotation is not inherited by child jobs hence old builds are not deleted automatically (We marked the checkbox of 'Discard old items' and 'Days to keep old items' as 30 in the multi-branch configuration)

Plugin version: 2.2.10-som_patch_2

**Comment by casz** [comment]
`2.2.10-som_patch_2` this is a unsupported version.
Please update to a released version

**Comment by Vormillion** [comment]
The same issue for 2.8.0
