### ISSUE TITLE
Plugin needs a maintainer who actively uses bitbucket 🙏

### ISSUE THREAD

**Issue by jetersen** [jenkinsci/bitbucket-branch-source-plugin#288]
This plugin needs a maintainer who actively uses bitbucket.
https://jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/
https://plugins.jenkins.io/cloudbees-bitbucket-branch-source/
![image](https://user-images.githubusercontent.com/1661688/75810167-5ae44200-5d8a-11ea-9973-752982942dce.png)

**Comment by michallaskowski** [comment]
Hi. I am actively using Bitbucket Server. And we are using the plugin in our multibranch pipeline jobs.
I am not sure if I have enough time yet, what would be the scope?

**Comment by reitzmichnicht** [comment]
Is it recommended to switch to the official bitbucket plugin?
https://github.com/jenkinsci/atlassian-bitbucket-server-integration-plugin
Whats the difference concerning features and stability?

**Comment by michallaskowski** [comment]
@Jetersen I think I can help now with BitBucket 7.0, but given there is a new plugin, would be great to know what would be the long term plan.

**Comment by Jetersen** [comment]
The difference is that this plugin supports both Bitbucket Server and Bitbucket cloud.
Long term plan is just to continue support the features already exist. If someone has some great ideas how to improve it further are more than welcome to drive the project forward.

@reitzmichnicht switching plugin is up to you and you alone, I cannot recommend either. I cannot even recommend Bitbucket nor Atlassian as I do not understand why they chose to create a new plugin instead of improving an existing plugin with a rather large install base.

Bitbucket Branch Source plugin (supports both cloud and server): https://plugins.jenkins.io/cloudbees-bitbucket-branch-source/
![image](https://user-images.githubusercontent.com/1661688/76972663-331adf80-692f-11ea-94b8-4defd7e03428.png) 

Bitbucket Server plugin (supports ONLY server): https://plugins.jenkins.io/atlassian-bitbucket-server-integration/
![image](https://user-images.githubusercontent.com/1661688/76972774-5b0a4300-692f-11ea-8408-372b9859c323.png)

**Comment by Jetersen** [comment]
Regarding scope, it is totally up to the maintainer to choose the scope. So 🤷‍♂

**Comment by ryancurrah** [comment]
I don't know a ton of Java. But I could help maintain it and try to automate some integration testing against different versions of Bitbucket. Does CloudBees not give you any funding for this project? It's like one of their customers most useful plugins.

**Comment by OmriHarary** [comment]
Just spitballing here, but if this plugin is lacking in a maintainer, and the official one is lacking in functionality, does it make sense to work towards merging the two?

**Comment by jetersen** [comment]
@OmriHarary I mentioned this is the mailing list when atlassian announced their plugin.

It seemed like they were very much against that idea, without any good reasoning.

https://groups.google.com/forum/#!searchin/jenkinsci-dev/bitbucket$20server|sort:date/jenkinsci-dev/3BTEJjqB-mo/p6Lb33SAAQAJ

**Comment by Zauxst** [comment]
Pardon to interject, but I didn't get that from their response, even more, I didn't get to see your proposition either.

Since they are looking to be part of the "recommended plugins" and are required to reach a popularity threshold which this plugin seems to pass with flying colors, it might be worth to specifically suggest that merging them. Or at least drag them here :) to be part of these discussions (on this github issue).

I can see both plugins being a thing on their own and in unison, as their plugin is working on a particular repository while this plugin has a multi-pipeline target, it might be worth it to everyone to suggest this... Or at least explain to them this functionality which most of us here, love it.

**Comment by OmriHarary** [comment]
I have to say that I agree with @Zauxst, I don't read that from their response nor do I see the proposition itself.

Whether or not it makes sense that they created yet another Bitbucket plugin for Jenkins when there are already so many, I think finding if there is a way to unite the two could ultimately lead to the best outcome, especially for the plugins' users.

**Comment by jetersen** [comment]
I might be reading in between the lines as a frustrated maintainer 😅
Again those that want to take over maintainership will have to take this chat with Atlassian... I have given up on anything Atlassian related.

**Comment by jetersen** [comment]
I'll point to this as my disappointment in Atlassian: https://jira.atlassian.com/browse/BCLOUD-5814?error=login_required&error_description=Login+required&state=6a723ea3-7015-4bc9-b6e7-f506b4182a0f

**Comment by mattiassluis** [comment]
I proposed to Atlassian as well to support this plugin or look at integrating while dealing with Bitbucket Server 7 compatibility issues. I looked also at their plugin and the features back then and it looks like they take a different approach.
I might be mistaken but from what I noticed it doesn't support:
* The webhooks plugin from Topicus (which doesn't require admin level access on repositories)
* Project level configuration (configure each repository individually)
* SSH Checkout (seems to be a PR in progress tho)

With regards to maintainership, our team has the willingness to help but we lack the Java and Jenkins Plugin knowledge which I think is crucial to keep the quality level of this project when it comes to contributions or understand the contents of pull request changes at the required level. At the same time I guess at this point it is better to have a few less knowledgable maintainers than no maintainers at all?

**Comment by jglick** [comment]
I have heard a useful distinction be made, between pull request _reviewers_ and _approvers_. A reviewer would look at the **Files** tab and point out low-level things that are not caught by current automation (CI, style apps): this comment is confusing, this API call is incorrect here, this variable reference could throw a `NullPointerException`. An approver would be someone who takes responsibility for releases and doing manual sanity tests where necessary, and would make overall comments on a PR: this UI choice is inconsistent, we are not yet ready to drop BB Server 4.x support, the added complexity in the code here is not justified by the trifling improvement, this is not perfect but it is a net gain so we should go ahead and merge it. If you cannot find anyone who can take on both roles, it is best to have some people in each role, and it is easier to find volunteers to help review while an approver needs to make a longer-term commitment.

**Comment by bitwiseman** [comment]
I have merge permissions on this plugin now.  I would rather there be a community maintainer of this plugin - someone who can guide this plugin forward not just take some PRs.  For now I'll go ahead and review and merge the existing PR/fixes and cut a release.

**Comment by 2improveIT** [comment]
I am actively using this plugin with bitbucket server, and have already submitted some pull requests for this plugin.
I am supporting my clients with this plugin, and have a deep knowledge of java,  and this plugin (especially the bitbucket server part of it).

**Comment by 2improveIT** [comment]
> I am actively using this plugin with bitbucket server, and have already submitted some pull requests for this plugin.
> I am supporting my clients with this plugin, and have a deep knowledge of java, and this plugin (especially the bitbucket server part of it).

@jetersen how can I become a maintainer ?

**Comment by jetersen** [comment]
@2improveIT good place to start.

https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/

**Comment by 2improveIT** [comment]
> @2improveIT good place to start.
> 
> https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/

Thx, I just applied for it.

**Comment by maulik-modi** [comment]
hello @jetersen , Do we have any other contributor from Atlassian team ?
![image](https://user-images.githubusercontent.com/34910430/104925299-a7e1fe80-59c4-11eb-825f-79f20a87e608.png)

**Comment by bitwiseman** [comment]
@maulik-modi 
That seems like a question for a discussion and/or another issue.

**Comment by Zauxst** [comment]
Hi, who is in charge of merging PRs? 
There are multiple PRs opened that seem to improve the quality of the plugin overal.

Can we do anything to speed up the process?

**Comment by bitwiseman** [comment]
@Zauxst Would you like to become a maintainer on this plugin, taking responsibility ensuring PRs are well tested and do not break existing functionality?

**Comment by 2improveIT** [comment]
Hi,

I also want to become a maintainer, like already asked before.


Kind regards,

Hein

**Comment by mguillem** [comment]
Hi
is there a maintainer here? According to the plugin page there are 8 maintainers for this project. Could one of them have a look at the opened pull requests?

Thanks
Marc

**Comment by lifeofguenter** [comment]
Hi all 👋🏽 ,

I am going to close this issue for now. We have nine maintainers assigned to the project and it has been relatively active already.

I will be doing some cleanups and try my best to facilitate for the awesome work from all contributors and maintainers. If anyone wants to reach out, I will be trying to be active in our gitter chat :)
