### ISSUE TITLE
Bitbucket events not registered automatically 

### ISSUE THREAD

**Issue by george2515** [jenkinsci/bitbucket-branch-source-plugin#296]
### Your checklist for this issue

- [x] Jenkins version
           2.240.5
- [x] Plugin version
           2.7.0
- [ ] Bitbucket cloud

- [x] Bitbucket server and version
           6.7.3

### Description

Hi, 
We are trying to upgrade to the latest version of jenkins lts and after upgrade the bitbucket-branch-source-plugin does not register proper webhook events. The webhook gets registered;however, no Pull requests/Repository events are selected on the Bitbucket side. Only when we manually select on merge, on pull request, etc does the webhook trigger and kicks off the build accordingly. This is problematic because we are dealing with quite a large number of repositories.
We are using the post-webhooks for Bitbucket (2.3.15) plugin.

The project jobs have been configured based on plugins documentation. Are we missing something or is this a bug?

Thanks

**Comment by ryanwoodsmall** [comment]
- [x] Jenkins version
   2.222.1
- [x] Plugin version
   2.7.0
- [ ] Bitbucket cloud
- [x] Bitbucket server and version
    6.9.1 / 6.10.3 / 7.0.3 / 7.1.1

Can verify this is happening using the "plugin" webhook provider, using the Bitbucket "Post Webhooks for Bitbucket" version 2.4.2 (and 2.2.23 as well). The "native" webhook provider seems to work, at least on Bitbucket Server 7.1, and enables push/PR event triggers, but this is an all-or-nothing change at the Bitbucket Server level and changing many existing repositories and jobs is non-trivial and pretty invasive.

https://support.cloudbees.com/hc/en-us/articles/115000053051-How-to-Trigger-Multibranch-Jobs-from-Bitbucket-Server mentions https://github.com/topicusfinan/bitbucket-webhooks-plugin but that repo appears to have gone missing.

Reaching out to the Move Work Forward folks https://marketplace.atlassian.com/apps/1215474/post-webhooks-for-bitbucket but not sure what to expect.

**Comment by leonkyr** [comment]
Thanks for creating this. We are looking into this right now @ryanwoodsmall and @george2515 

Is it possible you attach to the support request the debug log of Bitbucket server and your configuration?

Thanks,
Leo

**Comment by george2515** [comment]
There is nothing suspicious in the Bitbucket logs. Webhook registers just fine.
We have tested the Post Webhook plugin's API on Bitbucket side and we were able to manually register a webhook with properly configured events. For anyone that is interested here is the link:

https://moveworkforward.atlassian.net/wiki/spaces/DOCS/pages/867205121/Atlassian+Bitbucket+Post+Webhook+API

All of this leads me to believe the payload this plugin is posting over to Bitbucket is incorrectly set under certain circumstances so I would start my investigation there.

For anyone that is experiencing the same problem, we exxplicitly disabled this plugin's hook management and added a temporary stage to our pipelines that filters through webhooks based on registered URL and either updates an existing webhook with proper events or creates a new webhook with the same events. Needless to say, events configured correspond to the types of pipelines (PR build/Branch build/Release build, etc).

**Comment by leonkyr** [comment]
I got a feeling that one of our latest version broke the API contract 
https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/3dbf6b60550d90ab6e98991f51740c4bc279ffb4/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/repository/BitbucketServerWebhook.java#L11

We are looking into this today. If possible please revert to 1.12.23

**Comment by ryanwoodsmall** [comment]
1.12.23 creates the webhook and enables the event triggers as expected on my test system.

**Comment by leonkyr** [comment]
We identified the issue in the latest version:  we added events to the POST payload in order to provide more control over API, but didn't carry on the backward compatibility on the events list.

We are release a fix for this today.

Really sorry for the inconvenience.

**Comment by leonkyr** [comment]
Please upgrade [Post Webhooks for Bitbucket](https://marketplace.atlassian.com/apps/1215474/post-webhooks-for-bitbucket?hosting=server&tab=overview) to 2.4. (the latest version).

The issue has been fixed.

I believe this issue can be closed.

**Comment by ryanwoodsmall** [comment]
@leonkyr : Verified that 2.4.3 fixes my issues. Will let @george2515 handle closing since this is his issue. Thanks to everyone for the turnaround here!

**Comment by george2515** [comment]
Folks please feel free to close this if @ryanwoodsmall has confirmed resolution. I am not sure when I will have time to look into this again. 
Next time we do some upgrades, I will give automatic webhook registration another shoot. 

Thanks for the turnaround!

**Comment by ryanwoodsmall** [comment]
@leonkyr @george2515 Spoke too soon: 2.4.3 appears to have broken the PR workflow, at least on our end. Pull/branch events work as expected, but a PR/merge/delete branch doesn't trigger a build after the merge after the as it previously did. Rolled back to 1.12.23 for the time being, just want to note here for posterity in case it bites anyone else. Replied on the Move Work Forwrad Atlassian Service Desk issue F1-442 as well.

**Comment by RolphH** [comment]
Indeed, I noticed as well that the latest version breaks triggering builds when merging to master. Rolled back to 2.3.15 for the time being.

**Comment by ruhrohraggy** [comment]
Is anyone here using tag builds? I believe we're on one of the older versions of the Post webhooks plugin, as the events are getting set automatically, but it's not setting the `Tag Created` option automatically even though I have tag discovery on as a trait... Still can't tell if I'm missing something or it's not implemented.

**Comment by ryanwoodsmall** [comment]
AFAIK, the "Tag Created" repository event has never been automatically enabled, even with discover tags enabled in the Jenkins multibranch pipeline build. Just setup a new test build with discover tags and the default event set is the same both with and without.

![Screenshot 2020-05-19 at 13 42 40](https://user-images.githubusercontent.com/5304551/82365780-c7a8c900-99d6-11ea-9766-9a1281e9f2ec.png)

**Comment by ruhrohraggy** [comment]
> AFAIK, the "Tag Created" repository event has never been automatically enabled, even with discover tags enabled in the Jenkins multibranch pipeline build. Just setup a new test build with discover tags and the default event set is the same both with and without.

Yup... that's what I was afraid of. And that's what I was just trying to confirm -- I've dug through the source for this plugin and it's looked like that event type isn't even implemented as an ENUM like the rest of the hook event types. But I didn't know if maybe I was missing something. Big oof. We're implementing tag builds for all of our Java libraries and UI packages..... That's a **LOT** of repo's to go through and manually update. Gonna have to figure something out.

**Comment by ryanwoodsmall** [comment]
The REST API can be used to enable events for existing hooks. cURL example is below, some info elided; the first does a `GET` of the existing hook, the second does a `POST` to the specific endpoint (the **id** from the JSON) of the hook config using an access token. You need:

- the **id** (appended to the REST URL for the specific config you want to update)
- the **title** (cannot be NULL)
- the **url** (cannot be NULL)
- the element to change (**tagCreated** here)

```
$ curl -k -L -s -X GET -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/json" http://${SITE}/rest/webhook/1.0/projects/${PROJ}/repos/${REPO}/configurations | jq .
{
  "id": 65,
  "title": "Jenkins hook",
  "url": "...",
  ...
  "tagCreated": false,
  ...
}
$ curl -k -L -s -H "Authorization: Bearer ${TOKEN}" -H "Content-Type: application/json" -X POST -d '{"title": "Jenkins hook", "url": "...", "tagCreated": "true"}' http://${SITE}/rest/webhook/1.0/projects/${PROJ}/repos/${REPO}/configurations/65 | jq .
{
  "id": 65,
  "title": "Jenkins hook",
  "url": "...",
  ...
  "tagCreated": true,
  ...
}
```

Cloudbees has some Jenkins docs with examples here: https://support.cloudbees.com/hc/en-us/articles/115000083932-Generate-webHooks-in-Bitbucket-Server-via-REST-API-for-Pipeline-Multibranch#updateawebhookbyid

**Comment by ruhrohraggy** [comment]
@ryanwoodsmall Thanks! That was actually the path I was going down. Not with cURL's but just the Jenkins built in httpRequest. I'm glad you wrote to me because I hadn't seen that the title and URL couldn't be null! I was wondering why I was getting a 405.... that could very well be why. Thanks again!

**Comment by ruhrohraggy** [comment]
@ryanwoodsmall I'm back. Again probably not the right forum of conversation but I've gotten more help here than googling lol. Anyone here know about the webhook registration happening automatically for jobs that already exist? It seems like the registration listener wouldn't be invoked if a job already exists, even if the configuration changed in a way that might change the webhook? We're moving to using the native webhook in Bitbucket so that we can automatically have tag creation events registered as an event, but I'm noticing that without deleting a job and then recreating it with our Job DSL, the webhook doesn't update or anything. If I just run our job that handles all job generation, no updates are seen in Bitbucket. Is my understanding correct for the listener or is there some way I can force the SCMSource object of each job to "update" everytime so that the webhook gets re-registered

**Comment by ryanwoodsmall** [comment]
The hooks are registered as part of job creation. AFAIK there's no auto update procedure or recreation of missing hooks, but a new hook can be created using the plugin API. Might be able to remove the SCM source and readd to get the hooks created, but that's hacky and I wouldn't count on it. The native webhooks are a different beast entirely and have their own API set, but I think coverage there is similar - regardless, you'll still have to either create them manually, via API, or delete/recreate jobs. I never had much luck with the builtin webhooks but I also haven't messed with them for a few versions of BitBucket; the MWF Post Webhooks plugin was much more reliable in the past, I'd reckon mostly due to limited surface area.

**Comment by leonkyr** [comment]
@ruhrohraggy @ryanwoodsmall This is Leo from Move Work Forward. If you have any suggestions on how we could improve the plugin in a backward compatible way please let me know.

**Comment by thirsch** [comment]
Just in case anybody else finds this issue while looking for help on the topic. In our case we had to change the bitbucket server version back to 6.x since it has been changed to 7.x per default after upgrading the plugin. Now everything works fine again. :-)

**Comment by bitwiseman** [comment]
@thirsch Yes, the server version setting is new, so we had to choose a default value. Sorry for the inconvenience, but glad it works now.

**Comment by tkhkokd** [comment]
Does your credential have Admin level access to the repository? Otherwise you cannot register hook.
