### ISSUE TITLE
Create different build status key for the same PR targeting different branches

### ISSUE THREAD

**Issue by bigpuritz** [jenkinsci/bitbucket-branch-source-plugin#298]
### Your checklist for this issue

- [x] Jenkins version
  2.240.5

- [x] Plugin version
  2.6.0

- [ ] Bitbucket cloud

- [x] Bitbucket server and version
  6.8.0
 

### Description

Hi,

in our GIT workflow, pull requests are often created based on the same feature branch for different target branches.

For example, suppose there are two pull requests, both of which are created from the same feature branch but for the different target branches:

```
Feature branch A => PR 1 => Target branch X
Feature branch A => PR 2 => Target branch Y
```

In Jenkins, this leads to the creation of one build job per pull request. So far so good.
(Note! Dependending on the target branch it may be possible, that the first job fails and the second not)

However, since both pull requests are based on the same commit ID, the respective build job always notifies both PRs. And thus overwrites the build status of the other build job. The build status can only be assigned to a commit via Bitbucket's REST API, so this behavior is understandable.

But what causes problems is the value of the "**key**" attribute in the build status sent to Bitbucket. This is always created based on the feature branch name (see `BitbucketBuildStatusNotifications.java # getBuildKey (..)`). The **key** value is the same for both PRs and hence only one build job appears in the build history of the two PRs (either the first or the second one).

It would be wonderful if you could make this behavior configurable and allow, for example, to use the name of the PR instead of the branch name as the "**key**" value.

Thanks.

**Comment by bigpuritz** [comment]
Any progress on this?

**Comment by gmshake** [comment]
The current logic use different key between different build of PRs. There was a PR https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/172 slightly changed the behavior of computing the key.

Can you confirm that the option `Exclude branches that are also filed as PRs` is not set on your job?
