### ISSUE TITLE
Atlassian account admin requires single sign-on

### ISSUE THREAD

**Issue by swerenfl** [jenkinsci/bitbucket-branch-source-plugin#301]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [x] Bitbucket cloud

- [x] Bitbucket server and version

### Description

Jenkins ver. 2.204.2
Bitbucket Plugin 2.7.0
Bitbucket Cloud

Receiving the following error:

> com.cloudbees.jenkins.plugins.bitbucket.api.BitbucketRequestException: HTTP request error. Status: 403: Forbidden.
> Because your Atlassian account admin requires single sign-on, you'll need to authenticate with an app password.

Even when setting up an app password and adding it to the credential store, it's still not connecting. Has the community experienced anything like this? Just started happening today

**Comment by jetersen** [comment]
https://confluence.atlassian.com/bitbucket/app-passwords-828781300.html

**Comment by swerenfl** [comment]
I think we solved it. This is what we posted in our Slack (removed all PII):

![image](https://user-images.githubusercontent.com/2687557/78930121-2e96a200-7a69-11ea-8e5b-f92765b0757d.png)
