### ISSUE TITLE
Feature branch is build once, but Bitbucket reports 2 links

### ISSUE THREAD

**Issue by jochenhebbrecht** [jenkinsci/bitbucket-branch-source-plugin#303]
### Your checklist for this issue

- [X] Jenkins version

- [X] Plugin version

- [ ] Bitbucket cloud

- [X] Bitbucket server and version

### Description

Please describe your issue here.

- **Jenkins version:** Jenkins ver. 2.190.3 (with BlueOcean 1.22.0)
- **Plugin version:** 2.6.0
- **Bitbucket server:** 6.7.1

The plugin works great. When I create a feature branch, the branch is automatically discovered and the build runs great.
However, when going to Bitbucket, I see that for the feature branch - well, the commit - 2 links to Jenkins are available:
![Screenshot from 2020-04-16 13-05-11](https://user-images.githubusercontent.com/2405227/79449489-973ecb00-7fe3-11ea-9ee0-f41836227a93.png)
What could be the reason that 2 links are provided in Bitbucket? The URL is exactly the same

Jochen

**Comment by patthoyts** [comment]
When we had this occur it was because we were using the `notifyBitbucket()` command in the Jenkinsfile. This extension already notifies bitbucket when it starts and completes the build so there is no need to be calling `notifyBitbucket` explicitly. It might be you are doing this as well.

**Comment by jochenhebbrecht** [comment]
Thanks, you seem to be on the right track as we indeed call the function `notifyBitbucket()` in our Jenkinsfile.
However, if we don't do this, Jenkins does not detect a newly created feature branch. 

Which (web)hook do you use in Bitbucket to connect your repository changes with the Jenkins server?
