### ISSUE TITLE
Reviewer approval is not triggering jobs

### ISSUE THREAD

**Issue by shankarinece** [jenkinsci/bitbucket-branch-source-plugin#305]
### Your checklist for this issue

- [x] Jenkins version: v2.222.1
- [x] Plugin version: 2.7.0
- [ ] Bitbucket cloud
- [x] Bitbucket server and version: Atlassian Bitbucket v6.10.0

### Description

If the Webhook is configured for "Pull Request" -> "Approved", it is expected that the Jenkins branch is built upon approval of a PR. 
When PR is approved, the Bitbucket issues a request to Jenkins, but the build is not triggered neither in the parent nor in the branch jobs.

Below image shows the Bitbucket triggered the event upon PR approval. 
![image](https://user-images.githubusercontent.com/592232/80714111-19fe7480-8b12-11ea-8287-4bac34ccc1c9.png)

Here is the event request details
![image](https://user-images.githubusercontent.com/592232/80715452-018f5980-8b14-11ea-90db-1945a5f493af.png)

**Comment by mattiassluis** [comment]
Do I understand correctly that your use case is to only trigger a Jenkins build after approval? That's the first time I encounter that as I believe most people let Jenkins verify the pull request as part of the approval process (and often again after a pull request has been merged).

I guess the plugin could support this the same way as any other status update on the pull request similar to the change done by drg2 here: https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/291/files and the one I did today on https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/309.

@jetersen I could add this event type as well to my PR as additional supported trigger with the same behaviour if you like?

**Comment by jetersen** [comment]
Seems counter intuitive to build again on approval especially as a build might find static analyze or linting issues.

**Comment by mattiassluis** [comment]
Definitely not something you want the updateHook method to configure by default but if the plugin supports the incoming event it could be manually configured.
It sure is an unusual flow where you start with a manual review before triggering Jenkins

**Comment by jetersen** [comment]
Perhaps this is what your looking for:
https://github.com/jenkinsci/bitbucket-approval-filter-plugin
