### ISSUE TITLE
Release 2.8.0

### ISSUE THREAD

**Issue by rchui** [jenkinsci/bitbucket-branch-source-plugin#307]
### Your checklist for this issue

- [ ] Jenkins version

- [ ] Plugin version

- [ ] Bitbucket cloud

- [ ] Bitbucket server and version

### Description

We would like to take advantage of the OAuth credential usage that was added in https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/262. Are there any remaining blockers to cutting a new release for 2.8.0?

**Comment by jetersen** [comment]
I was hoping more action on #287 😓

**Comment by jetersen** [comment]
https://github.com/jenkinsci/bitbucket-branch-source-plugin/releases/tag/cloudbees-bitbucket-branch-source-2.8.0
