### ISSUE TITLE
Support new Bitbucket Server 7 event type "pr:from_ref_updated"

### ISSUE THREAD

**Issue by mattiassluis** [jenkinsci/bitbucket-branch-source-plugin#308]
- [x] Jenkins version: 2.233

- [x] Plugin version: 2.8.0

- [ ] Bitbucket cloud

- [x] Bitbucket server and version: 7.2.0

### Description
Bitbucket Server 7 introduced a new PR event:
https://confluence.atlassian.com/bitbucketserver070/event-payload-996644369.html#Eventpayload-Sourcebranchupdated

This event seems to fire when people use rebasing on their pull requests. This event is fire instead of the "pr:modified" event but should be handled identically.
It is very similar to the earlier PR https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/291

**Comment by jetersen** [comment]
@mattiassluis feel free to send a PR.

**Comment by mattiassluis** [comment]
> @mattiassluis feel free to send a PR.

That was the intention, and done. We upgraded this weekend to Bitbucket Server 7 and found this issue as well as being impacted by the issue https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/287. I am no Java developer but willing to help where I can on this issue

**Comment by mattiassluis** [comment]
Issue is still relevant and open until PR is merged and releases
