### ISSUE TITLE
Differences to https://plugins.jenkins.io/atlassian-bitbucket-server-integration/

### ISSUE THREAD

**Issue by kwin** [jenkinsci/bitbucket-branch-source-plugin#310]
I am noticing that it states in https://plugins.jenkins.io/cloudbees-bitbucket-branch-source/
> This plugin is up for adoption! We are looking for new maintainers.

At the same time Atlassian seems to properly maintain https://plugins.jenkins.io/atlassian-bitbucket-server-integration/ so I am wondering what the differences between your plugin and the one from Atlassian are.

**Comment by jetersen** [comment]
Please see https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/288

**Comment by deebloo** [comment]
@kwin the official Atlassian plugin us quite new and is missing a number of features. It doesn't even properly support Pull Requests (at this moment). It also doesn't support Project folders and auto discovery. I have been keeping an eye on it as well but this plugin is still the best option
