### ISSUE TITLE
Disable build notifications

### ISSUE THREAD

**Issue by atom-x** [jenkinsci/bitbucket-branch-source-plugin#313]
### Your checklist for this issue

- [x] Jenkins version: 2.237

- [x] Plugin version: 2.8.0

- [ ] Bitbucket cloud

- [x] Bitbucket server and version: 6.8.0

### Description

We are experiencing some issues with build status notifications which are sent from plugin to bitbucket. So we are looking for possibility to disable build status notifications.

I checked the source code and found that build notification could be disabled via com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSourceContext#notificationsDisabled

But according com.cloudbees.jenkins.plugins.bitbucket.BitbucketBuildStatusNotifications#sendNotifications source context is created without specifying that field.

So is there any way to disable this notifications?

Thanks!

**Comment by jetersen** [comment]
https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/203#issuecomment-503334399
