### ISSUE TITLE
Question: how to capture all bitbucket events and send it to a custom rabbitmq queue?

### ISSUE THREAD

**Issue by guilhermecgs** [jenkinsci/bitbucket-branch-source-plugin#317]
### Your checklist for this issue

- [ ] Jenkins version

- [ ] Plugin version

- [ ] Bitbucket cloud

- [X] Bitbucket server and version

### Description

HI Folks,

I have some requirements and I need to know if this plugin can help me.

What I need is to capture all events from bitbucket and send it to a rabbitmq queue.

As far as I know, this plugin configures webhooks in each bitbucket repository ... Not sure if it uses periodic pooling either.

Whatever the inner workings are, I want to be informed when a PR is created/merged.

Can I use this plugin to do that?  If not, can you give me some directions

more info:
- I have thousands of repos and teams. I cannot add a webhook directly on bitbucket myself.

**Comment by mattiassluis** [comment]
The plugin is able to scan a "Project" in Bitbucket and register a webhook for each repository that contains a Jenkinsfile in either a branch or a pull request. The creation of the webhook only works if the Jenkins credentials have sufficient permissions on the project/repo to do so. In this setup you could detect inside your Jenkins pipeline what kind of commit you are building (is it a PR or something else) and with some self added git magic you could detect the events that you are describing. But this logic and the logic to write info to RabbitMQ must be in each Jenkinsfile I think.

I think it is technically plausible to achieve what you want but it would be much easier and give you way more control if you would simply register your own webhook and have a small broker that would handle the events and send them to RabbitMQ.
The Bitbucket API is not to overly complicated to discover projects and repositories and to create webhooks. But to create webhooks you need `REPO_ADMIN` permissions (so does Jenkins to register the webhooks) unless you are using the `Post Webhooks` plugin on Bitbucket from Topicus which only requires `REPO_WRITE`.
