### ISSUE TITLE
How to define a Proxy server

### ISSUE THREAD

**Issue by alfador1** [jenkinsci/bitbucket-branch-source-plugin#323]
Hello guys,
How to tell the plugin to go through my proxy instead of directly going to the global configuration and use it's Bitbucket endpoints

**Comment by rajand87** [comment]
Hi Guys, 
We are facing the same issue. The plugin is not considering the global proxy settings and we don,t want to reach the bitbucket server directly. Please help

**Comment by nfalco79** [comment]
the proxy configuration is taken into account both bitbucket server and cloud when create the apache http client that is used to perform REST API calls.
