### ISSUE TITLE
Need a way to poll release/* branches at a different rate than others

### ISSUE THREAD

**Issue by ykoehler** [jenkinsci/bitbucket-branch-source-plugin#333]
### Description

The plugin should offer behaviors as to throttle build for different branches based upon their name.  For example, I would like the pull request to be scanned and built if any changes made every 5 minutes, but I would like my release/* branches to be built at most 1 time per day (not every 5 minutes) - even if webhooks come in indicating a change.

At this time, each branch is polled/handled the same, and they are either build on a timer or on-hook notifications.  Which I believe is inappropriate for projects where release branches go through a long and resource-intensive CD process.

**Comment by bitwiseman** [comment]
@ykoehler 
Limiting specific branches within a multi-branch project might be possible, but it would be involved.  It isn't a scenario I've heard much call for. Most people address this by limiting the commits to their `release/*` branches - they release when a new commit appears in a `release/*` branch. 

As a workaround you could filter your `release/*` branches out of your CI job and create a separate job for the `release/*` branches with different limitations.

**Comment by bitwiseman** [comment]
@ykoehler Have youe tried setting a "Branch Property Strategy"?

**Comment by ykoehler** [comment]
I went ahead with the Branch Property Strategy, but it doesn't work correctly when using Lockable resources as well, submitted an enhancement request to the Lockable plugin to implement the same behavior.
