### ISSUE TITLE
Single file retrieval from PR uses outdated Bitbucket API

### ISSUE THREAD

**Issue by henrikb123** [jenkinsci/bitbucket-branch-source-plugin#336]
### Your checklist for this issue

- [x ] Jenkins version

- [ x] Plugin version

- [ ] Bitbucket cloud

- [ x] Bitbucket server and version

### Description

Jenkins version: 2.235.3
Plugin version: 2.9.1
Bitbucket server and version: 7.4.0

When the plugin needs to retrieve a single file from a pull-request in Bitbucket server it uses the at=pull-request reference which doesn't seem to be supported post Bitbucket 7+.

Example snippet that triggers this behaviour

```
pipeline {

    agent {
        kubernetes {
            customWorkspace 'myworkspace'
            label 'mylabel'
            yamlFile 'Jenkinsfile.yml'
            defaultContainer 'java'
        }
    }

    stages {
        stage("Build") {
            steps {
	      sh "echo 'hello'"
            }
        }
    }
}
```
(line 7 with yamlFile being the culprit)

Stacktrace:
```
java.io.FileNotFoundException: URL: /rest/api/1.0/projects/test/repos/my-repro/browse/Jenkinsfile.yml?at=pull-requests%2F14%2Fmerge&start=0&limit=500
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:854)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getFileContent(BitbucketServerAPIClient.java:1149)
	at com.cloudbees.jenkins.plugins.bitbucket.filesystem.BitbucketSCMFile.content(BitbucketSCMFile.java:98)
	at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:335)
```

This is related to issue #294 where a similar issue was fixed, but this feels like a case that was left behind.

**Comment by bitwiseman** [comment]
Yes, 7.x has different behavior. 

See https://issues.jenkins-ci.org/browse/JENKINS-61493

**Comment by bitwiseman** [comment]
@henrikb123 

Kalle Niemitalo
Kevin Huber

The linked comment below indicates that in BitBucket 7 Atlassian has removed the ability to do lightweight checkout while using the "Merging" strategy. This is intentional, by-design behavior implemented by Atlassian. It is beyond the control of Jenkins project to fix this.

As a workaround, please try changing to use the "Current Pull Request revision" strategy instead and see if that works. 

https://jira.atlassian.com/browse/BSERV-12284?focusedCommentId=2389584&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2389584

> refs/pull-requests/*/merge has been fully removed in 7.0 and will never be created/updated by the system again. For pull requests that were opened prior to upgrading to 7.x, which have a merge ref, that ref will be removed the first time the pull request is updated (or when it's merged or declined, as ever). With the switch from 3-way diffs (which were built around displaying the merge's diff) to 2-way diffs (which use the common ancestor), the system no longer retains the merges it creates to check mergeability; it runs git merge to see what happens, and discards everything that results. This prevents the accumulation of "unreachable" pull request merge objects in repositories, which can (greatly) slow down clone/fetch/pull/push performance as they build up. Any tool that wishes to build a pull request's merge will need to create that merge on its own, going forward.
>
>Prior to 7.0, because pull request diffs were built around the merge, checking mergeability (which happens automatically after page load when a pull request is created via the UI) would create the public refs/pull-requests entries for that pull request. In 7.x, since the diff is now using the common ancestor and no longer needs the merge, checking mergeability doesn't create any refs. (This is shown in the log snippets above.) Instead, the refs are created when a pull request's diff is viewed. Plugins which are installed in Bitbucket Server can simulate this by either using the PullRequestService to stream the pull request's changes, or (more efficiently), by using ScmService.getPullRequestCommandFactory(pullRequest).effectiveDiff() (which PullRequestService uses under the hood). Remote callers can use rest/api/1.0/projects/KEY/repos/slug/pull-requests/N/changes?limit=1 to do the same. Any of those will ensure refs/pull-requests/*/from is created (or updated) to match the pull request's current state.
>
>I'd wager many webhook apps (or other apps that notify external systems, however they do so) have logic in them for using PullRequestService.canMerge, MergeRequestCheckService.check or ScmPullRequestCommandFactory.tryMerge to try and force pull request refs to be created/updated. (The Post Webhooks for Bitbucket app did, back when it was open source; the source has since been made private, or at least moved off Github, so I'm not sure these days.) Those approaches will not work in 7.x. Instead, such apps need to be updated to use PullRequestService.streamChanges or ScmPullRequestCommandFactory.effectiveDiff to force the from ref to be created/updated. As noted earlier, there is no way in 7.x to get a merge ref.
>
>I'll reiterate here that Bitbucket Server's pull request refs are not API, and have never been considered API, so the way they work is dangerous to rely on. I'll also readily acknowledge that that's hardly a satisfactory answer, to receive or to give, and that it would be nice if it changed. I am not a PM for Bitbucket Server, so I can't say when/if such improvements will hit the roadmap. Perhaps I'll see if I can use some upcoming 20% time to make some improvements. I'm sorry that, at least for the moment, I can't offer better.
>
>Best regards,
>Bryan Turner
>Atlassian Bitbucket

**Comment by bitwiseman** [comment]
@henrikb123 

I may have been wrong about this.  As a workaround, please try enabling "Call changes API" for your Bitbucket 7 endpoints.  

Keep in mind that this will make an additional API call for each PR.  In extreme cases, this may cause you to exceed your account's rate limit when you didn't previously.

**Comment by dwnusbaum** [comment]
FWIW, I have seen another report from a user who states that "Call changes API" does not help. From what I can see, the `yamlFile` feature in the Kubernetes plugin [calls](https://github.com/jenkinsci/kubernetes-plugin/blob/75b788a917bb2f06a99a9719ada5e9a80f29c513/src/main/resources/org/csanchez/jenkins/plugins/kubernetes/pipeline/KubernetesDeclarativeAgentScript.groovy#L38-L40) calls the [`readTrusted`](https://github.com/jenkinsci/workflow-multibranch-plugin/blob/91fd65daeb7c6ba7cf51518380304041699602ca/src/main/java/org/jenkinsci/plugins/workflow/multibranch/ReadTrustedStep.java) step defined in `workflow-multibranch`, which is supposed to be able to fall back to a heavyweight checkout, so I'm not totally sure what might be going wrong.

**Comment by xabolcs** [comment]
@bitwiseman enabling "Call changes API" doesn't help for my Bitbucket Server 7 endpoint.
But manually changing `merge` to `from` in the URL (`/rest/api/1.0/projects/test/repos/my-repro/browse/Jenkinsfile.yml?at=pull-requests%2F14%2Ffrom&start=0&limit=500`) helps.

Sure, enabling "Call changes API" helps for other areas in the Jenkins - Bitbucket Server integration, but not for lightweight checkout.

But the problem is the same - `git ls-remote` shows there is no more `merge` for newer PRs:
```
c5fe5646515e58eb67958cbb181ad301649fea97	refs/pull-requests/1422/from
69df8d813c2d96d0adee7103793d9b82951886fd	refs/pull-requests/1422/merge
c5fe5646515e58eb67958cbb181ad301649fea97	refs/pull-requests/1423/from
ad4b79b5f0809a802902df865a46e378fa04f0a4	refs/pull-requests/1423/merge
cf34c974f84a8e82886de42c82be97671e5777a5	refs/pull-requests/1685/from
d8d5f5fed6bf59a6cf406ad07b31fdb187f4b340	refs/pull-requests/2529/from
39613491f3aa82e6b2d15f7e3ffce5d57fc49fb6	refs/pull-requests/2781/from
05d9a108d265886b0737cd5b9815cea43828978f	refs/pull-requests/2802/from
9e70491d7b649c5aedd921b8aecbca50c82872ba	refs/pull-requests/2803/from
f791077eed5b19c03a7567023480467a88f2ec6e	refs/pull-requests/2804/from
````

**Comment by bitwiseman** [comment]
@xabolcs 
Changing to `/from` in the URL is basically what `ChangeRequestCheckoutStrategy.HEAD` does.

**Comment by xabolcs** [comment]
Yup, I see.

It just doesn't look good that is selectable if the Bitbucket Server version is set to 7+. Or at least no mention about being useless for 7+ servers in the help text.

**Comment by hamzah-efi** [comment]
I can confirm that using the "The current pull request revision" choice seemed to resolve the lightweight checkout failure that I had as well. I have the Call API checkbox marked on the System page as well.

**Comment by bitwiseman** [comment]
@xabolcs 
We'd welcome a PR that improves matters.
