### ISSUE TITLE
Update scribe to scribejava

### ISSUE THREAD

**Issue by bitwiseman** [jenkinsci/bitbucket-branch-source-plugin#345]
Scribe is insanely out of date.  It is was moved to a new package name 6 years ago.   The latest version is **7.0.0** . 
https://github.com/scribejava/scribejava

See #342.

**Comment by sfat** [comment]
@bitwiseman , do you mind if I take a stab at this?

**Comment by bitwiseman** [comment]
@sfat  
Please do!
