### ISSUE TITLE
Meaningful name for PRs job name (in multibranch pipeline)

### ISSUE THREAD

**Issue by borisovano** [jenkinsci/bitbucket-branch-source-plugin#354]
- [x] Jenkins version
Jenkins 2.235.1

### Description

Currently in PR job name in Multibranch pipeline is "Pull Request PR-XXX" (e.g Pull Request PR-507)

IMHO it would be beneficial to add an option to get the name from PR subject or even append the source branch name such as: Pull Request PR-507-my-special-branch

**Comment by bitwiseman** [comment]
The id would still need to match the `PR-XXX` model, but adding the subject to the display name after the `PR-XXX` would be nice.

**Comment by PayBas** [comment]
@bitwiseman would you care to review https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/389 ?
It should resolve this issue/request.

**Comment by KalleOlaviNiemitalo** [comment]
The descriptions actually show up in tooltips of the PR-XXXX links in the list. But it's pretty silly that they appear nowhere on the branches/PR-XXXX page itself.

**Comment by Semmu** [comment]
Would love to see this implemented.

**Comment by iadonkey** [comment]
+1 :-)

**Comment by theycallmeninx** [comment]
Our team would also really love to have this PR merged in. Please include this as soon as possible.

**Comment by Ozz007** [comment]
+1

**Comment by rearl** [comment]
Our team would also really love to have this change.
+1

**Comment by slwon** [comment]
+1

**Comment by samrocketman** [comment]
WRT long titles; does it make sense to cut off the title after a certain number of characters e.g. `PR-XXX My super long...` shows there's more to the title but cutting it off for the UI consistency.

**Comment by nfalco79** [comment]
Close since implemented in the the branch api plugin

**Comment by iadonkey** [comment]
Thanks a lot!
