### ISSUE TITLE
Configurable Build Status Notification

### ISSUE THREAD

**Issue by ssc327** [jenkinsci/bitbucket-branch-source-plugin#360]
https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/508aa84e5e951b1494a74deb4eb86a59700cd5e7/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java

Currently the mapping of Jenkins build result to BitBucket build status is fixed/static.

```
        if (Result.SUCCESS.equals(result)) {
            statusDescription = StringUtils.defaultIfBlank(buildDescription, "This commit looks good.");
            state = "SUCCESSFUL";
        } else if (Result.UNSTABLE.equals(result)) {
            statusDescription = StringUtils.defaultIfBlank(buildDescription, "This commit has test failures.");
            state = "FAILED";
        } else if (Result.FAILURE.equals(result)) {
            statusDescription = StringUtils.defaultIfBlank(buildDescription, "There was a failure building this commit.");
            state = "FAILED";
        } else if (Result.NOT_BUILT.equals(result)) {
            // Bitbucket Cloud and Server support different build states.
            state = (bitbucket instanceof BitbucketCloudApiClient) ? "STOPPED" : "SUCCESSFUL";
            statusDescription = StringUtils.defaultIfBlank(buildDescription, "This commit was not built (probably the build was skipped)");
        } else if (result != null) { // ABORTED etc.
            statusDescription = StringUtils.defaultIfBlank(buildDescription, "Something is wrong with the build of this commit.");
            state = "FAILED";
        } else {
            statusDescription = StringUtils.defaultIfBlank(buildDescription, "The build is in progress...");
            state = "INPROGRESS";
        }
```

While this is great in most cases, we use build result as **merge check** on PRs and for our usage **Unstable** job should allow a merge.

Has it ever been discussed to make the mapping of **Unstable** to **SUCCESSFUL** or **FAIL** configurable? 

I see that https://github.com/jenkinsci/stashnotifier-plugin has this capability but I do not want to use a separate plugin just for notification.

**Comment by kimlin** [comment]
This would be a great christmas present!

**Comment by vassik** [comment]
indeed!:-)

**Comment by konradczajka** [comment]
I'd love to be able to control not only that but also the generated build key. I have a use case where a pipeline triggers itself with different parameters. Currently it leads to Bitbucket showing only one build which status changes as follows: inprogress->successful->inprogress->successful. It would be great to see two builds with dedicated names/descriptions.

**Comment by ssc327** [comment]
Functionality added
