### ISSUE TITLE
Scan Organization Folder stops on first exception

### ISSUE THREAD

**Issue by tomk3003** [jenkinsci/bitbucket-branch-source-plugin#369]
- [x] Jenkins version

- [x] Plugin version

- [ ] Bitbucket cloud

- [x] Bitbucket server and version

### Description

When the organization folder scan encounters an error while talking to the Bitbucket server (in our case a corrupted repository where the branch lookup failed) the scan stops and will never get over that error until it is fixed on the server side. I think the exceptions should be caught and reported but scanning should continue for the rest of the repositories. Perhaps an error limit could help stopping the scan if the number of exceptions exceed the limit.

Jenkins version : 2.222.1
Plugin version: 2.9.0
Bitbucket Server 7.1.2

**Comment by bitwiseman** [comment]
github-branch-source-plugin made a relatively recent change to address this same issue: 

https://github.com/jenkinsci/github-branch-source-plugin/blob/238fcdd9544ef8f5b859ad3e6d5ebf228349ef83/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMSource.java#L1033-L1045

Something similar should be done in this plugin.

**Comment by nfalco79** [comment]
Is this issue still present in latest version?
