### ISSUE TITLE
Links from Changes page not always linking against bitbucket

### ISSUE THREAD

**Issue by benbrummer** [jenkinsci/bitbucket-branch-source-plugin#378]
- [x] Jenkins version

- [x] Plugin version

- [ ] Bitbucket cloud

- [x] Bitbucket server and version

### Description
Jenkins 2.249.1
Plugin 2.9.4
Bitbucket Server 7.3.1

Links from https://jenkins.url/job/xyz/job/development/changes
are not always pointing to "bitbucketweb"

![image](https://user-images.githubusercontent.com/24470839/94271962-aaff3d80-ff42-11ea-841e-ad34d4654920.png)

**Comment by nfalco79** [comment]
Is this issue yet present in latest plugin version?
