### ISSUE TITLE
DisableConcurrentBuilds feature

### ISSUE THREAD

**Issue by racodond** [jenkinsci/bitbucket-branch-source-plugin#381]
### Your checklist for this issue

- [x] Jenkins version 2.249.1

- [x] Plugin version 2.9.0

- [ ] Bitbucket cloud

- [x] Bitbucket server and version 7.5

### Description

I can't find a way to set disableConcurrentBuilds() at multibranch pipeline job level (either through the web interface or through job DSL). The only way I found so far is to set it in my JenkinsFile inside properties().

But I want to set all the properties at job level. I managed to set rateLimit, parameters, etc. I cannot leave one property in my Jenkinsfile, otherwise properties defined at job level will be overridden with default values when a build is run on a branch.

Do you confirm that it is not possible? If not, any pointer to help me implement this feature and provide a PR.

Thanks!

**Comment by racodond** [comment]
You can ignore my issue. I found out the right way to do what I wanted to achieve.

**Comment by c4m4** [comment]
@racodond please, provide the solution, not only the problem

**Comment by racodond** [comment]
I set the property in Jenkinsfile.

**Comment by c4m4** [comment]
@racodond Thanks :)
