### ISSUE TITLE
Authorization should be reused in organization scan

### ISSUE THREAD

**Issue by tomk3003** [jenkinsci/bitbucket-branch-source-plugin#383]
* [x]  Jenkins version
* [x]  Plugin version
* [ ]  Bitbucket cloud
* [x]  Bitbucket server and version

### Description
We have a large organization folder with 350 repositories and a scan takes about 30 minutes. Scanning the log I see that for each repository the connection to Bitbucket is newly created. Wouldn't using an existing connection for all repos speed things up significantly? Or is it possible to parallize the scan?

Jenkins version : 2.222.1
Plugin version: 2.9.0
Bitbucket Server 7.1.2

**Comment by gmshake** [comment]
30minutes / 350 repositories is about 5 second / repository, I'm not 100% sure but it seems to be related to the system property `org.jenkinsci.plugins.github_branch_source.GitHubSCMSource.eventDelaySeconds` which value is default of 5 (seconds).

Can you please set the system property to a smaller value and try again?

**Comment by mdealer** [comment]
We have a very similar issue. Though, you can't really parallelize here, as Bitbucket will throttle the requests done by a single user anyway.

Could it be that the connections are also not reused for branches? We have a 300 repos x 50 branches situation.

**Comment by lifeofguenter** [comment]
This is quite setup dependent. Anything that involves scanning a large number of repos will not scale - so or so. Either it is Jenkins or it is Bitbucket that will give in.

I would rather look at an approach similar to the github-branch-source plugin, where events are being sent on repository creation. Outside of that scanning is not really useful as anything else should be catchable via an event.

**Comment by KalleOlaviNiemitalo** [comment]
Bitbucket Data Center and Server do not natively support webhooks on repository creation, as webhooks must be defined per repository and cannot be defined per project. [Manage webhooks](https://confluence.atlassian.com/bitbucketserver/manage-webhooks-938025878.html)

A plugin for Bitbucket Data Center and Server could perhaps provide a repository creation webhook but I don't know whether such a plugin exists already.

**Comment by tomk3003** [comment]
Just for the record: I checked the runtime today (after the admins updated the plugin) and the scan of 410 repositories took only 2 min 11 sec. Whoever was responsible for this: Thank you very much!
