### ISSUE TITLE
Pull Request target branch

### ISSUE THREAD

**Issue by y-luis** [jenkinsci/bitbucket-branch-source-plugin#391]
### Your checklist for this issue

- [x] Jenkins version: 2.235.5

- [x] Plugin version: 2.9.1

- [ ] Bitbucket cloud

- [x] Bitbucket server and version: v6.10.0

### Description

We recently adopted Bitbucket Branch Source Plugin, and we noticed it creates a special setting in a multibranch project for Pull Requests (independent tab), and it seems it sets the environment variable `BRANCH_NAME` to `PR-x` where `x` is the PR identifier. **Does the plugin keeps the original branch name and also the target branch in any environment variable?** We need that information to be used at a Sonarquebe analysis stage where both parameters are needed to set sonar scanner properties `sonar.pullrequest.branch` (the name of the branch that contains the changes to be merged) and `sonar.pullrequest.base` (the branch into which the Pull Request will be merged.).

**Comment by timothydowney** [comment]
You should be able to use `CHANGE_TARGET` and `CHANGE_BRANCH`.  Here's a snippet of how we handle properties in PRs.

This snippet is in the context of one of our pipeline functions, but you'll get the idea.

```
            if (context.env.CHANGE_ID) {
                sonarProps['sonar.pullrequest.key'] = context.env.CHANGE_ID
                sonarProps['sonar.pullrequest.branch'] = context.env.CHANGE_BRANCH
                sonarProps['sonar.pullrequest.base'] = context.env.CHANGE_TARGET
                sonarProps['sonar.pullrequest.target'] = context.env.CHANGE_TARGET
                sonarProps['sonarqube.pullrequest.bitbucket.projectKey'] = config.bitbucketProject
                sonarProps['sonarqube.pullrequest.bitbucket.repositorySlug'] = config.bitbucketRepo
            } else {
                // only specific the branch if we're NOT a PR
                sonarProps['sonar.branch.name'] = context.env.BRANCH_NAME
            }
```
