### ISSUE TITLE
Unable to save configuration changes for BitBucket

### ISSUE THREAD

**Issue by PatrikSchalin** [jenkinsci/bitbucket-branch-source-plugin#397]
### Unable to save Job config changes after upgrading to Jenkins 2.264.

Jenkins version: 2.264
Branch Src Plugin: 2.9.4

Nothing happens when I press "Apply" or "Save" after a configuration change. There's no stacktraces in the Jenkins log and no error messages in the UI. 

I do get the following JS errors when accessing the configuration page for a Job;
![image](https://user-images.githubusercontent.com/1298644/97967774-f9afbb00-1dbd-11eb-84bc-9b1a887f5a88.png)

**Comment by bitwiseman** [comment]
@PatrikSchalin 
Is this the same as JENKINS-64183?

**Comment by jansohn** [comment]
Sounds like a tables-to-div problem when it started with 2.264. Question is if it's this plugin or another one which causes the issue I guess...

**Comment by PatrikSchalin** [comment]
@bitwiseman Sorry for the delay! No, this is a separate issue and probably something that is caused by the tables-to-div change as @jansohn says.

**Comment by lifeofguenter** [comment]
Closing, details in the linked issue: https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/397#issuecomment-729927743 - thanks @jansohn
