### ISSUE TITLE
Error pulling merged code from a pull request

### ISSUE THREAD

**Issue by rmorasse415** [jenkinsci/bitbucket-branch-source-plugin#402]
### Your checklist for this issue

- [ X  ] Jenkins version

- [ X ] Plugin version

- [ X ] Bitbucket cloud

- [ X ] Bitbucket server and version

### Description

Jenkins Version: 2.222.1
Plugin Version: 2.9.4
Cloud Version: N/A
bitbucket server version: 7.6.0

When pulling the merged code for a PR in a multibranch pipeline project, Jenkins tries to access the API:
`/rest/api/1.0/projects/<project-key>/repos/<repo-name>/browse/Jenkinsfile?at=pull-requests%2F<PR-#>%2Fmerge`

the ref `pull-requests/<PR-#>/merge` no longer exists and according to this help article it is not and never was part of the public API:
https://community.atlassian.com/t5/Bitbucket-questions/Difference-of-refs-pull-requests-lt-ID-gt-merge-and-refs-pull/qaq-p/772142

**Comment by bitwiseman** [comment]
See #336 and https://issues.jenkins.io/browse/JENKINS-61493 for work around.

**Comment by bitwiseman** [comment]
Re-opening this as #336 did not fully cover this issue.

**Comment by bitwiseman** [comment]
@orgi said in #417 

> Currently - as mentioned by lot of other issues - the lightweight checkout feature for the Jenkinsfile when testing the merge commit (by setting the pull request discovery options to the 'Merging ...' option) is not possible with Bitbucket 7.x - as it relies on checking out the Jenkinsfile from the merge result (by using `pull-requests/*/merge`), which no longer is provided by Bitbucket.
> 
> However imho it is not required to check out the Jenkinsfile from the outcome of the merge. The plugin may just take the Jenkinsfile from the source branch of the PR (`pull-requests/*/from`), as:
> 
> * If the Jenkinsfile of the source branch and the merge would be identical, it obviously does not make a difference
> * If the Jenkinsfile would _not_ be the same, we anyway would get a merge conflict, not allowing to run the build anyways. Afaik it should be possible to detect this by the 'Call can merge' option.
> 
> If - for whatever reason - so. needs to take the Jenkinsfile from the merge, I could think about an option to explicitly not do the lightweight checkout. However I don't think that this would be required as of the explanation given before.
> 
> Or am I missing something here?

No, sorry.  A file can change without reporting a merge conflict.  

As a side note, you (or anyone) are welcome to try to implement a solution to mitigate this issue, but my experience working on this for the github-branch-source-plugin tells me that it will be difficult to accurately handle all the scenarios.  This proposed solution is perfect example of this.

**Comment by nfalco79** [comment]
Duplicates [JENKINS-61493](https://issues.jenkins.io/browse/JENKINS-61493)
