### ISSUE TITLE
'Advanced' button is missing

### ISSUE THREAD

**Issue by FaraSeer** [jenkinsci/bitbucket-branch-source-plugin#406]
### Your checklist for this issue

- [x] Jenkins version
Jenkins 2.249.2 (I also tried on the current LTS version, 2.249.3)
- [x] Plugin version
2.9.4
- [x] Bitbucket cloud
No
- [x] Bitbucket server and version
Yes, v7.7.1 (but it doesn't matter for this issue, as I suppose

### Description

Hello.

I am trying to set up a multibranch pipeline for my project.
I use a corporate bitbucket server, so I need to specify its URL in the 'Advanced' section, according to [this](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/docs/USER_GUIDE.adoc) instruction, but I cannot find it (button disappeared after one of the recent updates of Jenkins). 
What I see now:
![image](https://user-images.githubusercontent.com/8999527/99828178-ab473e00-2b6b-11eb-8784-7025adc0e5e6.png)

Here is the suspicious message from my google chrome console log, maybe it will help:

`19:46:47.519 hudson-behavior.js:505 Couldn't find the expected parent element (.setting-main) for element <select checkdependson fillurl=​"/​job/​linux-test/​descriptorByName/​com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource/​fillServerUrlItems" checkurl=​"/​job/​linux-test/​descriptorByName/​com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource/​checkServerUrl" name=​"_.serverUrl" class=​"setting-input validated select " value=​"https:​/​/​bitbucket.org">​…​</select>​
registerValidator @ hudson-behavior.js:505
(anonymous) @ behavior.js:116
(anonymous) @ behavior.js:111
applySubtree @ behavior.js:93
apply @ behavior.js:76
(anonymous) @ behavior.js:71
window.onload @ behavior.js:133
window.onload @ behavior.js:133
load (async)
addLoadEvent @ behavior.js:132
createSearchBox @ hudson-behavior.js:2530
(anonymous) @ configure:18`

I also tried it in the other browsers.

**Comment by lifeofguenter** [comment]
I think those docs are outdated and could need some love :)

You can setup custom bitbucket-server endpoints on your `/configure` page, and then select them in your project later.
