### ISSUE TITLE
Shallow clone in pull requests do not work 

### ISSUE THREAD

**Issue by WorldVM** [jenkinsci/bitbucket-branch-source-plugin#411]
- Jenkins Version : 2.204.1

- Bitbucket Branch Source Plugin V: 2.6.0

- Bitbucket Server Version : 6.10.2

### Description
Hello everyone, I have found a strange bug in the Branch Source plugin. Unfortunately I do not know how to solve it.

Basically we have a lot of pull requests that take a very long time. If I now activate Shallow Clone in the project configuration for pull requests, no Shallow clone will be executed - see Log :

```
Using shallow clone with depth 1
Avoid fetching tags
Cloning repository https://mybitbucketserver/scm/software/software.git
 > git init E:\Jenkins\ws\PR-2124 # timeout=10
Fetching upstream changes from https://mybitbucketserver/scm/software/software.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --no-tags --force --progress -- https://mybitbucketserver/scm/software/software.git +refs/heads/*:refs/remotes/origin/* # timeout=10
Using shallow fetch with depth 1
```

But there is no Depth 1 set for PRs, if I look at the same for branches a depth 1 is set - see log for branches:

```
Using shallow fetch with depth 1
 > git rev-parse --is-inside-work-tree # timeout=10
 > git config remote.origin.url https://mybitbucketserver/scm/software/software.git # timeout=10
Fetching upstream changes from https://mybitbucketserver/scm/software/software.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --no-tags --force --progress --depth=1 -- https://mybitbucketserver/scm/software/software.git +refs/heads/master:refs/remotes/origin/master # timeout=10
```

Why is the shallow clone not performed for PRs although I have set the hack ?

Picture for Configuration for PR
![grafik](https://user-images.githubusercontent.com/61978720/100350018-8e868c80-2fe9-11eb-8c57-1d4cd1507620.png)

Picture for Configuration for Branch 
![grafik](https://user-images.githubusercontent.com/61978720/100349879-5f701b00-2fe9-11eb-9725-667616150b65.png)

**Comment by bitwiseman** [comment]
@WorldVM 
Have you tried this with `Discover pull requests from origin` set to use the non-merge strategy? It possible that shallow cloning is turned off on purpose for pull requests due to merging strategy.
