### ISSUE TITLE
Invalid error message about Unregistered Server

### ISSUE THREAD

**Issue by kellyellery** [jenkinsci/bitbucket-branch-source-plugin#416]
Jenkins version
Jenkins 2.249.3

Plugin version
Bitbucket Branch Source Plugin 2.9.5

Bitbucket cloud
N/A

Bitbucket server and version
Atlassian Bitbucket v6.10.7

### Description

Invalid error message about "Unregistered Server" when creating a new multi-branch pipeline project. See attached image. This message disappears once you save the configuration an reopen it so it doesn't seem to really be an issue.

Judging by the empty server name it seems likely that an empty string is passed to the function "doCheckServerUrl"

Code reference:
https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/59b1ea763851ac6dce1e753b36064a1578d3ba8f/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java#L1170

![unregistered_server_redact](https://user-images.githubusercontent.com/75996109/102100409-afdcda80-3e29-11eb-8bc0-7e6980215440.jpg)

**Comment by Rokko11** [comment]
I have the same issue. Indeed, the parameter "value" in  the webservice request is blank:

```
Request URL: http://<jenkins-host>/job/<job>/descriptorByName/com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource/checkServerUrl?value=
```

Good news are, that it still works when you ignore the warning. Just fill out the owner and the repository name by your own.

**Comment by AlexanderStohr** [comment]
found it to happen on 2.289.1
with this possible side effects:
* reported server in the web GUI is always bitbucket.org (i am sure i dont want my credentials go to a public server)
* saving/applying a new config always takes forever (it never works for me)

**Comment by AlexanderStohr** [comment]
> found it to happen on 2.289.1 with this possible side effects:
> 
> * reported server in the web GUI is always bitbucket.org (i am sure i dont want my credentials go to a public server)
> * saving/applying a new config always takes forever (it never works for me)
> 
> Sorry to say, but in this state the system is not manageable for me any more in a quick and simple fashion.

Looked a bit more into it - seemingly the server registration was needed to make the error message vanish.
But the instead reported server name was misleading - bitbucket.org was reported when something else was set up. :-(

**Comment by sentimenti-it** [comment]
@AlexanderStohr @kellyellery @Rokko11 Have you found any workaround?
 I'm not able to use Job DSL at all because of this bug - after each job generation I would have to go throughout all jobs and manually fix it.

**Comment by bartoliniii** [comment]
@AlexanderStohr @kellyellery @Rokko11 Have you found any workaround?
I'm not able to use Job DSL at all because of this bug - after each job generation, I would have to go throughout all jobs and manually fix it.

**Comment by lifeofguenter** [comment]
@bartoliniii can you please post your config?

**Comment by bartoliniii** [comment]
@lifeofguenter 
What exactly do you need?

Here you can find my Job DSL code:
`
createJenkinsProject( 'example-displayed-name','example-repo-name')

def createJenkinsProject(name, repositoryName) {
    multibranchPipelineJob(name) {
        branchSources {
            branchSource {
                source {
                    bitbucket {
                        credentialsId('ci.user_password')
                        repoOwner('XXX')
                        repository(repositoryName)
                        traits {
                            bitbucketBranchDiscovery {
                                strategyId(1)
                            }
                            bitbucketPullRequestDiscovery {
                                strategyId(1)
                            }
                        }
                    }
                }
            }
        }
    }
}
`

**Comment by lifeofguenter** [comment]
What happens if you add `serverUrl` in your dsl to the same value as the `serverUrl` in your casc?

![Screenshot 2021-12-13 232341](https://user-images.githubusercontent.com/241073/145898576-e6449b74-f48a-4cf2-ad00-f9d8bc458e0c.png)

**Comment by bartoliniii** [comment]
> What happens if you add `serverUrl` in your dsl to the same value as the `serverUrl` in your casc?

When I manually set URL by bitbucketServerUrl and serverUrl it works!
I think it is 'good enough' workaround for me. Big thanks @lifeofguenter!

**Comment by lifeofguenter** [comment]
Sweet closing this ticket for now then. I have seen the same behavior with github-branch-source-plugin as well, so I am guessing it might be due how branch-source-plugins need to work generally.

**Comment by AlexanderStohr** [comment]
> the server registration was needed

as already stated: "the server registration was needed"
