### ISSUE TITLE
Full support for lightweight checkouts

### ISSUE THREAD

**Issue by orgi** [jenkinsci/bitbucket-branch-source-plugin#417]
### Versions

- [2.249.3] Jenkins version

- [2.9.4] Plugin version

- [7.6.1] Bitbucket server and version

### Description

Currently - as mentioned by lot of other issues - the lightweight checkout feature for the Jenkinsfile when testing the merge commit (by setting the pull request discovery options to the 'Merging ...' option) is not possible with Bitbucket 7.x - as it relies on checking out the Jenkinsfile from the merge result (by using `pull-requests/*/merge`), which no longer is provided by Bitbucket.

However imho it is not required to check out the Jenkinsfile from the outcome of the merge. The plugin may just take the Jenkinsfile from the source branch of the PR (`pull-requests/*/from`), as:
* If the Jenkinsfile of the source branch and the merge would be identical, it obviously does not make a difference
* If the Jenkinsfile would _not_ be the same, we anyway would get a merge conflict, not allowing to run the build anyways. Afaik it should be possible to detect this by the 'Call can merge' option.

If - for whatever reason - so. needs to take the Jenkinsfile from the merge, I could think about an option to explicitly not do the lightweight checkout. However I don't think that this would be required as of the explanation given before.

Or am I missing something here?

**Comment by bitwiseman** [comment]
@orgi 
I'm going to close this in favor of #402 (https://issues.jenkins.io/browse/JENKINS-61493) as this describes a proposed solution to that issue.
