### ISSUE TITLE
Pull Request Building Behaviour

### ISSUE THREAD

**Issue by one-random-dev** [jenkinsci/bitbucket-branch-source-plugin#421]
### Your checklist for this issue

- [x] Jenkins version - 2.263.1

- [x] Plugin version - 2.9.5

- [x] Bitbucket cloud - yes

- [x] Bitbucket server and version - cloud subscription

### Description

We are Using Multibranch Pipelines configured with this plugin.
Multibranch pipeline config (relevant part):
"Discover pull requests from origin" Enabled with strategy "Merging the pull request with the current target branch revision"
"Filter by name with regular expression" behavior enabled with the value "master"

Result:
all updates on master branch are received via webhook and trigger a build
no PRs get discovered and built

Expected:
all updates on master branch are received via webhook and trigger a build
all PRs with target branch master are received via webhook and trigger a build

Steps attempted:
From some older posts regarding similar issues, there are suggestions ou there to include "PR-.*" on the value of "Filter by name with regular expression" behavior; although this triggers PR builds, all PRs trigger a build with no relation to target branch of the PR

Desired Functionality:
Build on every update on master and every PR that has master as a target branch 
Is this possible within the configuration of this plugin, using bitbucket web?

Additional INFO:
webhook setup:
![image](https://user-images.githubusercontent.com/49782782/103921180-180d9c00-510a-11eb-9a73-5e1be44b51cd.png)

**Comment by bitwiseman** [comment]
There is no behavior currently built into this plugin to filter which PRs are built based on their source branch.

**Comment by stefangr** [comment]
The [SCM Filter Branch PR](https://plugins.jenkins.io/scm-filter-branch-pr/) plugin is exactly what you need.

It works nice in combination with the bitbucket branch source plugin as well.

**Comment by one-random-dev** [comment]
Thanks for the reply will test it out!

**Comment by alexey-boyko** [comment]
I'm experiencing same behaviour( @one-random-dev did you manage to make it work?

**Comment by OElabed** [comment]
Hi @stefangr ,
Thank you to propose another tool. So I have installed the plugin but it seems that does not work for my configuration. (May be my configuration is wrong).

So my uses case is that I need to filter origin branchs of PR (only **feature/app1/***) for the multibranch job. I do the following configuration with dsl job:

```
multibranchPipelineJob('APP1_PR_MULTI') {

    branchSources {
      configure { node ->
        node / sources(class: 'jenkins.branch.MultiBranchProject$BranchSourceList') / data / 'jenkins.branch.BranchSource' / source(class: 'com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource') {
          id(UUID.randomUUID().toString())
          serverUrl('http://<bitbucket-server>')
          credentialsId('13713251-320b-498f-bc31-231e0ea6a36b')
          repoOwner('~oelabed')
          repository('project-pr-test')
          traits {
              'com.cloudbees.jenkins.plugins.bitbucket.OriginPullRequestDiscoveryTrait'{
                strategyId(1)
              }
              'net.gleske.scmfilter.impl.trait.WildcardSCMOriginFilterTrait'{
                includes("feature/app1/*")
              }
              'com.cloudbees.jenkins.plugins.bitbucket.SSHCheckoutTrait'{
                credentialsId('ab4f376a-2bc3-4623-95aa-6b949b3b6d9d')
              }
          }
        }
      }
  }
  configure {
    it / factory(class: "org.jenkinsci.plugins.workflow.multibranch.WorkflowBranchProjectFactory") << {
        scriptPath("app1/ci/jenkinsfile.pr")
    }
  }

  orphanedItemStrategy {
      discardOldItems {
          numToKeep(10)
      }
  }
}
```


The result is that the PR is not seen by the job (feature/app1/test-branch -> master). Have you any idea why does not work ?

Thanks

**Comment by nfalco79** [comment]
> The [SCM Filter Branch PR](https://plugins.jenkins.io/scm-filter-branch-pr/) plugin is exactly what you need.
> 
> It works nice in combination with the bitbucket branch source plugin as well.

I can confirm.
