### ISSUE TITLE
Trigger builds on tag discovery

### ISSUE THREAD

**Issue by Semmu** [jenkinsci/bitbucket-branch-source-plugin#422]
### Your checklist for this issue

- [x] Jenkins version: 2.267

- [x] Plugin version: 2.9.7

- [x] Bitbucket cloud

- [ ] Bitbucket server and version

### Description

Hey folks,

We started using this plugin extensively, (had some issues with creating multibranch organization scanners that discover tags by default, via configuration as code), but it seems there is no way for the discovered tags to be built automatically.

I was searching related issues here, but only found comments explaining that it is not currently implemented.

Could I request this feature to be added? I was trying to implement this feature myself and create a pull request, but I got lost in the code and don't know what should be added that triggers the build. (Didn't really work with Jenkins and its ecosystem before.)

Thanks in  advance!

**Comment by andham** [comment]
You can use https://plugins.jenkins.io/basic-branch-build-strategies/ for this.

**Comment by Semmu** [comment]
Thanks for the quick response!

I installed this plugin and tried to configure the organization scanner, but nothing changed on the UI, I see no new options added by this plugin, so I'm still stuck.

Could you elaborate please how to setup this?

(Also, I would appreciate Job DSL/CasC solutions, because we are automating our Jenkins deployments.)

**Comment by andham** [comment]
Sorry, we don't use organization scanner. Also, we ended up not using that plugin (for now) as the need for building on tags is very limited in our shop.

**Comment by Semmu** [comment]
There seems to be a misunderstanding.

By "organization scanner" I mean this very plugin I opened this issue for. (ID: `cloudbees-bitbucket-branch-source`)
And you suggested to install `basic-branch-build-strategies`.
Then I guess there is no way to make them work together, like you suggested?

In this case I still want to request this feature from the maintainers/developers of this plugin, or please show me some general direction I should go to implement this feature myself.

**Comment by andham** [comment]
When you said "organization" I thought you were referring to Bitbucket Team/Project scanning (called organizations in GitHub). We're not using that but "plain" multibranch pipelines.
I don't remember the exact configuraton but after installing the linked plugin, it should be possible to add "Discover tags" as a behaviour and there have strategy configuration. I think this also affects the other behaviors but I'm not sure.

**Comment by bitwiseman** [comment]
> I was searching related issues here, but only found comments explaining that it is not currently implemented.

Which comments are those?

> By "organization scanner" I mean this very plugin I opened this issue for. (ID: `cloudbees-bitbucket-branch-source`)
> And you suggested to install `basic-branch-build-strategies`.
> Then I guess there is no way to make them work together, like you suggested?

Those two plugins absolutely work together.  Could you provide more of a description of what your configuration looks like? Maybe screenshot(s) of the job that you are trying to configure?  

> In this case I still want to request this feature from the maintainers/developers of this plugin, or please show me some general direction I should go to implement this feature myself.

I'm pretty sure you should not need to implement this yourself.

**Comment by Semmu** [comment]
> Which comments are those?

I do not remember exactly, but for example, people were discussing this issue here: https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/139#issuecomment-443201532 (or at least something related, I'm not sure how the plugin currently handles new tag creation and its webhook event without re-running the whole organization scanner)

> Those two plugins absolutely work together. Could you provide more of a description of what your configuration looks like? Maybe screenshot(s) of the job that you are trying to configure?

Yes, they indeed work together, I just missed it. But my problem is still the same, after I run the organization scanner, the branches and PRs are automatically built, but the tags need to be triggered manually.

My (relevant) configuration looks like this on the UI:
<img width="733" alt="Screenshot 2021-01-27 at 18 10 24" src="https://user-images.githubusercontent.com/1938602/106027224-fb420400-60ca-11eb-8fd8-efda0c14a2b3.png">

And this is the Job DSL code (snippet) used to seed the organization scanners:
```groovy
// "Traits" ("Behaviours" in the GUI) that are NOT "declarative-compatible"
// For some 'traits, we need to configure this stuff by hand until JobDSL handles it
// https://issues.jenkins.io/browse/JENKINS-45504
configure { node ->
    def traits = node / navigators / 'com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMNavigator' / traits
    traits << 'com.cloudbees.jenkins.plugins.bitbucket.BranchDiscoveryTrait' {
        strategyId('3')
    }

    traits << 'com.cloudbees.jenkins.plugins.bitbucket.OriginPullRequestDiscoveryTrait' {
       strategyId('2')
    }

    traits << 'com.cloudbees.jenkins.plugins.bitbucket.TagDiscoveryTrait' {
      null
    }
}
```

As you can see everything is set to be discovered automatically (branches, PRs, and tags), but tags are not built when discovered, so the behaviour is different for those unfortunately.

**Comment by eoc-ross** [comment]
I'm facing the same problem with Jenkins v2.282. I've tried installing basic-branch-build-strategies plugin but never managed to make it work.

Even worse, after the installation, all hooks suddenly stop working and there is no way to make them process events again. Even unistalling and removing old configuration is not enough.

Is there someone that has some experience with these 2 plugin working together that can provide some insight? It would be really appreciated.

**Comment by eoc-ross** [comment]
So, I gave it another shot and finally managed to make it work. After installing basic-branch-build-strategies plugin, a new section is available in the Team/Project job config. You have to add all 3 strategies:

- Change requests
- Regular branches
- Tags

![image](https://user-images.githubusercontent.com/51781826/110638946-6e04cb80-81af-11eb-9a5d-137628b3bf71.png)

I'm not sure what happened yesterday, but I might have been playing with plugins too much. This time I tried with a fresh jenkins install and everything worked as expected.

Regards

**Comment by lifeofguenter** [comment]
@Semmu you might need to use the "native" bitbucket-server API for tag-events to successfully be fired :)
