### ISSUE TITLE
Add support to app password

### ISSUE THREAD

**Issue by Rulqu** [jenkinsci/bitbucket-branch-source-plugin#436]
Sorry, this is a bug report at the same time.

### Feature Request

We are getting locked out with the default account login for some reason. Might even be that the account is being bruteforced. Apparently it wouldn't lock out the app password login in a similar way. 

![image](https://user-images.githubusercontent.com/11457361/111450089-b45eab00-8718-11eb-991c-75c8a1a6781e.png)

I tried inserting app password to credentials and it doesn't find anything with it so I'm asking if it could be implemented.

**Comment by hasterhorb** [comment]
Did you recently change the password? If so, you are most likely affected by #321

**Comment by nfalco79** [comment]
Does this issue happens with latest plugin version? I had test recently repository browser, git clone/pull/push and Scan organization folder without issue.
