### ISSUE TITLE
Possibility to limit amount of discovered tags

### ISSUE THREAD

**Issue by a-socha** [jenkinsci/bitbucket-branch-source-plugin#441]
Hi Guys, 
I would like to know if there is a chance to introduce a limit of discovered tags number in the plugin. 
![image](https://user-images.githubusercontent.com/10079283/115515648-a525cc80-a285-11eb-85fd-246a7ec7adfe.png)
I imagine that it will be great if you can specify number X there and then Jenkins shows you only X of the latest tags in your repo. If parameter not specified - Jenkins show all for Backward Compatibility.

**Comment by lifeofguenter** [comment]
Tags in Git are just symlinks to a commit - and they can also be updated, so I assume it might be a bit tricky to get an accurate display of "give me the last x-number of tags".

If you use [basic-branch-build-strategies](https://plugins.jenkins.io/basic-branch-build-strategies/) you can at least simulate something similar easily by ignoring tags older than x-days:

![Screenshot 2021-11-13 220859](https://user-images.githubusercontent.com/241073/141659140-2cbe083b-68f5-47a5-b282-3eb6ab403c4f.png)

**Comment by ryancurrah** [comment]
@lifeofguenter I've tried using that setting tags older than 30 days are still being recognized. Our issue is that we have a lot of tags and cannot prune them easily. Because Go uses tags. Is it possible we could contribute this as a feature to this plugin?
