### ISSUE TITLE
Bitbucket cloud's workspaces are not recognized

### ISSUE THREAD

**Issue by 375gnu** [jenkinsci/bitbucket-branch-source-plugin#450]
I leave my original report, but i found that the plugin doesn't recognize workspaces and treats them as ordinal users and so `role` parameter is added.

## Version report

Jenkins and plugins versions report:

Various. Plugin versions 2.7.0 and 2.9.8 were tested.

### Reproduction steps

- Goto bitbucket cloud
- Create a workspace and several repositories in the workspace
- Create a new Bitbucket Team/Project in Jenkins

### Results

Expected result:

All those repositories should be listed.

Actual result:

No repositories are listed.

According to official Bitbucket API documentation (https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D):

> Returns a paginated list of all repositories owned by the specified account or UUID.
> 
> The result can be narrowed down based on the authenticated user's role.
> 
> E.g. with ?role=contributor, only those repositories that the authenticated user has write access to are returned (this includes any repo the user is an admin on, as that implies write access).
> 
> This endpoint also supports filtering and sorting of the results. See filtering and sorting for more details.

So, `role=owner` makes sense only for a personal workspace. For organizations it should be omitted (in that case it's implicitly `role=member`) or made configurable (admin/contributor/member/owner).

**Comment by InnocentChukwuDevOps** [comment]
Hello, Please I need help. I have installed the bitbucket-branch-source-plugin. I added the correct credentials for bitbucket in Manage Jenkins > Configure System > Bitbucket Endpoints > Manage hooks. Then I created a multibranch pipeline and in branch sources, I selected the bitbucket cloud, and added the same credentials I added in the bitbucket endpoints (This is the correct credentials), I added the owner which is an admin account but the repository names do not display.
The bitbucket cloud account is an organization account and there are over 50 repositories on it yet I can't get anyone to display in the dropdown. Please assist me with this

**Comment by InnocentChukwuDevOps** [comment]
I am using Jenkins 2.387.1

**Comment by nfalco79** [comment]
I wouls ask if this issue is still present using latest plugin version?

Anyway this issue is not clear to me. Please update step to reproduce with a complete configuration about the project, authentication used and so on.

**Comment by 375gnu** [comment]
I personally can't help as I left the project that used Bitbucket Cloud.
