### ISSUE TITLE
Bitbucket v7.12.0+ fixed on pull requests refs

### ISSUE THREAD

**Issue by qibint** [jenkinsci/bitbucket-branch-source-plugin#458]
As Atlassian team fixed this pull request refs issue [here](https://jira.atlassian.com/browse/BSERV-12284) which causes the plugin to fall back to heavyweight checkout [here](https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/409/commits/4bd445ac7cb5da05d5d04413969981e69bba4756). Do we have any plan to update to use lightweight checkout again for version 7.12.0+?

Thanks,
Qibin

**Comment by bitwiseman** [comment]
That change by atlassian do what you think it does. We still cannot do lightweight checkout when using the merge strategy for  PR builds. And you can already do lightweight weight checkout using the "head"/"from branch" strategy.   Please double check your configuration.  If you believe I'm mistaken, please screenshot or provide the config.xml for your job.

**Comment by qibint** [comment]
@bitwiseman refs/pull-requests/*/from was re-added back from Atlassian but based on the comment, refs/pull-requests/*/merge will never be used in the future which this branch source plugin relies on. So it looks like we have to use the heavy checkout from the plugin for a while. Since our codebase size is very large and our current workaround is to clean up pull request workspace after each run to save disk space. Do you guys have any other solution that can help in this case?

Thank you,
Qibin

**Comment by bitwiseman** [comment]
Unfortunately, this stance from Atlassian means you have only two options: use "merge" strategy with heavy weight checkout, or use "head" strategy to get  lightweight checkout.

**Comment by qibint** [comment]
@bitwiseman From my understanding, your most recent [changes](https://github.com/sams-gleb/bitbucket-branch-source-plugin/commit/4bd445ac7cb5da05d5d04413969981e69bba4756) is only a backward compatible solution and as more users upgrade their bitbucket either datacenter or server version to 7+, they will have the same problem eventually. Since the plugin is designed and used for Bitbucket, do you have any plans to address this issue? Is there a way to use the "head" strategy instead in this case? Please correct me if I'm wrong.

Thank you Liam!
Qibin

**Comment by sschleemilch** [comment]
Hi everyone,

has anyone noticed that `refs/pull-requests/*/from` might not be available as soon as the build starts?
We do see quite often that the initial build fails to fetch the ref and after waiting some time it then succeeds.
Might this be a runtime problem that Bitbucket takes some time to create the ref? That might have problems when Bitbucket is under heavy load?

Thanks :-)

**Comment by tuunit** [comment]
> Hi everyone,
> 
> has anyone noticed that `refs/pull-requests/*/from` might not be available as soon as the build starts?
> We do see quite often that the initial build fails to fetch the ref and after waiting some time it then succeeds.
> Might this be a runtime problem that Bitbucket takes some time to create the ref? That might have problems when Bitbucket is under heavy load?
> 
> I would be also interested why we rely on the `/from` ref when we could just use the source branch of a pull-request instead, couldn't we? Wouldn't that be more safe since the source branch is assured to be available as soon as the `git push` went through?
> 
> Thanks :-)

Hi indeed, that is a problem you will face since v7 of Bitbucket because the refs are lazily generated. Fortunately, you can enforce the update of the refs by checking the Can Merge API and Change API Checkboxes in the Bitbucket Plugin endpoint settings in Jenkins. This way Jenkins will essentially ask bitbucket to create the refs before trying to pull them.

**Comment by sschleemilch** [comment]
> Fortunately, you can enforce the update of the refs by checking the "Call Can Merge" and "Call Changes api"

I see, thanks for the response. I figured that this might solve the problem and it leads to HTTP 429's for us.
I can see that there are a few PR's planning to deal with that by introducing retry mechanisms. However, that will not solve the problem but will just postpone it a little bit. After all, if you have too many pull-requests, you will reach the set limit anyway. But with a retry mechanism we could at least start the builds delayed instead of needing to trigger those builds manually again.

**Comment by sschleemilch** [comment]
Regarding taking the `/from` ref at all:
I just tried to patch the plugin regarding taking the source branc.
So basically I am talking about those diffs:
```diff
diff --git a/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java b/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
index e423b6f..19c7bc9 100644
--- a/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
+++ b/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java
@@ -104,8 +104,8 @@ public class BitbucketGitSCMBuilder extends GitSCMBuilder<BitbucketGitSCMBuilder
                 String branchName = ((PullRequestSCMHead) head).getBranchName();
                 withRefSpec("+refs/heads/" + branchName + ":refs/remotes/@{remote}/" + head.getName());
             } else {
-                String pullId = ((PullRequestSCMHead) head).getId();
-                withRefSpec("+refs/pull-requests/" + pullId + "/from:refs/remotes/@{remote}/" + head.getName());
+                String branchName = ((PullRequestSCMHead) head).getBranchName();
+                withRefSpec("+refs/heads/" + branchName + ":refs/remotes/@{remote}/" + head.getName());
             }
         } else if (head instanceof TagSCMHead ){
             withRefSpec("+refs/tags/" + head.getName() + ":refs/tags/" + head.getName());

```
```diff
diff --git a/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java b/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
index eb920ed..de8567f 100644
--- a/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
+++ b/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/filesystem/BitbucketSCMFileSystem.java
@@ -180,7 +180,7 @@ public class BitbucketSCMFileSystem extends SCMFileSystem {
                         return null;
                     }
                 } else if (pr.getCheckoutStrategy() == ChangeRequestCheckoutStrategy.HEAD) {
-                    ref = "pull-requests/" + pr.getId() + "/from";
+                    ref = "refs/heads/" + pr.getBranchName();
                 } else if (pr.getCheckoutStrategy() == ChangeRequestCheckoutStrategy.MERGE) {
                     // Bitbucket server v7 doesn't have the `merge` ref for PRs
                     // We don't return `ref` when working with v7
@@ -191,8 +191,7 @@ public class BitbucketSCMFileSystem extends SCMFileSystem {
                     if (endpoint != null && endpoint.getServerVersion() != BitbucketServerVersion.VERSION_7) {
                         ref = "pull-requests/" + pr.getId() + "/merge";
                     } else {
-                        // returning null to fallback to heavyweight checkout
-                        return null;
+                        ref = "refs/heads/" + pr.getBranchName();
                     }
                 }
             } else if (head instanceof BitbucketTagSCMHead) {

```
Is there a reason we aim for the `/from` ref at all?

**Comment by bitwiseman** [comment]
@sschleemilch 
We point at the `/from` ref because that is where we **should** point per Atlassian. It also made more sense to do so when BB supported the `/merge` ref.  Now that they don't, it is a bit more academic.  

Most of you change above looks reasonable to me, but it entirely possible that it will fail in some unexpected way. 

That said, this part is definitely incorrect: 
```
-                        // returning null to fallback to heavyweight checkout
-                        return null;
+                        ref = "refs/heads/" + pr.getBranchName();
```

The fallback to heavyweight checkout needs to still be there - just revert these lines.

**Comment by sschleemilch** [comment]
@bitwiseman I agree. Those lines should have been just my private patch to not allow a heavyweight checkout at all on our Jenkins. For a general patch that should be reverted for sure.

**Comment by aajimal** [comment]
For teams that use rebase workflows does the PR **merge** strategy still approximate the changeset accurately enough?

**Comment by ikari7789** [comment]
Personally for me, it seems best to not use `refs/pull-requests/{id}/from`. In all of the places I've searched online, it is mentioned by the development team directly themselves that these refs are undocumented and could change at any time. In fact, in my own situation, these refs aren't even being updated and are pointing at totally random commits from years ago and breaking all of my builds. Attempting to try the diff from @sschleemilch hoping that it fixes my builds.

**Comment by KalleOlaviNiemitalo** [comment]
The patch in <https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/458#issuecomment-872962140> looks like it would try to get the source branch from the repository in which the pull request resides, even if the source branch is actually in a repository forked from that. But if you don't use forks, then it could work OK.

**Comment by sboardwell** [comment]
> The patch in [#458 (comment)](https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/458#issuecomment-872962140) looks like it would try to get the source branch from the repository in which the pull request resides, even if the source branch is actually in a repository forked from that. But if you don't use forks, then it could work OK.

Is there any solution to this?

**Comment by nfalco79** [comment]
Duplicates [JENKINS-61493](https://issues.jenkins.io/browse/JENKINS-61493)
