### ISSUE TITLE
Add more environment variables

### ISSUE THREAD

**Issue by raijinsetsu** [jenkinsci/bitbucket-branch-source-plugin#462]
### Feature Request
The plugin should set the following expected environment variables:

* GIT_COMMIT - The commit hash being checked out.
* GIT_PREVIOUS_COMMIT - The hash of the commit last built on this branch, if any.
* GIT_PREVIOUS_SUCCESSFUL_COMMIT - The hash of the commit last successfully built on this branch, if any.
* GIT_BRANCH - The remote branch name, if any.
* GIT_LOCAL_BRANCH - The local branch name being checked out, if applicable.
* GIT_CHECKOUT_DIR - The directory that the repository will be checked out to. This contains the value set in Checkout to a sub-directory, if used.
* GIT_URL - The remote URL. If there are multiple, will be GIT_URL_1, GIT_URL_2, etc.

This can be seen in any pipeline by adding `sh 'env'` and looking at the console log.

Without these, it is difficult to make build-time decisions. As an example: we skip the actual build and tests if the files that were modified are only documentation but we need to know the commit of the last successful build (GIT_PREVIOUS_SUCCESSFUL_COMMIT) in order to properly detect the changes.

There two work-arounds:
1. use the "Git Source Plugin" instead
2. store the commit as an artifact at the tail end of the build and restore it at the start

**Comment by doman18** [comment]
Im not sure i understand. For multibranch jobs this plugin sets these variables:
```
GIT_BRANCH
GIT_COMMIT
GIT_PREVIOUS_COMMIT
GIT_PREVIOUS_SUCCESSFUL_COMMIT
GIT_URL_1
GIT_URL_2
GIT_URL
```
So only GIT_CHECKOUT_DIR is missing but i think is easy to obtain. For PRs it also sets these 
```
CHANGE_AUTHOR
CHANGE_AUTHOR_DISPLAY_NAME
CHANGE_BRANCH
CHANGE_ID
CHANGE_TARGET
CHANGE_TITLE
CHANGE_URL

```
In case of using `checkout scm` you will be able get these from the object ...
```
def checkoutDetails = checkout scm
echo checkoutDetails.toString()
```
you will get
```
[GIT_BRANCH:master, GIT_COMMIT:68467f5b30b5d7ff3647889e907591f074d06b26, GIT_PREVIOUS_COMMIT:533ff7830bfcf09265790e466f343801787d2ed4, GIT_PREVIOUS_SUCCESSFUL_COMMIT:533ff7830bfcf09265790e466f343801787d2ed4, GIT_URL:git@bitbucket.org:organisation/dummy-repo.git]
```

I think that the only variable which is missing here are credentials ID. Both for the repository scanning/pulling and SSH checkout in case of using this function. It would be really usefull in case if someone would want to use it to more customised checkouts/fetch/pulling/commiting.

**Comment by lgcCerti** [comment]
> Im not sure i understand. For multibranch jobs this plugin sets these variables:
> 
> ```
> GIT_BRANCH
> GIT_COMMIT
> GIT_PREVIOUS_COMMIT
> GIT_PREVIOUS_SUCCESSFUL_COMMIT
> GIT_URL_1
> GIT_URL_2
> GIT_URL
> ```
> 
> So only GIT_CHECKOUT_DIR is missing but i think is easy to obtain. For PRs it also sets these
> 
> ```
> CHANGE_AUTHOR
> CHANGE_AUTHOR_DISPLAY_NAME
> CHANGE_BRANCH
> CHANGE_ID
> CHANGE_TARGET
> CHANGE_TITLE
> CHANGE_URL
> ```
> 
> In case of using `checkout scm` you will be able get these from the object ...
> 
> ```
> def checkoutDetails = checkout scm
> echo checkoutDetails.toString()
> ```
> 
> you will get
> 
> ```
> [GIT_BRANCH:master, GIT_COMMIT:68467f5b30b5d7ff3647889e907591f074d06b26, GIT_PREVIOUS_COMMIT:533ff7830bfcf09265790e466f343801787d2ed4, GIT_PREVIOUS_SUCCESSFUL_COMMIT:533ff7830bfcf09265790e466f343801787d2ed4, GIT_URL:git@bitbucket.org:organisation/dummy-repo.git]
> ```
> 
> I think that the only variable which is missing here are credentials ID. Both for the repository scanning/pulling and SSH checkout in case of using this function. It would be really usefull in case if someone would want to use it to more customised checkouts/fetch/pulling/commiting.

Where was this documented? I spent hours looking for this list and even looking at the source code.
