### ISSUE TITLE
Add comment to Pull Request

### ISSUE THREAD

**Issue by jdomag** [jenkinsci/bitbucket-branch-source-plugin#477]
Is there any simple way of detecting that job has started as a result of Pull Request creation (not regular push to the branch) and fetch PR id to use Bitbucket API to comment back to PR? 
I would like to do some operations and post a result of it to PR to make life of reviewer easier.

**Comment by mguillem** [comment]
@jdomag PR id is available as `env.CHANGE_ID`. Some other variables are availaible as well: 
https://javadoc.jenkins.io/plugin/pipeline-model-definition/org/jenkinsci/plugins/pipeline/modeldefinition/when/utils/EnvironmentNames.html

Jenkins `httpRequest` step can be used to perform the request like:
```
httpRequest url: url, contentType: 'APPLICATION_JSON', httpMode: 'POST', authentication: 'my-auth-token', requestBody: groovy.json.JsonOutput.toJson([text: ":warning: Jenkins Build failed $BUILD_URL"])
```
but I agree, this would be a nice feature for this plugin.

**Comment by jdomag** [comment]
> @jdomag PR id is available as `env.CHANGE_ID`. Some other variables are availaible as well:
> https://javadoc.jenkins.io/plugin/pipeline-model-definition/org/jenkinsci/plugins/pipeline/modeldefinition/when/utils/EnvironmentNames.html
> 
> Jenkins `httpRequest` step can be used to perform the request like:
> 
> ```
> httpRequest url: url, contentType: 'APPLICATION_JSON', httpMode: 'POST', authentication: 'my-auth-token', requestBody: groovy.json.JsonOutput.toJson([text: ":warning: Jenkins Build failed $BUILD_URL"])
> ```
> 
> but I agree, this would be a nice feature for this plugin.

Are you sure it's avaliable via bitbucket branch source plugin? I can see those env in MultiBranch Pipeline only not in Bitbucket Team/Project:
https://www.jenkins.io/doc/book/pipeline/multibranch/

**Comment by nfalco79** [comment]
CHANGE_ID env variable is contributed by git plugin using the information provided by the specific implementation of bitbucket plugin. That varialbe is valued only for pull request.
To archive what you are asking you can list comments for current pull request filtering by author and in case there are not comment that you can post one. At least this is how the old Sonarqube plugin works for SonarQube 6.x when comments the code line or approve/disapprove a pull reuqest when pass the quality gate.
