### ISSUE TITLE
The variavble CHANGE_AUTHOR_EMAIL is missing on pull requests

### ISSUE THREAD

**Issue by dsaydon90** [jenkinsci/bitbucket-branch-source-plugin#482]
### Feature Request

currently on pull requests I can notice only the following environment variables the related to the `CHANGE`

```
CHANGE_AUTHOR_DISPLAY_NAME
CHANGE_AUTHOR
CHANGE_TITLE
CHANGE_BRANCH
```

It will be awesome to have the environment variable `CHANGE_AUTHOR_EMAIL` also on pull requests

**Comment by KalleOlaviNiemitalo** [comment]
Branch API adds CHANGE_AUTHOR_EMAIL if available from ContributorMetadataAction. getContributorEmail():

<https://github.com/jenkinsci/branch-api-plugin/blob/1b883b9a05b7c1a265975eb30e1da9eaa0fa3f03/src/main/java/jenkins/branch/BranchNameContributor.java#L86-L91>

Bitbucket Branch Source creates ContributorMetadataAction here:

<https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/0e0a8e79418a318cde4ce39d3021f6cd24a0df1a/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java#L648-L649>

It takes the email address from BitbucketPullRequest.getAuthorEmail(). That should be working already… unless Bitbucket Cloud has started hiding the email address. Are you using Bitbucket Cloud, Server, or Data Center?

**Comment by dsaydon90** [comment]
Thank you for your answer @KalleOlaviNiemitalo 
I'm using **Bitbucket cloud**
Any way that I can help to debug it?

**Comment by KalleOlaviNiemitalo** [comment]
Looks like it is just not available:

<https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/0e0a8e79418a318cde4ce39d3021f6cd24a0df1a/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/BitbucketPullRequest.java#L60-L63>

**Comment by dsaydon90** [comment]
well, it's a bit frustrated

So I opened a ticket in Bitbucket cloud:
https://jira.atlassian.com/browse/BCLOUD-21349

I'll reopen this ticket if they will provide a solution for this

**Comment by KalleOlaviNiemitalo** [comment]
I assume the Bitbucket Branch Source plugin uses the following Bitbucket Cloud REST API to ask for information about a pull request: <https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/pullrequests/%7Bpull_request_id%7D>

The response from that can apparently contain an Account object that describes the author of the pull request, but that object does not contain any email properties.

Likewise, if you ask for information about a user, then the response does not include any email properties: <https://developer.atlassian.com/bitbucket/api/2/reference/resource/users/%7Bselected_user%7D>

Any user can still query their own registered email addresses, though: <https://developer.atlassian.com/bitbucket/api/2/reference/resource/user/emails>

> In [Bitbucket Cloud REST APIs are changing to improve user privacy](https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/), Atlassian warned that they were removing even user names from Bitbucket Cloud APIs. Because of that, I think they are very unlikely to add email addresses to the API responses.

Perhaps you could maintain your own mapping from Atlassian Account IDs or user nicknames to email addresses, and make the pipeline look up the email address from that. Such a database could run afoul of privacy laws though, so consult your lawyers first.
