### ISSUE TITLE
Add link to commit in build page's side bar

### ISSUE THREAD

**Issue by stth1998** [jenkinsci/bitbucket-branch-source-plugin#486]
### Dependencies

none.

### Feature Request

The plugin adds a side bar link into the Jenkins branch overview page of a multibranch build. This directs to the bitbucket source page of that particular branch.

![image](https://user-images.githubusercontent.com/5288317/134668109-15298d94-a9e3-436b-b889-5cb90482be1c.png)

It should also add a side bar link into the overview page of each build directing to the bitbucket commit page of the actually built commit. This link would also appear in the context menu of the builds list of the page mentioned above.

![image](https://user-images.githubusercontent.com/5288317/134668276-486378e0-11f7-4bfb-9349-f69a5462c127.png)

**Comment by KalleOlaviNiemitalo** [comment]
There are already similar links on the "Status" page of each build, although not in the sidebar:

- The "Changes" list links to each commit.
- The "SCM" section has a "Latest commit:" line that links to one commit.

One of the builds in our Jenkins instance has 18 links in the sidebar. If more redundant links are added there, I might have to scroll the page before I see the link I really want.

<details><summary>18 links in sidebar</summary>

1. Back to Project
1. Status
1. Changes
1. Console Output
1. Edit Build Information
1. Delete build ‘#‌&#x200B;2’
1. Timings
1. Git Build Data
1. DocFX Warnings
1. MSBuild Warnings
1. Pipeline Graph
1. Pipeline Console
1. Restart from Stage
1. Replay
1. Pipeline Steps
1. Workspaces
1. Previous Build
1. Next Build

</details>

**Comment by stth1998** [comment]
"git build data" as well as "changes"only contain the commit id and the branch name, but not even the git repo link (which is bad for multi-repo builds https://issues.jenkins.io/browse/JENKINS-29840)

So, one has to construct the link manually.

**Comment by KalleOlaviNiemitalo** [comment]
Oh, I was confused. The "SCM" section and the "Latest commit" link that I see on the "Status" page actually come from git-forensics-plugin: <https://github.com/jenkinsci/git-forensics-plugin/blob/cfbb7c7181ae5fe28fed650120d78d30eb2c5028/plugin/src/main/resources/io/jenkins/plugins/forensics/git/reference/GitCommitsRecord/summary.jelly#L16>

**Comment by nfalco79** [comment]
Bitbucket action link in the main multibranch job view links to the repository bitbucket page
Bitbucket action link in the main branch/PR job view links to the specific branch bitbucket page
Each build in the Changes page contains the whole URL to the commit on bitbucket
![Image](https://github.com/user-attachments/assets/a2480243-02df-475f-91c5-9d1c5e194678)
