### ISSUE TITLE
Filtering does not work for pull requests in multibranch jobs

### ISSUE THREAD

**Issue by doman18** [jenkinsci/bitbucket-branch-source-plugin#489]
### Version report

Jenkins and plugins versions report:

```
Jenkins 2.277.3
Bitbucket Branch Source 2.9.8
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Linux ubuntu 18.04
```

### Reproduction steps

- Create multibranch job
- Set Bitbucket as source
- Set Server, Credentials, Owner, repository name fields, and Jenkinsfile name if needed
- Remove discover branches, leave the rest fields for PR with default settings
- Add Filter by name (with wildcards)  and put '*feature/JenkinsBranch_1' or just '*JenkinsBranch_1'
- Click 'save'
- Create 'feature/JenkinsBranch_1', make 2 pull request where this branch is source and target

### Results

Expected result:

Pull requests for respected branch should be filtered, whether it is source or target branch. 

Actual result:

Nothing shows up, log shows that it is recognised but it seems to be ignored. When i set the filter to * or delete it then PRs jobs will show up and run. 
This filtering works with branches tab jobs so my guess is that plugin checks only GIT_BRANCH variable which in this case will always be something like 'PR-XXX' so there will be always mismatch. It should also take CHANGE_BRANCH and CHANGE_TARGET in condieration if they exist.

```
Started
[Thu Sep 30 07:14:43 UTC 2021] Starting branch indexing...
Connecting to https://bitbucket.org using SomUser/****** (SomUser)
Repository type: Git
Looking up MyCompany/my_repository for pull requests
Checking PR-216 from mycompany/my_repository and branch test/jenkins-branch
Checking PR-215 from mycompany/my_repository and branch feature/JenkinsBranch_1

  2 pull requests were processed
[Thu Sep 30 07:14:44 UTC 2021] Finished branch indexing. Indexing took 0.96 sec
```

**Comment by KalleOlaviNiemitalo** [comment]
"Filter by name (with wildcards)" is implemented as [WildcardSCMHeadFilterTrait in scm-api-plugin](https://github.com/jenkinsci/scm-api-plugin/blob/scm-api-2.6.5/src/main/java/jenkins/scm/impl/trait/WildcardSCMHeadFilterTrait.java). If you want to filter pull requests based on the names of the source and target branches, I think it could be a new check box in the existing WildcardSCMHeadFilterTrait, or a new trait. Either way, it should be implemented in scm-api-plugin, not in bitbucket-branch-source-plugin. The trait would be able to read the branch names from [ChangeRequestSCMHead2](https://javadoc.jenkins.io/plugin/scm-api/jenkins/scm/api/mixin/ChangeRequestSCMHead2.html).

**Comment by doman18** [comment]
@KalleOlaviNiemitalo Thanks for clarification. I will make the proper bug ticket in scm-api github and add the link to this topic.

**Comment by KalleOlaviNiemitalo** [comment]
Issues are not enabled in the [scm-api-plugin GitHub repository](https://github.com/jenkinsci/scm-api-plugin/). Please use the "Report an issue" link at <https://plugins.jenkins.io/scm-api/>.

**Comment by KalleOlaviNiemitalo** [comment]
I am curious about your use case, though. Why cannot you just include `PR-*`; do you have branches that are actively getting pull requests that you regardless don't want to build in Jenkins?

**Comment by doman18** [comment]
@KalleOlaviNiemitalo Repository already has file called 'Jenkinsfile'. This is triggered during normal PR's.
Now i added second 'Jenkinsfile1' with completely different set of actions which should be triggered only for PRs releated to 'feature/JenkinsBranch_1'. This is special branch dedicated for it. So i dont care about 'PR-*' name, i care about 'JenkinsBranch_1' name. Any other PRs should not trigger Jenkinsfile1.
Offcourse i could somehow try to add conditional in default Jenkinsfile, but it will really complicate things. So im trying to avoid that as much as possible

**Comment by KalleOlaviNiemitalo** [comment]
@doman18 Will you have pull requests with feature/JenkinsBranch_1 as the source branch?

**Comment by doman18** [comment]
@KalleOlaviNiemitalo AFAIK the pull requests will be made as feature/JenkinsBranch_1 -> develop.

**Comment by doman18** [comment]
I think i found a way. Instead of PRs sections i use 'branches' section and take 'Only branches also filled as PRs' rule in autodiscovery form. This works for PRs where feature/JenkinsBranch_1 is as source branch.
