### ISSUE TITLE
PRs from forks won't be detected

### ISSUE THREAD

**Issue by krulls** [jenkinsci/bitbucket-branch-source-plugin#521]
### Version report

Jenkins and plugins versions report:
Jenkins LTS 2.303.2
Pipeline Multibranch plugin 2.26 (https://plugins.jenkins.io/workflow-multibranch)
Bitbucket Branch Source plugin 2.9.11
and many others...

Bitbucket:
DataCenter edition, LTS 7.6.2
Post Webhooks add-on 2.5.3 (https://marketplace.atlassian.com/apps/1215474/post-webhooks-for-bitbucket?tab=overview&hosting=datacenter)

- What Operating System are you using (both controller, and any agents involved in the problem)?
Controller: CentOS 7

### Reproduction steps

- create a new "Multibranch Pipeline" job
- set up Branch source to the Bitbucket instance (we have DataCenter edition, version 7.6.2)
- set up the correlated repository (the repo has webhook configured to report changes to the corresponding endpoint on Jenkins side)
- add behaviours: discover branches, discover PRs from origin, discover PRs from forks, see 
![image](https://user-images.githubusercontent.com/866191/142629655-8e67d244-5465-4c66-9409-59b66d324a14.png)
- once saved, the job detects all branches in the origin repo and creates jobs properly
- create a fork of the origin repo
- create a branch in the fork repo
- create a PR in the origin repo: source is the new branch in the fork

### Results

Expected result:

PR is getting detected, new job created and being built

Actual result:

Nothing is happening, the multibranch pipeline job is not aware of the new PR

### Workaround

I can manually trigger a scan of the multibranch pipeline job. This reveals the outstanding PR from the fork and creates a job for it.

**Comment by lifeofguenter** [comment]
Are the webhooks being created? I would most probably also recommend using the native webhook plugin.

**Comment by krulls** [comment]
@lifeofguenter : Not sure what you mean with "created". They are configured the way that we have that logic running for years already. There was no change on Bitbucket side but upgrades on Jenkins side, that's why I assume it is related with this plugin here. And there were suspicious changes which could have introduced a buggy behaviour, see https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/445.

Thank you for the hint about the native webhooks in Bitbucket. We plan to migrate the configurations later on.

**Comment by lifeofguenter** [comment]
@krulls this plugin will create native webhooks if it is given permissions to do so. I can not say if it works or not on custom setups, but on the setup intended it will work.

Can you check in your webhook settings there should be a log in bitbucket of events - so you see any reaching your jenkins?

**Comment by krulls** [comment]
Before we go into further detail of the logic and logs of the webhook that is being triggered by Bitbucket actions (commits, PR changes) I want to inform you that we rolled back the plugin to version 2.9.9 and it works as before. That means:
In a multibranch pipeline job a new job gets created and built as soon as I open a PR in the origin repository. The source of this PR is a branch in a fork repository.

**Comment by krulls** [comment]
![image](https://user-images.githubusercontent.com/866191/142835425-508731a8-d1e9-49a6-9020-a3e55ba69b6e.png)
This is the configuration of the webhook trigger in the Bitbucket repository. You can see that it targets the webhook endpoint of this plugin.

**Comment by tanon-adm** [comment]
@lifeofguenter I faced the same issue. I updated the plugin and after that Jenkins stopped detecting PRs from repository forks. I can downgrade the plugin to version 2.9.8 only, but this version has security issues. Is there any chance that the bug will be fixed?

**Comment by sjjarvi** [comment]
@tanon-adm Is this the issue as mentioned in https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/469 ?

**Comment by tanon-adm** [comment]
@sjjarvi No, I didn't get a message like "‘Jenkinsfile’ not found". Everything works as expected on version 2.9.8 and it doesn't work on version 751.vda_24678a_f781 (after creating a PR there are no messages in the log, as if nothing happened).

**Comment by tanon-adm** [comment]
@lifeofguenter @sjjarvi Do you have any updates on my request? Maybe you need some additional information from my side?

**Comment by lifeofguenter** [comment]
@tanon-adm I am unable to replicate the issue - are you using native webhooks?

**Comment by tanon-adm** [comment]
@lifeofguenter No, I'm using 'Plugin' webhook implementation.

**Comment by lifeofguenter** [comment]
Do you mind checking if it works better using the native webhook?

**Comment by tanon-adm** [comment]
@lifeofguenter I have checked it now, with the native webhook it also doesn't work.
Additional information:
Jenkins LTS 2.319.2
Pipeline Multibranch plugin 706.vd43c65dec013 (https://plugins.jenkins.io/workflow-multibranch)
Bitbucket Branch Source plugin 751.vda_24678a_f781

**Comment by lifeofguenter** [comment]
can you please put a screenshot of your complete job-config and also which webhooks are enabled for the project?

Then I can try to replicate. Which version of Bitbucket are you using?

**Comment by tanon-adm** [comment]
My job config:
![изображение](https://user-images.githubusercontent.com/30141942/152389382-f4f19044-56b3-4ee4-b26c-4ef51bd85591.png)
![изображение](https://user-images.githubusercontent.com/30141942/152388252-fc0004fe-ca41-4f2b-89b2-0802cd5e9dc0.png)
![изображение](https://user-images.githubusercontent.com/30141942/152388564-482600d6-273a-4bd0-abc6-48992bcb3b3a.png)
![изображение](https://user-images.githubusercontent.com/30141942/152388805-b539b172-7514-4ae3-8145-de02ed869db3.png)

Atlassian Bitbucket v7.6.12

**Comment by lifeofguenter** [comment]
Hmm I am having difficulties replicating the issue. I created a new Bitbucket Server repo (v7.19.1), forked it, and the build immediately started in Jenkins (LTS, latest plugins):

![Screenshot from 2022-02-03 23-03-27](https://user-images.githubusercontent.com/241073/152437195-ad14abf3-7cfd-40de-9312-386875dbbc91.png)

My settings are slightly different, however I do not see anything obvious that might cause an issue:

![Screenshot from 2022-02-03 23-08-28](https://user-images.githubusercontent.com/241073/152437425-2b500c6f-f7af-480d-a358-aa6e9fc7be28.png)

![Screenshot from 2022-02-03 23-08-09](https://user-images.githubusercontent.com/241073/152437436-8fcb2d97-2563-4f04-b62f-5966f8e32b3e.png)

**However:**

My webhook config looks completely different (was created automatically by Jenkins):

![Screenshot from 2022-02-03 23-10-03](https://user-images.githubusercontent.com/241073/152437599-a29e66a1-8da0-438c-8c0e-9efd93c58bb8.png)

And that is the only webhook created - I do not have any separate webhook for PRs.

I am also not sure if there is a difference since I use branch-source/org-folder as opposed to multibranch pipeline

**Comment by krulls** [comment]
@lifeofguenter : The difference is that you use the Bitbucket native webhook, but @tanon-adm and me use the Post Webhooks add-on from the marketplace. Then it might just be related to this add-on. I am triggering a test internally to check if your proposed configuration works, then it seems we need to migrate away from the add-on.

(some extra info: the vendor of the add-on raises costs for it from a certain version, that's why we stuck to the rather old version of it. most current version is 3.25.24)

@tanon-adm : can you check which version of the add-on you have installed in your Bitbucket instance?

**Comment by tanon-adm** [comment]
@krulls We use version 1.12.23. It's old, but there is following warning message "You may update this app but the newest version isn't free. You can purchase a license through Atlassian.", so this is most likely the reason why. So you are right.

**Comment by krulls** [comment]
@nfalco79 : We have migrated away from the Post Webhooks add-on in Bitbucket, so I cannot test it.
