### ISSUE TITLE
NOT_BUILT is an error state, and should be reported as such

### ISSUE THREAD

**Issue by oreinert** [jenkinsci/bitbucket-branch-source-plugin#538]
When a build ends with a `NOT_BUILT` result, this plugin reports it as a success to a Bitbucket Server:

https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/9fa69fddd2e1d07df457a47185817b3f70fb6447/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketBuildStatusNotifications.java#L151

This behavior is wrong, it should be reported as a failure.

As it is now, a build ending with `NOT_BUILT` can satisfy the Merge Check "Minimum successful builds" in Bitbucket, thereby allowing developers to merge a pull request with such a check enabled, despite the fact that no build actually took place.

**Comment by KalleOlaviNiemitalo** [comment]
See <https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/448>, <https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/504>.

**Comment by lifeofguenter** [comment]
@oreinert we just released 751.vda_24678a_f781 that should include a fix :)
