### ISSUE TITLE
Upgrade from 734.v2f848c5e6ea2 to 737.vdf9dc06105be branch build is not triggered anymore

### ISSUE THREAD

**Issue by NilsRuiz** [jenkinsci/bitbucket-branch-source-plugin#540]
### Jenkins and plugins versions report

Jenkins: 2.319.1
OS: Linux - 4.15.0-147-generic
---
ace-editor:1.1
ant:1.13
antisamy-markup-formatter:2.6
apache-httpcomponents-client-4-api:4.5.13-1.0
atlassian-jira-software-cloud:1.4.4
authentication-tokens:1.4
authorize-project:1.4.0
bitbucket:214.v2fd4234d0554
blueocean:1.25.2
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.25.2
blueocean-commons:1.25.2
blueocean-config:1.25.2
blueocean-core-js:1.25.2
blueocean-dashboard:1.25.2
blueocean-display-url:2.4.1
blueocean-events:1.25.2
blueocean-git-pipeline:1.25.2
blueocean-github-pipeline:1.25.2
blueocean-i18n:1.25.2
blueocean-jira:1.25.2
blueocean-jwt:1.25.2
blueocean-personalization:1.25.2
blueocean-pipeline-api-impl:1.25.2
blueocean-pipeline-editor:1.25.2
blueocean-pipeline-scm-api:1.25.2
blueocean-rest:1.25.2
blueocean-rest-impl:1.25.2
blueocean-web:1.25.2
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-4
bouncycastle-api:2.25
branch-api:2.7.0
build-timeout:1.20
build-with-parameters:1.6
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-bitbucket-branch-source:737.vdf9dc06105be
cloudbees-folder:6.17
command-launcher:1.6
conditional-buildstep:1.4.1
cppcheck:1.25
credentials:1061.vb_1fceb_58fa_18
credentials-binding:1.27
date-parameter:0.0.4
display-url-api:2.3.5
docker-commons:1.17
docker-workflow:1.26
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-2
email-ext:2.86
extensible-choice-parameter:1.8.0
external-monitor-job:1.7
favorite:2.3.3
font-awesome-api:5.15.4-5
generic-webhook-trigger:1.79
git:4.10.1
git-automerger:0.6.3
git-changelog:3.15
git-client:3.11.0
git-server:1.10
github:1.34.1
github-api:1.301-378.v9807bd746da5
github-branch-source:2.11.4
gradle:1.37.1
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
htmlpublisher:1.28
jackson2-api:2.13.1-246.va8a9f3eaf46a
javadoc:1.6
jaxb:2.3.0.1
jdk-tool:1.5
jenkins-design-language:1.25.2
jira:3.6
jira-trigger:1.0.1
jjwt-api:0.11.2-9.c8b45b8bb173
job-dsl:1.78.3
join:1.21
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
ldap:2.7
lockable-resources:2.13
mailer:391.ve4a_38c1b_cf4b_
mapdb-api:1.0.9.0
matrix-auth:3.0
matrix-project:1.19
maven-plugin:3.16
mercurial:2.16
momentjs:1.1.1
multibranch-scan-webhook-trigger:1.0.9
nexus-artifact-uploader:2.13
nexus-jenkins-plugin:3.13.20211221-143401.603ba12
okhttp-api:4.9.3-105.vb96869f8ac3a
pam-auth:1.6.1
parameterized-trigger:2.43
pipeline-build-step:2.15
pipeline-github-lib:1.0
pipeline-graph-analysis:188.v3a01e7973f2c
pipeline-input-step:427.va6441fa17010
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.20
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.20
pipeline-utility-steps:2.11.0
plain-credentials:1.7
plugin-util-api:2.12.0
popper-api:1.16.1-2
popper2-api:2.11.0-1
pubsub-light:1.16
resource-disposer:0.17
role-strategy:3.2.0
run-condition:1.5
scm-api:2.6.5
scmskip:1.0.3
script-security:1118.vba21ca2e3286
slack:2.49
snakeyaml-api:1.29.1
sse-gateway:1.24
ssh-agent:1.23
ssh-credentials:1.19
ssh-slaves:1.33.0
sshd:3.1.0
structs:308.v852b473a2b8c
subversion:2.15.1
timestamper:1.15
token-macro:267.vcdaea6462991
trilead-api:1.0.13
variant:1.4
windows-slaves:1.8
workflow-aggregator:2.6
workflow-api:1108.v57edf648f5d4
workflow-basic-steps:2.24
workflow-cps:2648.va9433432b33c
workflow-cps-global-lib:552.vd9cc05b8a2e1
workflow-durable-task-step:1112.vda00e6febcc1
workflow-job:1145.v7f2433caa07f
workflow-multibranch:704.v8f039a_e2e8cf
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:804.vba10a18a1476
ws-cleanup:0.40

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20.04

### Reproduction steps

1. Bitbucket cloud side: enable hook from push
2. push a branch to the repo
3. job is not triggered (with newer version of plugin; it is triggered howver with previous version)

### Expected Results

Trigger a job on a push

### Actual Results

Actually, no jobs are triggers on branch push; only PRs are triggered

### Anything else?

Downgrade plugin to previous version to be able to trigger job on branch (and not only PRs)

**Comment by lifeofguenter** [comment]
This is confirmed also via:

* https://issues.jenkins.io/browse/JENKINS-65909
* https://issues.jenkins.io/browse/JENKINS-67502

**Comment by lifeofguenter** [comment]
@sneko Releases will always be automatic going forward.

Sometimes a faulty release will happen unfortunately, we can only improve from here :)

I hope you can understand - but we are also always looking for people who can improve the current code base <3

**Comment by sneko** [comment]
@lifeofguenter I totally understand your last point don't worry, I really appreciate your work.

Since in the `Update center` all kind of version naming exist I will probably starting now more rely on the "released X ago" to wait at least a few days/weeks.
![image](https://user-images.githubusercontent.com/8195958/148585982-726fad0d-4c21-4435-9a94-74b8e116bbcd.png)

I'm always happy to test new updates ASAP but today I just made people having lost some time due to the update and trying to figure out what was the cause. Really to balance if I should be on the first line to test updates or not 😅 

Thank you,

**Comment by sneko** [comment]
@lifeofguenter just thinking out loud, in the `Update center` it could be good if the results could have an indicator of number of issues open https://issues.jenkins.io/ **for this specific version only** (could work thanks to label maybe?)

(sorry for polluting the thread)

**Comment by mbdevpl** [comment]
I think I'm affected by this as well. Any way I can help? For now I have reverted the plugin to previous version using the "Downgrade" button like below, and indeed it seems to have fixed the issue.

![Screenshot 2022-01-10 at 10-35-49 Update Center  Jenkins](https://user-images.githubusercontent.com/1270332/148709836-c86b553b-9a82-41b0-a335-3c7e282e93c9.png)

**Comment by smirkybg** [comment]
I confirm that I'm affected by this issue too. After reverting to the previouis version, I start seeing PRs and regular branch commits to be triggering builds in Jenkins.

**Comment by dineshtrivedi** [comment]
Same here. Reverting the version has fixed the issue

**Comment by M1ke** [comment]
Can also confirm this issue started happening on our Jenkins server. Have just downgraded to v734 so will report if that resolves it.

Worth noting for anyone who wants to dig around the code and help fix that there's a suggested cause in the code here: https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/479#pullrequestreview-847587464

**Comment by lifeofguenter** [comment]
This has been reverted in the current (security) release.

**Comment by jjathman** [comment]
@lifeofguenter does release 751.vda_24678a_f781 have this fix as well?

**Comment by lifeofguenter** [comment]
@jjathman: yes :)
