### ISSUE TITLE
Branches are no longer picked up on certain PR events

### ISSUE THREAD

**Issue by pieterjanpintens** [jenkinsci/bitbucket-branch-source-plugin#544]
After updating our jenkins machines we noticed some weird behavior related to the bitbucket plugin.
We managed to resolve most of the problems but we still see one.
We are working with bitbucket cloud.

When working with PR builds everything seems to behave normally:
- PR branches appear
- They build, are linked to bitbucket etc
But when you merge the PR the project seems to loose all non PR branches (they get disabled).

The log says:

`Connecting to https://bitbucket.org using Credentials for buildoperator user in bitbucket
Repository type: Git
Looking up unifiedpost/pj-playground for branches

  0 branches were processed`

I debugged this section and i noticed that a change was made to com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource
That is starting on line 588 certain events are now assumed to provide branches.
- event instanceof HasPullRequests
- event instanceof HasRefsChangedRequest
I have the impression that these types are only valid for the bitbucket server and not for the bitbucket cloud.
As a result the call always seems to assume there are no branches and the filtering will mark all branches as disabled.

I think we should also check the types of the event after checking if the event is null so that the old behavior is used for bitbucket cloud. 

### Reproduction steps

Set up bitbucket plugin against bitbucket cloud
Add a multi branch project that works with PR builds

### Expected Results

Branches should remain valid after a PR merge

### Actual Results

Branches get disabled

**Comment by pieterjanpintens** [comment]
PR for this https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/545

**Comment by KalleOlaviNiemitalo** [comment]
interface HasPullRequests was added in <https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/445>.

**Comment by lifeofguenter** [comment]
Is this still happening on the current release?
