### ISSUE TITLE
First commit on PR doesn't trigger Jenkins pipeline

### ISSUE THREAD

**Issue by mBouamama** [jenkinsci/bitbucket-branch-source-plugin#555]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.319.2
OS: Linux - 5.4.172-90.336.amzn2.x86_64
---
ace-editor:1.1
apache-httpcomponents-client-4-api:4.5.13-1.0
authentication-tokens:1.4
aws-java-sdk:1.12.131-302.vbef9650c6521
aws-java-sdk-cloudformation:1.12.131-302.vbef9650c6521
aws-java-sdk-codebuild:1.12.131-302.vbef9650c6521
aws-java-sdk-ec2:1.12.131-302.vbef9650c6521
aws-java-sdk-ecr:1.12.131-302.vbef9650c6521
aws-java-sdk-ecs:1.12.131-302.vbef9650c6521
aws-java-sdk-elasticbeanstalk:1.12.131-302.vbef9650c6521
aws-java-sdk-iam:1.12.131-302.vbef9650c6521
aws-java-sdk-logs:1.12.131-302.vbef9650c6521
aws-java-sdk-minimal:1.12.131-302.vbef9650c6521
aws-java-sdk-ssm:1.12.131-302.vbef9650c6521
aws-secrets-manager-credentials-provider:0.5.6
aws-secrets-manager-secret-source:0.0.2
azure-ad:1.2.3
azure-commons:1.1.1
basic-branch-build-strategies:1.3.2
bitbucket-filter-project-trait:1.0
bootstrap4-api:4.6.0-3
bootstrap5-api:5.1.3-4
bouncycastle-api:2.25
branch-api:2.7.0
build-user-vars-plugin:1.8
caffeine-api:2.9.2-29.v717aac953ff3
checks-api:1.7.2
cloudbees-bitbucket-branch-source:751.vda_24678a_f781
cloudbees-disk-usage-simple:0.10
cloudbees-folder:6.17
command-launcher:1.2
configuration-as-code:1.55.1
copyartifact:1.46
credentials:2.6.2
credentials-binding:1.27.1
dependency-check-jenkins-plugin:5.1.2
display-url-api:2.3.5
docker-commons:1.18
docker-java-api:3.1.5.2
docker-plugin:1.2.6
docker-workflow:1.26
durable-task:493.v195aefbb0ff2
echarts-api:5.2.2-2
extended-read-permission:3.2
font-awesome-api:5.15.4-5
git:4.10.3
git-client:3.11.0
git-server:1.10
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-1.0
jackson2-api:2.13.1-246.va8a9f3eaf46a
javax-activation-api:1.2.0-2
javax-mail-api:1.6.2-5
jaxb:2.3.0
jdk-tool:1.0
job-dsl:1.78.3
jquery3-api:3.6.0-2
jsch:0.1.55.2
junit:1.53
kubernetes:1.31.3
kubernetes-client-api:5.11.2-182.v0f1cf4c5904e
kubernetes-credentials:0.9.0
lockable-resources:2.13
mailer:408.vd726a_1130320
matrix-auth:2.6.6
matrix-project:1.20
metrics:4.0.2.8.1
momentjs:1.1.1
pipeline-build-step:2.15
pipeline-graph-analysis:188.v3a01e7973f2c
pipeline-input-step:446.vf27b_0b_83500e
pipeline-milestone-step:1.3.2
pipeline-model-api:1.9.3
pipeline-model-definition:1.9.3
pipeline-model-extensions:1.9.3
pipeline-rest-api:2.21
pipeline-stage-step:291.vf0a8a7aeeb50
pipeline-stage-tags-metadata:1.9.3
pipeline-stage-view:2.21
plain-credentials:1.8
plugin-util-api:2.13.0
popper-api:1.16.1-2
popper2-api:2.11.2-1
prometheus:2.0.10
saml:2.0.9
scm-api:595.vd5a_df5eb_0e39
script-security:1131.v8b_b_5eda_c328e
simple-theme-plugin:0.7
slack:2.46
snakeyaml-api:1.29.1
sonar:2.14
ssh-agent:1.24.1
ssh-credentials:1.19
ssh-slaves:1.33.0
sshd:3.1.0
structs:308.v852b473a2b8c
timestamper:1.16
token-macro:267.vcdaea6462991
trilead-api:1.0.13
variant:1.4
workflow-aggregator:2.6
workflow-api:1136.v7f5f1759dc16
workflow-basic-steps:2.24
workflow-cps:2648.va9433432b33c
workflow-cps-global-lib:2.21
workflow-durable-task-step:1121.va_65b_d2701486
workflow-job:1145.v7f2433caa07f
workflow-multibranch:706.vd43c65dec013
workflow-scm-step:2.13
workflow-step-api:622.vb_8e7c15b_c95a_
workflow-support:813.vb_d7c3d2984a_0
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins: 2.319.2

OS: Linux - 5.4.172-90.336.amzn2.x86_64
On Kubernetes, aws kubernetes engine
Kubernetes version: v1.21
agent version: jenkins/inbound-agent:4.6-1

### Reproduction steps

<details>
  <summary>MultiBranch Pipeline Configuration</summary>

![image](https://user-images.githubusercontent.com/57527739/152795496-c8ee2eb6-d4d7-4769-8a32-19b4dd39197a.png)
![image](https://user-images.githubusercontent.com/57527739/152795557-990401c0-b403-4714-9446-93c87d16fa95.png)
![image](https://user-images.githubusercontent.com/57527739/152795708-ff258876-a5ca-4548-94de-9e3a647f0333.png)
![image](https://user-images.githubusercontent.com/57527739/152795799-aa73837f-381d-4980-9e69-720f575ccfcd.png)
</details>
<details>
<summary>Bitbucket WebHook conf</summary>

![image](https://user-images.githubusercontent.com/57527739/152796394-c20523d5-0ff8-4871-8953-415039af6c3d.png)

</details>

1. Step 1: Run with same conf on jenkins/bitbucket
2. Step 2: create a new branch on our bitbucket repo
3. Step 3: commit something on our new branch
4. Step 4: create PR on bitbucket with merging our new branch into master branch

### Expected Results

1. bitbucket send PR created to jenkins
2. Jenlkins trigger a new build on PR branch section

### Actual Results

1. bitbucket send PR created to jenkins
2. 0 build is triggered by Jenkins

### Anything else?

<details>
  <summary>jenkins logs</summary>

```
Looking up xxxxxx/xxxxxxxxx for pull requests
Checking PR-93 from up xxxxxx/xxxxxxxxxr and branch feature/xxxxxxxxx
      ‘Jenkinsfile’ found
    Met criteria
Changes detected: PR-93 (null → 9095e96dbd7d)
No automatic build triggered for PR-93
```

I noticed when you commit again the job is triggered.

**Comment by lifeofguenter** [comment]
Can you add “discover change requests” under build strategies and see if that works better?

The log _discovers_ the PR but has no build instruction.

**Comment by mBouamama** [comment]
Hi,
Thx a lot for the quick response.
i added discover change requests but nothing happens, i got same problem again.
Regards

<details>
<summary>new configuration with “discover change requests” under build strategies</summary>

![image](https://user-images.githubusercontent.com/57527739/153036982-1599421a-a35d-44a9-a556-fc8b3a4674e0.png)

</details>

<details>
<summary>logs</summary>

 ```
 8 branches were processed
Looking up xxx/xxxxxxxx for pull requests
Checking PR-97 from xxx/xxxxxxxx and branch jenkins3
      ‘Jenkinsfile’ found
    Met criteria
No automatic build triggered for PR-97

  1 pull requests were processed (query completed)
```
</details>

**Comment by KalleOlaviNiemitalo** [comment]
"All Strategies Match" seems the wrong choice here, as it requires that the same job is for a named branch AND for a change request.

**Comment by mBouamama** [comment]
wow so fast, ok i see, i added new configuration, when its deployed i will test
regards
