### ISSUE TITLE
Support to Azure Key Vault plugin

### ISSUE THREAD

**Issue by SirNeo** [jenkinsci/bitbucket-branch-source-plugin#559]
### What feature do you want to see added?

Currently the bitbucket branch source plugin doesn't allow select a Key Vault credential when we are creating a new Bitbucket Team/Project pipeline. I suggest that the plugin to allow select a Key Vault credential too. Instead we save the credentials in Jenkins, we will store them in Azure Key Vault
![evidence1](https://user-images.githubusercontent.com/5236294/154055415-31bb4e1e-b0f8-4f9c-9299-951786d7302d.png)
![evidence2](https://user-images.githubusercontent.com/5236294/154055417-65d87ab5-66d6-427d-89b8-01d236abb8ab.png)
.

**Comment by nfalco79** [comment]
The plugin use StandardUsernameCredential that is what Git plugin requires.
If you install the Azure Key Vault plugin and configure a AzureUsernamePasswordCredentials it should be available in the list.
