### ISSUE TITLE
Bitbucket Branch Source Smart Mirror Support 

### ISSUE THREAD

**Issue by Maxo112** [jenkinsci/bitbucket-branch-source-plugin#592]
### What feature do you want to see added?

Since we have large repos on our Bitbucket Server Enterprise environment and have various sites. Would be my wish in Jenkins to select which smart mirror to pull the repository from. Unfortunately, the Jenkins is in a completely different location. 

Should it be possible for Jenkins to download directly from the smart mirror we would have an improvement in time by several 100 percent. 

Unfortunately, as soon as I try to add the Smart mirror as a Bitbucket server, I get the error. 

![image](https://user-images.githubusercontent.com/38752564/165264485-5ea70ac2-fc6e-4ca5-aa68-232891252f50.png)

### Upstream changes

I don't want to use the GIT plugin, it must explicitly support the Branch Source plugin to support Bitbucket Smart Mirror.

**Comment by KalleOlaviNiemitalo** [comment]
The [Bitbucket Server Integration](https://plugins.jenkins.io/atlassian-bitbucket-server-integration/) plugin supports cloning from mirrors. OTOH, it doesn't yet support pull requests, so switching to it is not trivial.

**Comment by Maxo112** [comment]
@KalleOlaviNiemitalo  That's the problem it doesn't support PRs that's my biggest problem with the plugin :(

**Comment by bsnuggs1** [comment]
@Maxo112 - The [Bitbucket Server Integration](https://plugins.jenkins.io/atlassian-bitbucket-server-integration/) plugin supports PRs now...but unfortunately, not in the way you'd expect.  It can only trigger re-scans in Jenkins for the source branch.  It doesn't actually attempt to do a merge operation and run a build against the result.
