### ISSUE TITLE
Auto webhook creation broken for Bitbucket 7.x

### ISSUE THREAD

**Issue by dsakilesh** [jenkinsci/bitbucket-branch-source-plugin#615]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins version -  2.332.3
Plugin version - 773.v4b_9b_005b_562b
Bitbucket server and version - v7.21.0
  ```
After installing the latest version of the bitbucket branch source plugin, the webhooks are not getting created automatically upon the jenkins job creation.

Scan multibranch pipeline does not give any error. And bitbucket logs are clean.

We are using the NATIVE implementation for our jenkins. It was working fine from last 2.5 years. Is there any change in the behavior of the plugin in the recent versions of bitbucket branch source plugin.

PFA the screenshot of plugin configuration in Jenkins.

Thank you!
</details>
![Bitbucketv7-Native](https://user-images.githubusercontent.com/58210462/175471390-fce38cea-bcfb-44e6-b66a-be9027bb190f.png)

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux - Ubuntu

### Reproduction steps

Step1: Install the latest version of bitbucket branch source plugin
Step2: Create the Multibranch jenkins pipeline job

### Expected Results

Webhook will be created in Bitbucket repository

### Actual Results

Webhook not created in Bitbucket repository

**Comment by nfalco79** [comment]
Do you have this issue with latest version of the plugin?
