### ISSUE TITLE
GIT_COMMIT, GIT_URL, and other info is not returned in scm object or environment variables

### ISSUE THREAD

**Issue by red8888** [jenkinsci/bitbucket-branch-source-plugin#633]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

linux

### Reproduction steps

1. Build a pipeline with the bitbucket plugin

### Expected Results

I'm having trouble finding this in documentation anywhere, but from what I have seen I should be getting environment variables like GIT_COMMIT and GIT_URL populated OR that info should be available in the scm object.

### Actual Results

Scm object does not include git commit and I don't have any env vars that have this info.

### Anything else?

I just want to confirm if this is expected behavior. I don't want to have to shell out to git to get the commit id, url, commit message, commit user, etc.

**Comment by andham** [comment]
When using the Bitbucket Branch Source plugin, env.GIT_COMMIT and env.GIT_URL is available in a declarative pipeline. I believe this actually set outside of the plugin. However, it seems it's not available in a scripted pipeline or I'm doing some silly error in the pipeline.

**Comment by nfalco79** [comment]
we use scripted pipeline, with latest version (at least) both env variables are populated correctly:
```
    node() {
        stage ('Build') {
            gitCommands.checkout()
            echo env.GIT_COMMIT
            echo env.GIT_URL
        }
    }
```

> Commit message: "BUILD test"
First time build. Skipping changelog.
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
d31df3425c5bacc656a2910689b61bef863091b6
[Pipeline] echo
https://nfalco@bitbucket.org/nfalco/xxxxxx-backend.git
