### ISSUE TITLE
Please share more information on behaviour of WebhookRegistrationTrait and improve documentation for this trait

### ISSUE THREAD

**Issue by amezentzev** [jenkinsci/bitbucket-branch-source-plugin#635]
### Describe your use-case which is not covered by existing documentation.

Could you share more info and update docs regarding WebhookRegistrationTrait behaviour?
Right now it's unclear if setting this to "DISABLE" will effectively completely disable webhooks registration in bitbucket in all cases (on job addition using jcasc, on jenkins startup, on job update using jcasc).

**Comment by pparth** [comment]
Any updates here guys?

**Comment by nfalco79** [comment]
Documentation has been updated. Anyway traits disable the automatic registration for the multibranch project/organization folder. Hook processor remain active, this mean that you have add webhook manually for each repository.
