### ISSUE TITLE
OAuth checkout credentials

### ISSUE THREAD

**Issue by tn-osimis** [jenkinsci/bitbucket-branch-source-plugin#707]
### Describe your use-case which is not covered by existing documentation.

The current user guide mentions:

> Checkout Credentials: Credentials used to check out sources once the repository, branch or pull request is discovered. HTTP Basic Authentication, SSH and OAuth credentials are supported. If not set then Scan Credentials are used.

However, as of Jenkins v2.405 with the Bitbucket branch source plugin v800.va_b_b_9a_a_5035c1, the "Checkout credentials" field does not appear anymore.

I suspected/hoped that it would now be available as a behavior (similar to #671), however the only relevant behavior I can see is for checking out (cloning/fetching) via SSH -- not HTTPS with OAuth.

Ideally the documentation should:

- Be updated to reflect the current state of things,
- If the feature is still available, it should explain how to use it/where to find the option,
- If there was a regression, it should mention it explicitly so as to stop users from wasting their time looking for it.

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/63c7f213a40905102e522bb1163795e950e3603d/docs/USER_GUIDE.adoc

**Comment by nfalco79** [comment]
The OAuth credential is supported and is documented [here](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/docs/USER_GUIDE.adoc#credentials-configuration)
