### ISSUE TITLE
Remove mentions of Checkout Credentials

### ISSUE THREAD

**Issue by nilsmahlstaedt** [jenkinsci/bitbucket-branch-source-plugin#715]
### Describe your use-case which is not covered by existing documentation.

The current docs describe two types of credentials: Scan Credentials and Checkout Credentials.
The later seems to be no longer be part of the plugin and is no longer visible in the UI.

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

User Guide Section in Question: https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/docs/USER_GUIDE.adoc#credentials-configuration

**Comment by TeCHiScy** [comment]
> The "Checkout Credentials" UI was removed in commit [a4c6bf3](https://github.com/jenkinsci/bitbucket-branch-source-plugin/commit/a4c6bf39b83168ff62fc622bd4084ef90cf810c0).
> 
> A similar feature is still available. In a multibranch pipeline project, configure the "Bitbucket" branch source. Under the "Behaviours" heading, click "Add", choose "Checkout over SSH" from the menu, and select an SSH key credential for the checkout. The branch source will still use HTTP for other purposes.

Hi Kalle, thanks for the clarification. Now I can use `Checkout over SSH` behaviour to specify a ssh credential which is different from the access token I used in branch scan. And it's would be nice to mention the alternative method in the document, in case of any misleading.
