### ISSUE TITLE
More than 200 branches - build stuck

### ISSUE THREAD

**Issue by swolf** [jenkinsci/bitbucket-branch-source-plugin#721]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

Jenkins: 2.401.1
OS: Windows Server 2019 - 10.0
Java: 11.0.19 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)

cloudbees-bitbucket-branch-source:805.v7f97d29dc0f5

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

OS: Windows Server 2019 - 10.0 (controller, it never gets to the agent)

### Reproduction steps

1. Have a bitbucket repository with more than 200 branches
2. Have a default branch called 'master' and try to build it

### Expected Results

Build is running without any issues.

### Actual Results

Build is stuck at the very beginning when it is querying the branches from bitbucket. The only output would be for example: "Branch event" and after a few hours when nothing further happened an error is thrown.

### Anything else?

We further investigated the issue and it seems to be a problem with the pagination of the branches. When we have less than 200 branches (default page size is hardcoded to 200: https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/7f97d29dc0f506a7ba037262d51cc386911caabb/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java#L160) it is working as expected. 

A REST query to bitbucket with the following GET paramaters is the starting point: mybitbucket.com/rest/api/1.0/projects/TS/repos/myrepo/branches?start=0&limit=200

This works as expected. Looking at the code it seems to try to go to the next page:

https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/7f97d29dc0f506a7ba037262d51cc386911caabb/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java#L871

Apparently, the last page is never reached and bitbucket is flooded with requests. Similar requests like this one are done every 20ms until the job is failing (bitbucket access log):

x.x.x.x | https | xxx | my_jenkins_user | 2023-06-13 07:31:18,875 | "GET /rest/api/1.0/projects/TS/repos/myrepo/branches HTTP/1.1" | "" "Apache-HttpClient/4.5.14 (Java/11.0.19)" | 200 | 0 | 7018 | - | 29 | - |

**Comment by swolf** [comment]
I got the logging enabled in the jenkins with this logger: org.apache.http.wire

Then I see the following requests flooding bitbucket (always the same):

http-outgoing-3216760 >> "GET /rest/api/1.0/projects/myproject/repos/myrepo/branches?filterText=master HTTP/1.1[\r][\n]"

It seems that there are no pagination GET Parameters (limit and start). Bitbucket has a default limit of 25 entries and there are more than 25 branches containing the word master. This is probably the issue we are facing.

It seems that the url does not contain the GET parameters for limit and start at all (I am not so familiar with this Handy URI Templates):

https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/7f97d29dc0f506a7ba037262d51cc386911caabb/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/server/client/BitbucketServerAPIClient.java#L635

**Comment by stoenpav** [comment]
Hello, having the same problem, will there be a fix for this issue ?
