### ISSUE TITLE
Add support for Project and Workspace Access Token for Bitbucket Cloud

### ISSUE THREAD

**Issue by reuben-james** [jenkinsci/bitbucket-branch-source-plugin#748]
### What feature do you want to see added?

The docs say the following credential types are supported: 
`Scan Credentials: Credentials used to access Bitbucket API in order to discover repositories, branches and pull requests. If not set then anonymous access is used, so only public repositories, branches and pull requests are discovered and managed. HTTP Basic Authentication, Access Token and OAuth credentials are supported.`

Please add support for a Workspace Token (NOT a project-specific Access Token), as described in Bitbucket docs here: https://support.atlassian.com/bitbucket-cloud/docs/workspace-access-tokens/ 

Bitbucket docs describe how these can be used in-place of legacy username:password format here: https://support.atlassian.com/bitbucket-cloud/docs/using-workspace-access-tokens/ 

So in theory they should work in the same way that OAuth tokens do by setting `jenkins:credentials:username` to `x-token-auth`, however, this currently doesn't work. 

Attempting to configure this in Jenkins for Respository Sources > Bitbucket Team/Project under an Organisational Folder does not successfully scan the bitbucket project and retrieve any repos/branches/PRs.

**Comment by Jonny-vb** [comment]
I can get a workspace access token to work for scanning by using a secret text credential set to the token, but that doesn't then work for checking out repos.
This could be worked around if the separate checkout credentials option was still present, but it looks like we just currently can't use workspace access tokens

**Comment by fran-pastor** [comment]
> I can get a workspace access token to work for scanning by using a secret text credential set to the token, but that doesn't then work for checking out repos. This could be worked around if the separate checkout credentials option was still present, but it looks like we just currently can't use workspace access tokens

same behaviour for us
We can provide "Checkout over SSH" in advanced preferences but we prefer to user username/pass for git operations, and workspace access token for discover repos

**Comment by jbowers-celartem** [comment]
We are looking for this as well.  Using user-based app passwords for build systems isn't ideal

**Comment by eightnoneone** [comment]
@reuben-james I'm facing the same/similar issues. I was confused by your parenthetical "(NOT a project-specific Access Token)" as I don't see that this scope of token works with Cloud today. Did I miss understand? 

Is the need specifically "Workspace Access Tokens" or really _any_ Access Token within Bitbucket Cloud? The plugin [docs](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/docs/USER_GUIDE.adoc) mention:

> Access Token
> The plugin can make use of a personal access token (**Bitbucket Server only**) instead of the standard username/password.

Which to mean means Cloud has no support for Access Tokens at any level (Workspace, Project, Repository). I'd very much like to have Project-level Access Tokens included, if that doesn't change the definition of your request.

**Comment by spriya757** [comment]
Hi, 

Bitbucket Cloud supports Repository, project, and workspace access tokens. Also, recently launched scaled rate limits for paid plans - https://bitbucket.org/blog/introducing-scaled-rate-limits-for-bitbucket-cloud-api. It would be really helpful to have the plugin support access tokens to avoid rate limiting issues.

**Comment by nfalco79** [comment]
I expect access token works as OAuth credential. Unfortunally I can test this because Workspace Access Token is a premium feature that my company does not have. So please post any logs that could help why configuring as the same of OAuth2 credentials does not work

**Comment by divakumaran** [comment]
Like to get the feature developed and available 

This plugin only accepts app password or OAuth credentials and doesn't support access tokens yet this is blocking us

**Comment by nfalco79** [comment]
This is the configuration for repository Access Token:
![Image](https://github.com/user-attachments/assets/61b37ac9-d6be-4998-88ea-50866d58e37e)

Since there is no very specific documentation for Bitbucket Cloud than [this](https://support.atlassian.com/bitbucket-cloud/docs/workspace-access-tokens/) or [this](https://support.atlassian.com/bitbucket-cloud/docs/project-access-tokens/)
Is there someone that could post me the same configuration for project and workspace access token (you can delete immediately).
I need to know the instruction (as above) of use token in REST API or in git clone command and so on.

Test done with repository Access Token works

**Comment by Jonny-vb** [comment]
Hi @nfalco79 - there is some additional documentation around using workspace access tokens here: https://support.atlassian.com/bitbucket-cloud/docs/using-workspace-access-tokens/

**Comment by nfalco79** [comment]
Thanks @Jonny-vb. I did not found that page and documentation neither on the REST API page. It's the same procedure for personal access token so I think it would already work with the code in the PR #934 
I have to document that user.email is required for push operation and can be set with the appropriate trait. Normally is not required but it is using git from CLI.

**Comment by Jonny-vb** [comment]
That would be great if so. Thanks for looking at this - it's nice to see this plugin getting some love recently!
