### ISSUE TITLE
Bitbucket build-status API Deprecated

### ISSUE THREAD

**Issue by rickemch** [jenkinsci/bitbucket-branch-source-plugin#778]
### Jenkins and plugins versions report

<details>
Per https://community.atlassian.com/t5/Bitbucket-questions/Why-is-the-required-builds-merge-check-still-failing-after-a/qaq-p/2230801 , the Bitbucket REST API /rest/api/1.0/build-status/latest/commits/{commitId} is deprecated. It does not work to mark a specific Jenkins build in Bitbucket. This results in "Required Builds" in Bitbucket never being marked as passed.

The Branch Source Plugin needs to be updated to use the new Bitbucket API:   /rest/api/latest/projects/{projectKey}/repos/{repositorySlug}/commits/{commitId}/builds

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

Enable Required Builds in Bitbucket for a Jenkins multibranch pipeline job.
Pass the Jenkins multibranch pipeline job. 
Verify that Required Builds in Bitbucket still indicates needing a pass on the multibranch pipeline job for the commit.

### Expected Results

Required Builds in Bitbucket is satisfied by a pass on the Jenkins multibranch pipeline job for the commit.

### Actual Results

Required Builds in Bitbucket still indicates needing a pass on the multibranch pipeline job for the commit.

**Comment by nfalco79** [comment]
Close as duplicated
