### ISSUE TITLE
Webhook creation no longer working with Bitbucket server v8.8

### ISSUE THREAD

**Issue by jackiedaytonaAZ** [jenkinsci/bitbucket-branch-source-plugin#803]
### Jenkins and plugins versions report

<details>
  <summary>Windows</summary>

  ```
Windows Jenkins agent with Bitbucket server v8.8.2
  ```
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows

### Reproduction steps

Turn on the `Manage hooks` option either at the global level or at the pipeline level.

### Expected Results

Multibranch pipelines will automatically register webhooks in Bitbucket repositories

### Actual Results

404 error: 

java.io.FileNotFoundException: URL: /rest/webhook/1.0/projects/PROJECT/repos/REPO/configurations

### Anything else?

It appears Atlassian may have changed the webhook endpoints starting with v8.8:
https://developer.atlassian.com/server/bitbucket/reference/api-changelog/

Based on my testing it appears that the /rest/webhook/1.0 endpoint may no longer exist?

**Comment by twingg** [comment]
We've tested bitbucket 8.14 and bb branch source plugin 805.v7f97d29dc0f5
Webhook creation **worked** for organization folders and multibranch project.
bitbucket server configuration in jenkins set to v7 and later
