### ISSUE TITLE
IllegalStateException: "Can't find clone link for protocol HTTP" after plugin update

### ISSUE THREAD

**Issue by melorbany** [jenkinsci/bitbucket-branch-source-plugin#804]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.426.3
OS: Linux - 4.14.330-250.540.amzn2.x86_64
Java: 11.0.22 - Red Hat, Inc. (OpenJDK 64-Bit Server VM)
---
bitbucket:241.v6d24a_57f9359
cloudbees-bitbucket-branch-source:871.v28d74e8b_4226
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Amazon Linux 2
Jenkins: 2.426.3
OS: Linux - 4.14.330-250.540.amzn2.x86_64

### Reproduction steps

1. Install/update the `bitbucket-branch-source-plugin` to the latest version.
2. Configure a Multibranch Pipeline job with a Bitbucket repository.
3. Trigger the branch indexing job.
4. Observe the failure with the IllegalStateException in the Jenkins system logs.

### Expected Results

Jenkins should complete branch indexing for a Bitbucket repository without errors. The plugin should find the clone link for the HTTP protocol properly and allow for the normal operation of Jenkins processes, such as checking out the repository and triggering builds based on source code changes.

### Actual Results

 Finished branch indexing. Indexing took 1.9 sec
FATAL: Failed to recompute children of  _[job/project name]_
java.lang.IllegalStateException: Can't find clone link for protocol HTTP
at com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.lambda$getCloneLink$1(BitbucketGitSCMBuilder.java:313)
at java.base/java.util.Optional.orElseThrow(Optional.java:408)
at com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.getCloneLink(BitbucketGitSCMBuilder.java:313)
at com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.withPrimaryRemote(BitbucketGitSCMBuilder.java:300)
at com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.withBranchRemote(BitbucketGitSCMBuilder.java:293)
at com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.withBitbucketRemote(BitbucketGitSCMBuilder.java:199)
at com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.withCloneLinks(BitbucketGitSCMBuilder.java:130)
at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.build(BitbucketSCMSource.java:1033)
at jenkins.scm.api.SCMSource.build(SCMSource.java:934)
at jenkins.branch.MultiBranchProject.newBranch(MultiBranchProject.java:556)
at jenkins.branch.MultiBra" how to get the current URL"

### Anything else?

- Using Bitbucket Cloud.
- Job SCM Configuration is valid. 
- Downgrading to the previous version of the `bitbucket-branch-source-plugin` has temporarily resolved the indexing issue, allowing Jenkins to function as expected.

**Comment by madav-tech** [comment]
@melorbany Could you explain briefly (with images preferably) how you downgraded the plugin? I'm encountering the same issue but the "downgrade" button is greyed out

**Comment by melorbany** [comment]
> @melorbany Could you explain briefly (with images preferably) how you downgraded the plugin? I'm encountering the same issue but the "downgrade" button is greyed out

I faced the same issue while downgrading. What worked for me was to check for any dependent plugins and uninstall them (**You can find these by hovering over or clicking the 'Uninstall' button** ). After removing the dependencies, the 'Downgrade' button should become active, and you can proceed with the downgrade.

**Comment by boussaffawalid** [comment]
same issue here

**Comment by intef0** [comment]
Same issue +1

**Comment by ediwo1** [comment]
I have the issue.

**Comment by EdHUtilifeed** [comment]
Same issue this morning. None of our devs could get any multibranch pipeline to run. We did a manual downgrade with the cli (firtst had to delete the plugin then run the command` jenkins-plugin-cli --plugins cloudbees-bitbucket-branch-source:866.vdea_7dcd3008e) ` That solved the issue for now.

**Comment by madav-tech** [comment]
For anyone stuck on how to downgrade the plugin without uninstalling anything, see this:
https://medium.com/@minaxijoshi3101/downgrade-a-plugin-version-in-jenkins-without-internet-28580603732b

I followed it and the downgrade was successful without uninstalling any plugin

**Comment by ediwo1** [comment]
There is a simple solution from Web UI. Download previous version of cloudbees-bitbucket-branch-source.hpi and upload:

<img width="581" alt="image" src="https://github.com/jenkinsci/bitbucket-branch-source-plugin/assets/86931335/1b295196-7662-4c0c-baca-f65ee3c5ecba">

Restart Jenkins.

**Comment by 0pilatos0** [comment]
Having the same issue here, downgrading to a older version fixes the issue for now indeed

**Comment by lifeofguenter** [comment]
@andrey-fomin related to: https://github.com/jenkinsci/bitbucket-branch-source-plugin/pull/796 ?

**Comment by andrey-fomin** [comment]
Yes. Looks like it's related with #796. I'll check.

**Comment by cbolson1** [comment]
I'm still seeing this problem, even with the latest version [888.v8e6d479a_1730](https://updates.jenkins.io/download/plugins/cloudbees-bitbucket-branch-source/888.v8e6d479a_1730/cloudbees-bitbucket-branch-source.hpi)

I verified that this worked on release 866.vdea_7dcd3008e, but it broke on release 871.v28d74e8b_4226.

I'm happy to open a new issue for my problem if needed, but it looks like the exact same failure signature as this one:

```
ERROR: [Mon Jul 29 15:05:11 GMT 2024] Could not fetch branches from source 354743ac-03b3-4fe9-aeca-236e377ad636
[Mon Jul 29 15:05:11 GMT 2024] Finished branch indexing. Indexing took 4.5 sec
FATAL: Failed to recompute children of Sidecar
java.lang.IllegalStateException: Can't find clone link for protocol HTTP
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.lambda$getCloneLink$1(BitbucketGitSCMBuilder.java:313)
```
