### ISSUE TITLE
Error after Jenkins upgrade with Bitbucket Branch Source Plugin – CannotResolveClassException: repositoryType

### ISSUE THREAD

**Issue by Maxo112** [jenkinsci/bitbucket-branch-source-plugin#907]
### Jenkins and plugins versions report

**Problem:**
After upgrading the Bitbucket Branch Source Plugin to version 906.vedf430cb_4481, Jenkins displays a warning about deprecated data:
`CannotResolveClassException: repositoryType - org.jenkinsci.plugins.workflow.job.WorkflowJob
`

In the config.xml for multiple repositories (around 3000), the following entry appears:
`<target>
    <name>10.9.x-release</name>
    <repositoryType>GIT</repositoryType>
</target>
`

### What Operating System are you using (both controller, and any agents involved in the problem)?

System Information
Jenkins Version: 2.462.3
Bitbucket Branch Source Plugin: 906.vedf430cb_4481

### Reproduction steps

1. Upgrade Jenkins with the updated Bitbucket Branch Source Plugin.
2. Restart Jenkins and check for deprecated data.
3. The error appears for projects with the <repositoryType> tag in their config.xml files as shown above.

### Expected Results

**Expected Behavior**
Existing configurations should remain compatible without requiring manual removal of the <repositoryType> tag from every repository configuration file.

### Actual Results

**Actual Behavior**
Jenkins throws CannotResolveClassException for repositoryType, indicating an issue with the configuration after the plugin update.

**Comment by nfalco79** [comment]
May I have the config.xml part for the bitbucket configuration? I need to know how to fix serialization

**Comment by nfalco79** [comment]
repositoryType field has been removed with commit [6e501b97d2dc8067444729393faf58b142b574a3](https://github.com/jenkinsci/bitbucket-branch-source-plugin/commit/6e501b97d2dc8067444729393faf58b142b574a3). But the field was transient since 7 year and xstream should not serialize it

**Comment by Maxo112** [comment]
@nfalco79 

[config.xml - Copy.txt](https://github.com/user-attachments/files/17676938/config.xml.-.Copy.txt)

Unfortunately there is nothing in the logs, I only have a screenshot of the page where the outdated data can be found. 

![Image](https://github.com/user-attachments/assets/24a983a3-e7bf-4238-b049-28095c73006f)

**Comment by nfalco79** [comment]
Thanks a lot, I've got other example:
```
<flow-definition plugin="workflow-job@1436.vfa_244484591f">
  <actions/>
  <displayName>master</displayName>
  <keepDependencies>false</keepDependencies>
  <properties>
    <org.jenkinsci.plugins.workflow.multibranch.BranchJobProperty plugin="workflow-multibranch@795.ve0cb_1f45ca_9a_">
      <branch plugin="branch-api@2.1178.v969d9eb_c728e">
        <sourceId>com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMNavigator::https://bitbucket.org::workspace::repo_slug</sourceId>
        <head class="com.cloudbees.jenkins.plugins.bitbucket.BranchSCMHead" plugin="cloudbees-bitbucket-branch-source@888.v8e6d479a_1730">
          <name>master</name>
          <repositoryType>GIT</repositoryType>
        </head>
```
repositoryType is not used and set always to GIT, Discard Unreadable Data operation is safe.

**Comment by Maxo112** [comment]
@nfalco79 Thank you Sir, So if I remove the data it will not delete the complete config.xml data but only the entry `repositoryType ` ?

**Comment by nfalco79** [comment]
Yes, "Discard Unreadable Data" removes the unknow (unreadable) data from any config.xml. You can also dismiss the warning but I can ensure that remove repositoryType is safe.
This is the official documentation: https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/client-and-managed-controllers/unreadable-data
This happens when you disable a plugin for example that mean all configured data in config.xml are no more valid, so it's your choice keep them (in caso you want enable that plugin again) or discard. Other use case (like this) a plugin remove useless attributes from class used to configure the job behaviour.
