### ISSUE TITLE
Can't get repository names dropdown when using workspace token authentication in Bitbucket Cloud

### ISSUE THREAD

**Issue by zudljk** [jenkinsci/bitbucket-branch-source-plugin#917]
### Jenkins and plugins versions report

When using a workspace access token, Bitbucket Cloud requires the use of an "Authorization: Bearer <token>" header.

However, in the job configuration, the Bitbucket Branch Source plugin only supports Basic authentication when fetching the list of repositories.

Since this fails due to the above requirement from Bitbucket Cloud, the dropdown for the repository name stays empty, making it impossible to complete the configuration.

The dropdown also doesn't allow entering the repo name manually.

Using the "Checkout via SSH" behavior doesn't help because it doesn't apply to the fetching of the repo list.

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.479.1
OS: Linux - 5.14.21-150500.55.59-default
Java: 17.0.13 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
Office-365-Connector:5.0.0
active-directory:2.37
analysis-model-api:12.9.1
ansicolor:1.0.5
ant:511.v0a_a_1a_334f41b_
antisamy-markup-formatter:162.v0e6ec0fcfcf6
any-buildstep:14.ve115ec1484f0
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.4-124.v31e2987e48f4
asm-api:9.7.1-97.v4cc844130d97
atlassian-bitbucket-server-integration:4.1.1
atlassian-jira-software-cloud:2.0.15
authentication-tokens:1.119.v50285141b_7e1
basic-branch-build-strategies:81.v05e333931c7d
bitbucket:254.v9d8ec33a_7a_42
bitbucket-build-status-notifier:1.4.2
bitbucket-oauth:0.13
bitbucket-pullrequest-builder:1.5.0
bitbucket-push-and-pull-request:3.1.3
blueocean:1.27.16
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.27.16
blueocean-commons:1.27.16
blueocean-config:1.27.16
blueocean-core-js:1.27.16
blueocean-dashboard:1.27.16
blueocean-display-url:2.4.3
blueocean-events:1.27.16
blueocean-git-pipeline:1.27.16
blueocean-github-pipeline:1.27.16
blueocean-i18n:1.27.16
blueocean-jira:1.27.16
blueocean-jwt:1.27.16
blueocean-personalization:1.27.16
blueocean-pipeline-api-impl:1.27.16
blueocean-pipeline-editor:1.27.16
blueocean-pipeline-scm-api:1.27.16
blueocean-rest:1.27.16
blueocean-rest-impl:1.27.16
blueocean-web:1.27.16
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
branch-api:2.1200.v4b_a_3da_2eb_db_4
build-pipeline-plugin:2.0.2
build-timeout:1.33
build-user-vars-plugin:176.vb_9c7907fd524
built-on-column:1.4
caffeine-api:3.1.8-133.v17b_1ff2e0599
cctray-xml:97.vb_8e5e9f9b_464
checks-api:2.2.1
chromedriver:1.2
cloud-stats:336.v788e4055508b_
cloudbees-bitbucket-branch-source:910.v5b_9b_36e0379e
cloudbees-folder:6.955.v81e2a_35c08d3
collapsing-console-sections:1.10.0
command-launcher:116.vd85919c54a_d6
commons-compress-api:1.26.1-2
commons-httpclient3-api:3.1-3
commons-lang3-api:3.17.0-84.vb_b_938040b_078
commons-text-api:1.12.0-129.v99a_50df237f7
conditional-buildstep:1.4.3
config-file-provider:980.v88956a_a_5d6a_d
content-replace:1.8.2
copyartifact:757.v05365583a_455
credentials:1384.vf0a_2ed06f9c6
credentials-binding:681.vf91669a_32e45
data-tables-api:2.1.8-1
delivery-pipeline-plugin:1.4.2
display-url-api:2.204.vf6fddd8a_8b_e9
docker-commons:445.v6b_646c962a_94
docker-java-api:3.4.0-94.v65ced49b_a_7d5
docker-plugin:1.7.0
docker-workflow:580.vc0c340686b_54
durable-task:577.v2a_8a_4b_7c0247
echarts-api:5.5.1-4
eddsa-api:0.3.0-4.v84c6f0f4969e
email-ext:1849.v6dd03b_f6e423
envinject:2.919.v009a_a_1067cd0
envinject-api:1.199.v3ce31253ed13
extended-read-permission:53.v6499940139e5
extensible-choice-parameter:1.8.1
external-monitor-job:215.v2e88e894db_f8
favorite:2.221.v19ca_666b_62f5
flatpickr-api:4.6.13-5.v534d8025a_a_59
flexible-publish:0.16.1
font-awesome-api:6.6.0-2
forensics-api:2.6.0
git:5.5.2
git-changelog:3.39
git-client:5.0.0
git-parameter:0.10.0
git-server:126.v0d945d8d2b_39
github:1.40.0
github-api:1.321-468.v6a_9f5f2d5a_7e
github-branch-source:1807.v50351eb_7dd13
google-compute-engine:4.580.v005441dfeea_d
google-oauth-plugin:1.330.vf5e86021cb_ec
gradle:2.13.1
groovy:457.v99900cb_85593
gson-api:2.11.0-85.v1f4e87273c33
h2-api:11.1.4.199-30.v1c64e772f3a_c
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
htmlpublisher:1.37
http_request:1.19
instance-identity:201.vd2a_b_5a_468a_a_6
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jacoco:3.3.7
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:280.v050b_5c849f69
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jdk-tool:80.v8a_dee33ed6f0
jenkins:1.0
jenkins-design-language:1.27.16
jenkins-jira-plugin:3.1.0
jenkins-multijob-plugin:659.v6633374ec624
jersey2-api:2.44-151.v6df377fff741
jira:3.13
jira-steps:2.0.165.v8846cf59f3db
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
jnr-posix-api:3.1.19-2
job-dsl:1.89
jobConfigHistory:1283.veb_dfb_00b_5ec0
joda-time-api:2.13.0-93.v9934da_29b_a_e9
jquery:1.12.4-3
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-101.v7a_8666713110
json-path-api:2.9.0-118.v7f23ed82a_8b_8
junit:1309.v0078b_fecd6ed
kubernetes:4296.v20a_7e4d77cf6
kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
kubernetes-credentials:190.v03c305394deb_
kubernetes-credentials-provider:1.262.v2670ef7ea_0c5
ldap:725.v3cb_b_711b_1a_ef
locale:546.v1609030511ca_
lockable-resources:1327.ved786b_a_197e0
mailer:488.v0c9639c1a_eb_3
mapdb-api:1.0.9-40.v58107308b_7a_7
matrix-auth:3.2.3
matrix-project:839.vff91cd7e3a_b_2
maven-artifact-choicelistprovider:1.17
maven-info:0.3.2
maven-plugin:3.24
mercurial:1260.vdfb_723cdcc81
metrics:4.2.21-458.vcf496cb_839e4
mina-sshd-api-common:2.14.0-133.vcc091215a_358
mina-sshd-api-core:2.14.0-133.vcc091215a_358
multiple-scms:0.8
nested-view:1.35
next-build-number:66.v4b_4762172d53
nodejs:1.6.2
oauth-credentials:0.653.v14cf2088e950
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
pam-auth:1.11
parameterized-scheduler:277.v61a_4b_a_49a_c5c
parameterized-trigger:806.vf6fff3e28c3e
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-github-lib:61.v629f2cc41d83
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:744.v5b_556ee7c253
pipeline-input-step:495.ve9c153f6067b_
pipeline-maven:1457.vf7a_de13b_c0d4
pipeline-maven-api:1457.vf7a_de13b_c0d4
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2218.v56d0cda_37c72
pipeline-model-definition:2.2218.v56d0cda_37c72
pipeline-model-extensions:2.2218.v56d0cda_37c72
pipeline-multibranch-defaults:2.1
pipeline-npm:320.vc9266a_b_fc60a_
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2218.v56d0cda_37c72
pipeline-stage-view:2.34
pipeline-utility-steps:2.18.0
plain-credentials:183.va_de8f1dd5a_2b_
plugin-util-api:5.1.0
prism-api:1.29.0-18
prometheus:795.v995762102f28
pubsub-light:1.18
rebuild:332.va_1ee476d8f6d
resource-disposer:0.24
role-strategy:743.v142ea_b_d5f1d3
run-condition:1.7
saml:4.464.vea_cb_75d7f5e0
schedule-build:577.v0613c45b_9eef
scm-api:696.v778d637b_a_762
script-security:1369.v9b_98a_4e95b_2d
sectioned-view:1.28
slack:751.v2e44153c8fe1
snakeyaml-api:2.3-123.v13484c65210a_
sonar:2.17.2
sse-gateway:1.27
ssh:2.9
ssh-agent:376.v8933585c69d3
ssh-credentials:343.v884f71d78167
ssh-slaves:2.973.v0fa_8c0dea_f9f
sshd:3.330.vc866a_8389b_58
stashNotifier:1.507.vb_7300a_1a_a_d10
structs:338.v848422169819
test-results-analyzer:0.4.1
testng-plugin:835.v51ed3da_fcc35
throttle-concurrents:2.14
timestamper:1.27
token-macro:400.v35420b_922dcb_
trilead-api:2.147.vb_73cc728a_32e
variant:60.v7290fc0eb_b_cd
versionnumber:1.11
warnings-ng:11.11.0
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1336.vee415d95c521
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3993.v3e20a_37282f8
workflow-durable-task-step:1378.v6a_3e903058a_3
workflow-job:1436.vfa_244484591f
workflow-multibranch:795.ve0cb_1f45ca_9a_
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:678.v3ee58b_469476
workflow-support:932.vb_555de1b_a_b_94
ws-cleanup:0.47
xshell:203.v80a_c62d7886f
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

jenkins/jenkins:lts Docker image on RedHat Linux

### Reproduction steps

Prerequisite: bitbucket.org is configured under "Manage Jenkins" > "System" > "Bitbucket Endpoints"

Variant A:
1.  Go to Bitbucket.org
2. Go to Workspace Settings and create an Access Token
3. Go to Jenkins and create a new set of Credentials of type "Bitbucket Personal Access Token"
4. Enter the above token in the "Token" field and save the credentials
5. Create a new pipeline project
6. Add a new branch source of type Bitbucket
7. Select bitbucket.org as the server
8. The set of credentials above is not selectable from the "Credentials" dropdown list since the plugin only supports username/password credentials and Basic authentication.

Variant B:
1.  Go to Bitbucket.org
2. Go to Workspace Settings and create an Access Token
3. Go to Jenkins and create a new set of credentials of type "Username/Password"
6. Enter "x-token-auth" as user name and the above token as password
7. Create a new pipeline project
8. Add a new branch source of type Bitbucket
9. Select bitbucket.org  as the server
10. Select the above credentials as the credentials to use
11. Enter your bitbucket.org workspace name under "owner"
12. The "Repository name" dropdown will be empty due to Basic authentication not being accepted by bitbucket.org when fetching the list of repos. (see attached screenshot)

### Expected Results

I would expect the plugin to 

A) either also accept personal access token authentication, OR
B) submit the credentials as a "Authentication: Bearer ..." header instead of "Authentication: Basic ..."

### Actual Results

A) The plugin cannot use personal access tokens as credentials and
B) the plugin also cannot submit an access token created as an username/password type credential the correct way that Bitbucket.org accepts it.

In any case, the "repository name" dropdown stays empty and therefore the configuration cannot be completed.

The POST request to https://<jenkins-hostname>/view/<project>/job/<job-name>/descriptorByName/com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource/fillRepositoryItems returns HTTP 500 Internal Server Error with the message

`The selected credentials do not have permission to determine whether <our workspace> does or does not exist.`

However, using the same credentials when issuing a raw GET request to api.bitbucket.org, they are accepted and we can list the repositories in our workspace.

Thus, the problem aren't the credentials themselves but rather the way in which the plugin submits them.

### Anything else?

My suggestion would be to 

- either support credentials of Bitbucket Personal Access token type
- submit the username/password credentials not as "Authorization: Basic <...>" but as "Authorization: Bearer <...>", or provide a setting that allows to configure that.

### Are you interested in contributing a fix?

![Image](https://github.com/user-attachments/assets/193f89b8-8995-44ce-89e4-dd3603d0c091)

**Comment by nfalco79** [comment]
Change to Enhancement, the documentation declare to support only [personal access token ](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/docs/USER_GUIDE.adoc#access-token) (Bitbucket Server only)

**Comment by nfalco79** [comment]
Duplicates #748
