### ISSUE TITLE
Commit build result is not shown within the pull request in Bitbucket cloud after the last upgrade

### ISSUE THREAD

**Issue by MazenAlkhatib** [jenkinsci/bitbucket-branch-source-plugin#941]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins 2.479.1
  ```
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Debian 12

### Reproduction steps

I am using Bitbucket cloud and since the refs for Bitbucket cloud are not supported/exposed outside of Bitbucket, the option to build PR revision won't work.

### Expected Results

Instead, my work around was to just rely on the commit build result, it was showing within the PR what was the last commit build result and if it fails I block the merge of the PR

### Actual Results

After the last release, this is not working anymore. I still can see the build result on the commit level but it's not showing within the PR anymore thus, I can't block merge because there is not notification happening on the PR level.

### Anything else?

I was able to solve it by rolling back to version `922.va_71d0e0b_7b_8d`

### Are you interested in contributing a fix?

Yes

**Comment by nfalco79** [comment]
Clones #819
