### ISSUE TITLE
Update the refname format in Bitbucket branch source plugin

### ISSUE THREAD

**Issue by spriya757** [jenkinsci/bitbucket-branch-source-plugin#945]
### What feature do you want to see added?

Hi team, 

I'm from Bitbucket Cloud team. One of our customers reported the same issue as this - https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/621#issuecomment-2463473695. Using refname as "refs/heads/master" won't show the Jenkins build in the pull request page. The correct format/usage of the field refname is just to use "master" instead of "refs/heads/master".

Can you please update the same in your plugin?
Having a null value works too.

Thank you!!

**Comment by nfalco79** [comment]
Please report issues of this plugin [to Jira](https://www.jenkins.io/participate/report-issue/redirect/#21428) rather than GitHub.

More information in https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/README.md#issue-tracking-where-file-new-issues.
