### ISSUE TITLE
Missing builds status connection with Pull Requests

### ISSUE THREAD

**Issue by stasyshyn** [jenkinsci/bitbucket-branch-source-plugin#946]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
OS `Ubuntu 24.04.1 LTS` 
The same issue was reproduced on OS `Ubuntu 22.04.5 LTS`

Jenkins version `2.490`
Bitbucket Branch Source Plugin `933.0.2`

Bitbucket Cloud 

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

OS Ubuntu 24.04.1 LTS, I have checked the os logs but I didn't find any issues.

### Reproduction steps

We used the Bitbucket Cloud + Jenkins server and I have an issue with the Pull Requests build status

On the bitbucket Cloud side, we use the Branch restrictions rules to check the Minimum number of successful builds. This allows us to make sure we merge only stable code to our Stage environment. Since the last two weeks, the build status fully has worked only for branch tabs in Bitbucket Cloud and partly for PR tabs in Bitbucket Cloud.

**Bitbucket configuration:**
1. Create a user.
2. Create an app password.
3. Add user to Repo.
4. Create Webhhok in Repo `https://jenkins-url/bitbucket-scmsource-hook/notify`
5. Configure Branch restrictions for example for `stage` branch
5.1 Minimum number of successful builds for the last commit with no failed builds and no in-progress builds -`1`
5.2 Prevent a merge with unresolved merge checks

**Jenkins configuration**

1. Add credentials with Username and App password to the credentials
2. Install the plugin Bitbucket Branch Source
3. Go to Jenkins system setting Bitbucket Endpoints 
3.1  Use Manage hooks 
3.2 Chose stored credentials from the step 1 
3.3 Use the Jenkins URL in the Custom Jenkins Root URL field. 

**Jenkins Multibranch pipeline project**
1. Use Branch Sources - Bitbucket
2. Use the same credentials from (Jenkins configuration step 1) 
3. Configure repo 
4. Run any build for any branch 
5. Create PR from the branch that was built in the Multibranch pipeline to the `stage` branch

If we go to the branches tab that was built we will see the connection to the Multibranch pipeline project - specific build 

![Image](https://github.com/user-attachments/assets/f23403b1-b4e4-4123-a9da-a5e1a2e409a6)

![Image](https://github.com/user-attachments/assets/3ae2d1a4-bd1c-433f-a6bd-b41913c193bd)

But if we go to the PR tab and check the same we see the built status icon but without connection to Builds 

![Image](https://github.com/user-attachments/assets/d2309b40-be98-4edd-a599-7554cb602ba4)

When I click on the Builds icon I don't see anything and as a result, I can't merge the PR because the build result is  successful  but without a connection to the specific build 

![Image](https://github.com/user-attachments/assets/28954d08-67ed-452b-a7ca-8860aeee6c86)

I have checked the webhook logs and it looks also fine
![Image](https://github.com/user-attachments/assets/09e32a7a-3b48-4072-935f-33677bddcb47)

### Expected Results

Fixing the issue with the connection between Bitbucket Cloud PR and Jenkins Multibranch pipeline project via  Bitbucket Branch Source Plugin 

### Actual Results

I can't use it like it was before the Jenkins Multibranch pipeline project with Branch Sources - Bitbucket because this broke my automation

**Comment by nfalco79** [comment]
Please report issues of this plugin [to Jira](https://www.jenkins.io/participate/report-issue/redirect/#21428) rather than GitHub.

More information in https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/master/README.md#issue-tracking-where-file-new-issues.
